### PR TITLE
correct classpath references and java version

### PR DESCRIPTION
**Pull request by fmaali**
- updated classpath references to existing versions of the libraries.
- Java version upgraded to 7 as some Java 7 specific features are used.
- corrected references to old project name (grefine-all) in the launch script

### CODE REVIEW

**Comment by thadguidry** [comment]
@fmaali The build broke... Hmm, I wonder if its an env issue ?  Can you take a look  https://travis-ci.org/OpenRefine/OpenRefine/jobs/255029967

**Comment by fmaali** [comment]
@thadguidry I guess it is an env problem... seeing this error on Travis:
Error: Error while uploading main/tests/data/food.csv to OpenRefine

tests run fine locally. Is there a way to re-trigger the build?

**Comment by thadguidry** [comment]
@fmaali I'm checking that now...

**Comment by thadguidry** [comment]
@fmaali OK, there's some weirdness happening on Travis for me... its just spinning when I try to do a sync....that doesn't seem right.  I'll try again tomorrow (although their status light shows green like all systems are OK)

**Comment by thadguidry** [comment]
@fmaali
build 364 failed https://travis-ci.org/OpenRefine/OpenRefine/builds/255029966
build 365 passed https://travis-ci.org/OpenRefine/OpenRefine/builds/255062631

I think we're good now.

**Comment by fmaali** [comment]
thanks for looking after this @thadguidry

**Pull request merged**
