### PR TITLE
Closes dialogs when escape key is pressed

### LINKED ISSUE #1018: Close modal dialogs on ESC key
We need a possibility to close any modal window by pressing "Escape". Like we have this behaviour now on cells' "Edit", and "Rename this column" windows.

### PR DESCRIPTION
**Pull request by lisa761**
Closes #1018 
Closes all dialog boxes (created through `DialogSystem`) when escape key is pressed

### CODE REVIEW

**Comment by thadguidry** [comment]
@lisa761 Thanks!  Curious, was an outside click asked for in the issue?  Do you think this might cause a user some grief if they spent 10 mins configuring a dialog to their settings (looking up details on other screens, etc. SQL schema from Oracle, Templates from an outside spec) ... and then an errant click would lose the dialog info they patiently typed in?

**Comment by lisa761** [comment]
@thadguidry You're right, I didn't think that far ahead (I just found it in the edit cell that was mentioned in the issue and thought it was a nice addition), it would definitely cause problems to those who did it by mistake. Should I remove it then?

**Comment by thadguidry** [comment]
@lisa761 Try it out as a user on a few of the dialogs and then see how it feels for a user...then make your decision :-)

**Comment by wetneb** [comment]
Congratulations for this PR!! \o/

One thing I am wondering is whether this could be implemented in a single place (the `DialogSystem`) which would apply to all the dialogs used in OpenRefine. That would avoid duplicating this logic in many places :) Have you considered moving some of this into the `DialogSystem.createDialog`, `DialogSystem.showDialog` and `DialogSystem.dismissUntil` methods?

**Comment by lisa761** [comment]
@thadguidry @wetneb Thanks, for helping out :) I made the changes

**Comment by lisa761** [comment]
@wetneb yes, I can do that by globally declaring `escapeKey`

**Pull request merged**
