### PR TITLE
Removed references to freebase in messages #2029

### LINKED ISSUE #2029: remove references to freebase in messages
**Describe the bug**
One day I had a warning message mentioning Freebase, in OR 3.1... Not sure of it but I think it was this one in https://github.com/OpenRefine/OpenRefine/blob/e57228a1306f19313c52d4a967866f193fc02dfb/main/webapp/modules/core/langs/translation-en.json : 
 
"I You haven't done any schema alignment yet,\n so there is no triple to export.\n\n Use the Freebase > Edit Schema Alignment Skeleton...\n command to align your data with Freebase schemas first."

Maybe there are others.

**To Reproduce**

**Current Results**
What results occured or were shown.

**Expected behavior**
A clear and concise description of what you expected to happen or to show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows 10, Linux, Ubuntu 18.04]
 - Browser Version: [e.g. Chrome 19, Firefox 61, Safari, NOTE: OpenRefine does not support IE but works OK in most cases]
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version [e.g. OpenRefine 3.0 Beta] : Openrefine 3.1

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

### PR DESCRIPTION
**Pull request by darecoder1999**
Removed all freebase references from all translation files
Closes #2029

### CODE REVIEW

**Comment by thadguidry** [comment]
Thanks Ekta!  Could you check in our Java/JS to see if we even use the exportTripleloader anymore where `warning-align` is the only place found? Perhaps that function can be removed as well? Was it only used for Freebase?  Dig in, starting here: https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/project/exporters.js#L112

**Comment by ostephens** [comment]
@thadguidry would you be ok to have a separate issue for that, as it would be good to get this PR done and #2029 fixed separately to digging into other potential Freebase cleanup

**Comment by thadguidry** [comment]
Sorry, I'm used to making comments within PR's where my previous team's knew to create the issues themselves and help drive with peer feedback.  They knew how to isolate PR's and create new issues when appropriate based on feedback from peers.

I gotta pull back from my "enterprise" mode, I guess? :-)

**Comment by darecoder1999** [comment]
@ostephens @thadguidry How should I proceed? Should I create a new issue and then start working on that? Please direct me. Thank you.

**Comment by thadguidry** [comment]
@darecoder1999 yes, create a new issue to isolate the "remove freebase functions no longer needed".  And thank you so so so much Ekta!

**Comment by ostephens** [comment]
@darecoder1999 as part of this issue can you also check for any use of these warning messages in the code (I think you'll find some in https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js) and make sure these calls are removed as well

**Comment by darecoder1999** [comment]
Okay @ostephens sir, I'll check that too. Thank you.

**Comment by darecoder1999** [comment]
@thadguidry @ostephens sir, I have checked for the use of the warning messages corresponding to the translation files. I have found some calls to `'core-views/recon-text-fb'` in https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/scripts/views/data-table/menu-reconcile.js (thank you @ostephens) but I feel that function in the js file is part of dead-code and can be safely removed. I don't have a great knowledge of JavaScript in the frontend, I have mostly worked with node.js and express.js in the backend. Therefore, I was looking for your call about this before making the commits.

**Comment by wetneb** [comment]
It's not dead code :)
Open any project in OpenRefine, click on the triangle next to a column to open the column menu, go to `Reconcile` -> `Start reconciling...` without clicking: just hovering `Start reconciling...` will display the message as a tooltip.
image

So this message needs to be replaced by something not specific to Freebase.

**Comment by darecoder1999** [comment]
@wetneb sir thank you so so much for clarifying my misconception. Earlier I had the thought that these messages should be removed from the issue discussion. Thanks once again.

**Comment by ostephens** [comment]
My suggestion would be to replace:
"Reconcile text in this column with items on Freebase" with
"Reconcile text in this column with items in another data source"

**Comment by darecoder1999** [comment]
@wetneb @ostephens Thanks for suggestions. With your guidance, I have made the required changes. Kindly review this PR. Thanks once again. :smile:

**Comment by darecoder1999** [comment]
@wetneb Can you please merge this PR if that is fine?

**Pull request merged**
