### PR TITLE
Tweak the suggest dialog to display descriptions

### PR DESCRIPTION
**Pull request by wetneb**
image
for issue #1378.

This makes it possible for any reconciliation service to return an additional `"description"` field in each suggest result. Descriptions are optional (if no description is provided, the item is displayed as before).

If this PR is accepted, I will update the documentation to indicate that this is supported.

### CODE REVIEW

**Comment by thadguidry** [comment]
@wetneb works as advertised.  can't wait to have the new interface for this down the road !

**Comment by wetneb** [comment]
@thadguidry feel free to propose new properties at Wikidata… we're always happy to discuss new properties, especially if it's not yet another external id… and then try to populate them with the wikidata extension maybe?

**Comment by thadguidry** [comment]
@wetneb yes, there's a lot that is needed.  I'll get around to them sometime this year. no worries.

**Comment by wetneb** [comment]
@jackyq2015 @ostephens happy with merging this?

**Pull request merged**
