### PR TITLE
Fallback to English language to avoid need to maintain 'default' translation files.

### PR DESCRIPTION
**Pull request by MattBlissett**
I found

```
    // TODO: Switch this to just use English as the default language so we
    // so we don't have to maintain a separate redundant file.
```

so have done this.

The extension translations were identical, there was one difference between the core default and en files.

### CODE REVIEW

**Comment by thadguidry** [comment]
:+1:

**Comment by magdmartin** [comment]
+1

**Comment by wetneb** [comment]
It looks like this PR is pretty uncontroversial but still has not been merged after two years… If no one complains I will merge this in the coming days.

**Comment by jackyq2015** [comment]
I am fine to merge this.

**Pull request merged**
