### PR TITLE
Enable clustering using custom functions from dropdown menu

### PR DESCRIPTION
**Pull request by zyadtaha**
This is the fifth PR in the GSoC project. 

Changes proposed in this pull request:
- Add custom functions from clustering functions dialog to dropdown menu
- Enable clustering based on custom functions selected from the dropdown

#### Here's a demo:

https://github.com/user-attachments/assets/370a5835-bf20-4406-979c-bb86a7051c75

### CODE REVIEW

**Review by wetneb — APPROVED** [review]
Looks great to me. Tested manually, it seems to work well. Let's leave it open a bit longer in case others notice issues.

**Comment by zyadtaha** [comment]
> Looks great to me. Tested manually, it seems to work well. Let's leave it open a bit longer in case others notice issues.

Thanks for your feedback! I'll include a Cypress test to ensure the entire feature is covered.

**Comment by zyadtaha** [comment]
I believe this is ready to merge, but I'd prefer to wait until #6738 is merged, just in case we need to add any additional updates related to the feature.

**Comment by zyadtaha** [comment]
Since the feature is nearly complete, I drafted this as a hint for users.

`Personalize your clustering strategy by writing expressions in GREL, Jython, or Clojure to better align with your data, achieve more accurate results, and explore innovative approache. Find out more…
`

**Pull request merged**
