### PR TITLE
adding zst, zstd compression support

### LINKED ISSUE #4058: Add support for importing "zst", "zstd" files
I would like to import a `.zst` or `.zstd` file but currently that file type is not recognized to be imported by OpenRefine.

### Proposed solution
Perhaps using Apache Commons Compress (we already have usage in `ImportingUtilities.java`)
https://commons.apache.org/proper/commons-compress/examples.html#Zstandard

### Additional context
RFC standard: `RFC 8478`
mime type: `application/zstd`
official website: https://facebook.github.io/zstd/
example file:  https://github.com/facebook/zstd/blob/dev/tests/golden-decompression/rle-first-block.zst
example code Apache Druid: https://github.com/apache/druid/blob/8296123d895db7d06bc4517db5e767afb7862b83/core/src/test/java/org/apache/druid/java/util/common/CompressionUtilsTest.java#L366

### PR DESCRIPTION
**Pull request by rachittiwari8562**
Fixes #4058 

Changes proposed in this pull request:
Tried adding "ZstdCompressorInputStream".

### CODE REVIEW

**Comment by wetneb** [comment]
Nice! Perhaps you could try adding an accompanying test, as a unit test on the `tryOpenAsCompressedFile` method? That would hopefully help you debug :)

**Comment by thadguidry** [comment]
@rachittiwari8562 Don't give up on this!  You can do this and the whole OpenRefine community would really appreciate your efforts!

**Comment by rachittiwari8562** [comment]
> @rachittiwari8562 Don't give up on this! You can do this and the whole OpenRefine community would really appreciate your efforts!

I will get back to this after 2 days . Right now a little busy on college courses.

**Comment by wetneb** [comment]
@rachittiwari8562 this PR looks like it is on the right track, and I can imagine it should be doable to write an accompanying test. If you need help with that let me know :)

**Comment by wetneb** [comment]
We have a new version of this PR at #4522.

**Pull request closed without merging**
