### PR TITLE
render geo: URIs as links in cells

### PR DESCRIPTION
**Pull request by Abbe98**
https://en.wikipedia.org/wiki/Geo_URI_scheme

### CODE REVIEW

**Review by wetneb — APPROVED** [review]
Looks good to me.

**Comment by wetneb** [comment]
It works for me both with Firefox and Chromium on Debian. It offers to open Gnome Maps, which then shows a slippy map with a marker at the desired coordinates.

**Comment by Abbe98** [comment]
With FF and Chromium on Fedora I'm given the following options: Gnome Maps, Google Maps, and OpenStreetMap

**Comment by ostephens** [comment]
I've been trying to find how well supported this is across browsers, and haven't been able to find a lot - but support looks patchy tbh (this page doesn't list browsers but it does offer some insight into adoption https://wiki.openstreetmap.org/wiki/Geo_URI_scheme and it's not great)

However, that said it seems to me reasonably likely that if you are dealing with data with Geo URIs then you'll have some understanding of what they are - so I'm OK with this display if it's helpful to those users

**Comment by wetneb** [comment]
Interesting, I did not suspect this could be platform dependent.

**Comment by ostephens** [comment]
There is a plugin for FF. Not tried it but https://addons.mozilla.org/en-GB/firefox/addon/geo-uri-handler/

**Comment by Abbe98** [comment]
> However, that said it seems to me reasonably likely that if you are dealing with data with Geo URIs then you'll have some understanding of what they are - so I'm OK with this display if it's helpful to those users

I could imagine this being the situation for most schemes other than mailto, tel, http, https, etc.

**Comment by tfmorris** [comment]
By "common" I meant browsers with substantial [market share](https://gs.statcounter.com/browser-market-share/desktop/worldwide) - and, by extension, the [operating systems](https://gs.statcounter.com/os-market-share/desktop/worldwide/) they run on.

Safari on Mac at least pops up an error dialog, but Chrome on Mac only logs an error to the Javascript console.

What happens on **popular** browsers like Chrome on Windows? That's what should shape the UX decisions.

**Pull request merged**
