### PR TITLE
enh: Enhancements in Recon Search dialogue

### PR DESCRIPTION
**Pull request by kushthedude**
Refers #2332

### CODE REVIEW

**Comment by kushthedude** [comment]
> the behaviour of "match all similar cells" should be changed to take into account any other columns set up during reconciliation.

Hmm, I didn't look into it. Let me give it a shot as Java is new to me.

**Comment by wetneb** [comment]
@kushthedude do you intend to make progress on this PR or should we close it?

**Comment by kushthedude** [comment]
Actually due to Lockdown in my area, I have low connectivity from a few days due to which I am not able to update my old PRs and also not able to work on new issues right now. I will update it in few days and also open PRs which are pending for issues assigned to me once the issue gets resolved.

**Comment by wetneb** [comment]
Sure, there is no rush at all!

**Comment by kushthedude** [comment]
I have messed my local branch, will open a new one ! Thanks for holding up @wetneb 😄

**Pull request closed without merging**
