### PR TITLE
Using the parsed form parameter 'options' instead of looking for an U…

### PR DESCRIPTION
**Pull request by ancore**
This fix solves [Issue #1757](https://github.com/OpenRefine/OpenRefine/issues/1757).

### CODE REVIEW

**Comment by wetneb** [comment]
@ancore great, thanks a lot! Sorry for the delay in reviewing. Ideally it would be useful to have a unit test demonstrating that the options are recognized in the exporter.

**Comment by nsiebler-dm** [comment]
Any possibility to finalize this? Would be much appreciated.

**Comment by ostephens** [comment]
@ancore @nsiebler-dm we'd really prefer to have a unit test which checks for the correct behaviour alongside this change - we always try to add tests when we change code because we have had a history of poor test coverage.

Is there any chance tests could be added to this PR?

**Comment by wetneb** [comment]
@ostephens makes a lot of sense! Merging this then.

**Comment by thadguidry** [comment]
@ostephens Correct, more correctly, Stefano added it for Windmill-based UI testing.  Command used on L259 within...
https://github.com/OpenRefine/OpenRefine/blame/95d0cf546d37dc81c493c9ef09e946a7547cd1ba/refine#L256
Original commit here: https://github.com/OpenRefine/OpenRefine/commit/6dbe794658feae7acda9e29a45315b42ece0fa47

**Pull request merged**
