### PR TITLE
Add test for KeyValueColumnize

### PR DESCRIPTION
**Pull request by wetneb**
In relation to #1214, this PR just adds a test to demonstrate the way KeyValueColumnize deals with records and therefore requires to see the rows in a particular order to work correctly.

The point is just to make sure that the existing functionality is preserved by future contributors. And increase our test coverage, which seems to be very low at the moment.

### CODE REVIEW

**Comment by wetneb** [comment]
Whoops, curious that there is this discrepancy between OpenJDK and OracleJDK. Thank you Travis!

**Comment by wetneb** [comment]
@thadguidry that's a good idea! feel free to add that on the branch (it's a branch in this repo so you can push to it)

**Comment by thadguidry** [comment]
@wetneb liking Codacy so far ?

**Comment by wetneb** [comment]
@thadguidry yeah it's clearly better than coverall with the code review features!

**Comment by thadguidry** [comment]
@wetneb OK.  For this one, as long as we get the additional test and things pass and Travis is happy and no errors (warnings OK for now) on Codacy, then you can accept commit.  We'll probably want to tweak Codacy for our project eventually (ignoring a few things, etc)... we should probably schedule a hangout with Jacky after summer break..September-ish.  Sound good ?

**Comment by wetneb** [comment]
@thadguidry yeah it'd be good to configure it a bit so that only relevant issues are reported. Sure, happy to hangout when you want!

**Comment by wetneb** [comment]
The code review features are nice but I think the most important thing is the code coverage. Because 20% coverage is *really* low for a big project like that.

**Pull request merged**
