### PR TITLE
Add support for JSON Objects to forEachIndex() control

### LINKED ISSUE #3147: Implement `forEachItem` for JSON object
Users have ongoing complaints about the difficult in parsing  JSON which has arbitrary structure, most often in the form of JSON API responses which were designed to return objects keyed by arbitrary identifiers rather than just returning array as the vast more of APIs do.

Examples provided in #2186 include:
* Wikimedia Commons -> https://commons.wikimedia.org/w/api.php?action=query&titles=File:Google%202015%20logo.svg&prop=imageinfo&iiprop=url&format=json
* MySociety MapIt -> https://mapit.mysociety.org/point/4326/0.1293497,51.5464828

And the issue has been discussed both on the OpenRefine mailing list and StackOverflow:
* https://groups.google.com/d/msg/openrefine/O72bg8GZkj8/vBoEzmGxBwAJ
* https://stackoverflow.com/questions/10782737/google-refine-iterate-over-a-json-dictionary

### Proposed solution

Similar to the `forEachIndex` function that we have for arrays, we would implement a `forEachItem` iterator control which would accept a JSON node object, two variable names (one for key and one for value), and a GREL expression. It would iterate over each item in the JSON object, assigning the string value of the key to the key variable and the value for the item to the value variable and then execute the GREL expression.

The control would **only** accept a JSON object to iterate over and would explicitly **not** support iterating over objects that implement the `HasFields` interface.

### Alternatives considered
* extend `forEach()` to iterate over JSON object items. This wouldn't provide access to the field name / key, but would probably satisfy the vast majority of cases since the key is usually included in the child object as an id.
* implement iteration for every object that implements HasFields. Since OpenRefine `HasFields` objects typically have a small fixed set of fields, this seems to have limit value.

### PR DESCRIPTION
**Pull request by tfmorris**
Fixes #3147

I'm on the fence as to whether this should be a separate control (name TBD), as I originally spec'd, or if rolling the functionality into the existing `forEachIndex` is close enough semantically given that the array index and the object key are both performing essentially the same function. This pull request adopts the latter approach. Doing it the other way would basically involve cloning the code, giving it a new function name, and making the error messages more specific.

Changes proposed in this pull request:
- add tests for `forEachIndex`
- enhance error checking to reject using the same variable name for both index and value
- add support for JSON objects withe same structure, but the object key instead of the array index returned in the index/key variable

### CODE REVIEW

**Comment by tfmorris** [comment]
What do folks think about the approach of extending `forEachIndex()` as opposed to creating a separate `forEachEntry()` or `forEachItem()` or some such?

I'm not wedded to this approach, but it does allow reuse of a lot of the existing machinery and doesn't seem like a hugely awkward extension.

**Comment by wetneb** [comment]
Maybe @ostephens has thoughts on the matter?

**Comment by ostephens** [comment]
`Added comment on #3147 but in summary I'm fine with this approach

**Comment by tfmorris** [comment]
@ostephens Thanks for the review and the feedback.
@wetneb If you are satisfied with the `hashCode()` update, can you please approve?

**Review by wetneb — APPROVED** [review]

**Pull request merged**
