### PR TITLE
Switch to standard Coveralls action. Fixes #6493

### LINKED ISSUE #6493: Improve Coveralls reporting
Currently we submit two different Coveralls jobs per build (Java 11 & Java 21) and it's very difficult to tell them apart. You need to trace from the build log files to get the Coveralls job number to know what build correlates with what job.

It's not clear to me that we get a lot of value out of coverage per Java version, so we can either:
1. Eliminate one of the builds
2. Add disambiguating information so that we know what Coveralls job goes with what build

While researching this, I discovered that the Maven plugin we're using has been deprecated and that the Coveralls [Universal Coverage Reporter](https://github.com/coverallsapp/coverage-reporter) has built-in support for our coverage tooling, so we should probably just switch to that and the standard [Github action](https://github.com/coverallsapp/coverage-reporter/blob/master/doc/examples/github-actions-default.yml)

### PR DESCRIPTION
**Pull request by tfmorris**
Fixes #6493

Changes proposed in this pull request:
- Switch to standard Coveralls GitHub action
- Add Java version as job flag
- Remove old Maven plugin integration for Coveralls

Draft until I see if it works...

### CODE REVIEW

**Comment by tfmorris** [comment]
I'm not sure what's going on with the reported drop in coverage here.  Coveralls is taking the same relevant/covered/missed counts and computing different percentages:

New 

COVERAGE	∆	FILE	LINES	RELEVANT	COVERED	MISSED	HITS/LINE	BRANCH HITS	BRANCH MISSES
31.25		[...om/google/refine/importing/ImportingUtilities.java](https://coveralls.io/builds/66599194/source?filename=main%2Fsrc%2Fcom%2Fgoogle%2Frefine%2Fimporting%2FImportingUtilities.java)	1209 - 3	568	194	374	9.0 + 8	76 + 76	220 + 220
21.1		[...google/refine/model/changes/ColumnSplitChange.java](https://coveralls.io/builds/66599194/source?filename=main%2Fsrc%2Fcom%2Fgoogle%2Frefine%2Fmodel%2Fchanges%2FColumnSplitChange.java)	436 - 3	223	50	173	10.0 + 9	19 + 19	85 + 85

Current

COVERAGE	∆	FILE	LINES	RELEVANT	COVERED	MISSED	HITS/LINE
34.15		[...om/google/refine/importing/ImportingUtilities.java](https://coveralls.io/builds/66617983/source?filename=main%2Fsrc%2Fcom%2Fgoogle%2Frefine%2Fimporting%2FImportingUtilities.java)	1212	568	194	374	1.0
22.42		[...google/refine/model/changes/ColumnSplitChange.java](https://coveralls.io/builds/66617983/source?filename=main%2Fsrc%2Fcom%2Fgoogle%2Frefine%2Fmodel%2Fchanges%2FColumnSplitChange.java)	439	223	50	173	1.0

The top line summary for the [new run](https://coveralls.io/builds/66599194) is internally inconsistent (62% vs 66%):
COVERAGE: **_62.207%_** (-3.7%) FROM 65.887%
RUN DETAILS
6594 of 12107 branches covered (54.46%)

Branch coverage included in aggregate %.

16784 of 25474 relevant lines covered (**_65.89%_**)

I'm tempted to accept the one-time drop in coverage of ~3% and just keep an eye on how it performs going forward.

**Comment by tfmorris** [comment]
I'm going to declare this done unless someone else can spot the source of the coverage discrepancy.

The only remaining question is whether we really need to run coverage separately for multiple compiler JVM versions.

**Review by wetneb — CHANGES_REQUESTED** [review]
Nice! I think it's fine to have this difference in coverage stats, as you say it's more the difference for each pull request that matters.

I'd be indeed in favor of reporting coverage for only one Java version (say 21) because it's quite a lot more PR checks otherwise. I think it's rare that the Java version makes any difference (the case of date parsing being a recent counter-example).

As an additional clean-up one could remove the `coveralls-maven-plugin.version` property from `pom.xml`.

**Review by wetneb — APPROVED** [review]

**Comment by tfmorris** [comment]
I've addressed the review comments and squashed a bunch of the experimental commits. I suggest ignoring white space for the review because there is one large-ish section of wonking indenting that I fixed adjacent to another edit I made to make the styles all match.

**Pull request merged**
