### PR TITLE
Let's move the Readme for UX tests into the main/tests folder

### PR DESCRIPTION
**Pull request by thadguidry**
this will make it easier to also see from GitHub perspective if news devs are just browsing.

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
Since it applies to the UX tests, I think we should keep it in the folder for UX tests.

**Comment by thadguidry** [comment]
@wetneb renamed the title so it's more clear.  Perhaps you missed the **Files changed** however?
** main/tests/cypress/Readme.md → main/tests/Readme.md **

**Comment by wetneb** [comment]
Thad,

The directory `main/tests` currently contains both backend tests written in Java and integration tests with Cypress. The README file you moved is specific to the integration tests, with Cypress. Therefore it makes sense to keep this file in a directory which is specific to Cypress tests. Which is its current location. So I would close this PR without merging it.

Is this clear?

**Comment by thadguidry** [comment]
Ah! Sorry, didn't catch the backend tests.  Yeah, closing.

**Pull request closed without merging**
