### PR TITLE
add find function. issue 1296

### PR DESCRIPTION
**Pull request by jackyq2015**

### CODE REVIEW

**Comment by ettorerizza** [comment]
Thank you, @jackyq2015 !

screenshot-127 0 0 1-3333-2018-01-15-09-15-59-970

**Comment by jackyq2015** [comment]
why the new change won't trigger the build?!

**Comment by jackyq2015** [comment]
@ettorerizza Thanks for the documentation.

**Comment by isaomatsunami** [comment]
Why did anyone find that we need "find" until 2.8?
Great improvement!!!!!!!

**Comment by ettorerizza** [comment]
@jackyq2015 I juste noticed a [strange behavior](https://github.com/OpenRefine/OpenRefine/pull/1558#issuecomment-378891252) by reviewing the new `contains() `PR (very similar to your `find()` ) 

Looks like some special charcaters are always matched.

screenshot-127 0 0 1-3333-2018 04 05-13-33-02

**Pull request merged**
