### PR TITLE
Add maven build configurations

### PR DESCRIPTION
**Pull request by junwei-wang**
- Add a set of `pom.xml` for maven building tools.
- Add maven build information in README.md

### CODE REVIEW

**Comment by jackyq2015** [comment]
seems that the butterfly library still missing. Could you please take a look?

**Comment by junwei-wang** [comment]
@jackyq2015 It is because butterfly library is not in Maven repository. 
Test the following command
```
mvn initialize
mvn clean compile
```

**Comment by jackyq2015** [comment]
I see. Can you check the .Travis.yml under the root dir and change the
refine script to instruct  Travis to build it as the steps you mentioned?

**Comment by wetneb** [comment]
Hi @junwei-wang,

I'd like to merge this but it seems that the repository where the PR was from has been deleted. If you still have the data somewhere, do you think you could file a new PR? The only solution I see for me is to download the files individually and commit them myself, but that would not preserve attribution and it's quite dirty.

Thanks a lot for your help!

**Comment by junwei-wang** [comment]
I am sorry that the repo has been deleted.

**Comment by wetneb** [comment]
@junwei-wang no problem! it should have been merged long ago. Closing then.

**Comment by magdmartin** [comment]
Now available in  #1493

**Pull request closed without merging**
