### PR TITLE
Issue/1287 data part for nano

### PR DESCRIPTION
**Pull request by jackyq2015**

### CODE REVIEW

**Comment by thadguidry** [comment]
I already stated my design decision to get past the differing opinions.
That is to go forward...take the extra effort and time to go to Java 8
classes and using java.time as necessary. We will not use Java 7 classes.

**Comment by wetneb** [comment]
@thadguidry dear "Lead Designer", let's have a call maybe? I value your feedback as a user but this is about a technical decision.

**Comment by thadguidry** [comment]
Can't. On vacation. Do not rush. We have time to do this right is what I am
saying.

**Comment by wetneb** [comment]
I was hoping to get a release before 20th May, so that it's ready for the Wikimedia Hackathon 2018, but that's not going to happen then. I guess I'll just release a snapshot with the fixes and the extension then.

**Comment by jackyq2015** [comment]
@webnet No worry. you can cut a tag or branch to hold the version for the Wikimedia Hackathon 2018. At the same time, i will have a branch to fully migrate to java 8 time API. It will take a while but it is not impossible to finish before 20th. But if we cannot make it, you can still have the branch to show. :) what do you think?

**Comment by wetneb** [comment]
@jackyq2015 thanks! But this is a big change that needs thorough reviewing and testing, so even if we manage to do it quickly we should not rush to release that…

**Pull request merged**
