### PR TITLE
Update Jython to 1.7.1.

### PR DESCRIPTION
**Pull request by wetneb**
Related to #1236.

I have no idea why this breaks the URL caching test (this is seemingly unrelated). This should be fixed before merging.

### CODE REVIEW

**Comment by wetneb** [comment]
Hmm, the failure seems to be random as Travis did not encounter it this time… Looks like a race condition somewhere.

**Comment by thadguidry** [comment]
No delete for the Jython 2.7.0 jar file ? or am I missing something or my git index is freaking out ?

**Comment by wetneb** [comment]
@thadguidry I think I did remove the 1.7.0 version, see the changes here: https://github.com/OpenRefine/OpenRefine/pull/1238/files

**Comment by thadguidry** [comment]
@wetneb yeah, its my git index... fixed it... so this is good.  MERGE PLEASE

**Pull request merged**
