### PR TITLE
Issue 3453, organized the test suite

### PR DESCRIPTION
**Pull request by fgiroud**
Implements #3453
* renamed tests
* created empty folders for further tests

### CODE REVIEW

**Comment by fgiroud** [comment]
@wetneb This PR also contains an attempt to change the syntax for sorting tests, let's see if it fixes the flaky tests for the new version of OpenRefine

**Comment by fgiroud** [comment]
@kushthedude test failed, saying Cypress binaries are missing
Do you think this is somehow related on your PR [3454](https://github.com/OpenRefine/OpenRefine/pull/3454) about cypress cache ? It that possible that cache has been shared across actions ?
If we merge your PR first, would it solves this issue ?
Thx

**Comment by kushthedude** [comment]
Yes merging that PR will fix these issues.

**Comment by kushthedude** [comment]
@fgiroud you can update the branch and see the fix.

**Comment by fgiroud** [comment]
@kushthedude I have re-runned the actions and it's still failing, do you understand why ?

**Comment by kushthedude** [comment]
You will need to rebase with master to pull in latest changes.

**Comment by fgiroud** [comment]
@kushthedude still, I've cherry-picked the commits but it's not working.
Also, I believe that when using "PR target", the workflow files used are the one from the master, not the one from the PR

**Comment by kushthedude** [comment]
> @kushthedude still, I've cherry-picked the commits but it's not working.
> Also, I believe that when using "PR target", the workflow files used are the one from the master, not the one from the PR

Yeah but it's still not taking in new workflow as there is a dedicated `Setup Node` in new workflow which I still can't find in this PRs workflow

**Comment by wetneb** [comment]
@kushthedude that is normal, see the documentation of the `pull_request_target` event.

**Comment by fgiroud** [comment]
Well, it looks like PRs are mutually blocking, maybe we can merge this into master without having the UI tests green, there are almost no changes, only renaming and creating folders.

**Review by wetneb — APPROVED** [review]

**Pull request merged**
