### PR TITLE
Add UX Test for column / Text filter

### LINKED ISSUE #3421: Add UX Test for column / Text filter
Test the Column / Text filter

Screen Shot 2020-12-16 at 13 48 08

### Proposed solution

Add a test for the behavior with
* an exact string, check the number of occurrences
* a partial string, also check the number of occurrences
* Test case sensitive
* Test a regular expression

### PR DESCRIPTION
**Pull request by S-Harshit**
fixes #3421

Please let me know if this is ok as this is my first time using Cypress.

### CODE REVIEW

**Comment by fgiroud** [comment]
Thanks a lot @S-Harshit !
Few things
- the file should be located at project/grid/column/text_filter.spec.js, in order to mirror the UX
- please format your code according to the .prettierrc file

**Comment by S-Harshit** [comment]
I have changed the location to  project/grid/column/text_filter.spec.js
and I think one check is failing due to issue #3569 and should be fixed after that PR is Merged

**Comment by fgiroud** [comment]
@S-Harshit the file should be located at project/grid/column/text_filter.spec.js, in order to mirror the UX

**Comment by S-Harshit** [comment]
I have Renamed The File to text_filter.spec

**Review by fgiroud — APPROVED** [review]

**Review by fgiroud — APPROVED** [review]

**Pull request merged**
