### PR TITLE
Broken link in reconciling.md

### PR DESCRIPTION
**Pull request by padefla**
The link at line 20 is broken.
It should be:  [clean and cluster](https://docs.openrefine.org/manual/cellediting)

Fixes #{issue number here}

Changes proposed in this pull request:
- 
- 
-

### CODE REVIEW

**Comment by wetneb** [comment]
Hi @padefla, thanks for this PR!

I cannot reproduce the issue on my side: when I go to https://docs.openrefine.org/manual/reconciling and click "clean and cluster", I am directed to https://docs.openrefine.org/manual/cellediting as expected.

Which browser and operating system is this happening with?

**Comment by wetneb** [comment]
Ah, hang on, I can actually reproduce that too. It seems to be due to the presence (or absence) of a trailing slash at the end of the current page URL.

For instance, if you go to https://docs.openrefine.org/manual/reconciling, the links there will work, but if you go to https://docs.openrefine.org/manual/reconciling/, the links will not work.

**Comment by padefla** [comment]
Hi @wetneb,
I am using Firefox 87.0 on macos 10.14.6 (18G8022)
when I click "clean and cluster", I am directed to https://docs.openrefine.org/manual/reconciling/cellediting which returns a "Page Not Found"

**Comment by padefla** [comment]
I just noticed that when I use https://docs.openrefine.org/manual/reconciling to get the page, after loading the URL displayed is actually https://docs.openrefine.org/manual/reconciling/

**Comment by wetneb** [comment]
@padefla yes I also noticed that. I have just changed deploy settings and I think this has solved the issue, can you check on your side? When you click on https://docs.openrefine.org/manual/reconciling, no trailing slash should get added to the URL.

We still have the issue that if someone does visit a URL with a trailing slash, the links will be broken there. I am looking into adding a bit of JS to automatically remove those trailing slashes.

**Comment by padefla** [comment]
Now it works fine.

Thank you for the prompt reaction.

Have a nice day!

**Pull request closed without merging**
