### PR TITLE
Fixes #3364 expanded the sqlexporter dialogs on translation-en.json

### LINKED ISSUE #3364: Clarify options on the SQL exporter dialog
The options "Include Schema" and "Include Contents" in the SQL exporter dialog can be a bit mysterious for users.

### Proposed solution

Just like concrete SQL commands are included in the UI text elsewhere in the dialog ("DROP"), we could expand these phrases to mention the corresponding SQL commands ("CREATE TABLE", "INSERT").

### Alternatives considered

We could also drop the mentions of the commands elsewhere, but I think they are useful (and clear for users who know SQL).

### PR DESCRIPTION
**Pull request by Armaxxx**
The option in the SQL Exporter Dialog has been clarified, it now should be clearer what the option does.

### CODE REVIEW

**Comment by wetneb** [comment]
Thank you and congratulations for this first pull request!

Sorry for the failure of the Java CI, that is indeed unrelated to your changes.

Here are a few things we can improve:
* in the description of your pull request, please add "Fixes #3364", so that github understands that merging this pull request will close the corresponding issue
* Have you considered following the suggestion in the issue, to mention the corresponding SQL commands (which are written in uppercase by convention)?

**Comment by Armaxxx** [comment]
I haven't considered, will do better next time, thank you very much for real.

**Comment by wetneb** [comment]
@Armaxxx it would be great if you could address these points in this pull request already.

**Comment by Armaxxx** [comment]
Yeah, on it.

**Review by wetneb — APPROVED** [review]

**Pull request merged**
