### PR TITLE
Better error reporting in Wikibase schema

### LINKED ISSUE #4724: Saving the Wikidata Schema sometimes gives an error message that is imprecise and unhelpful. The problem should be describe instead.
We have non-negligeable problems in the Wikidata Schema’s validation process. A lot a times, even if the schema is good (what's visually in our face), the validation fails with a genereic and very unhelpful error message that can make a normal user grow some impatiance trying to find why it failed.

This is also for the error when saving a schema. Sometime, when there's problems, it just says it can't save the schema.

### Proposed solution
A clue to what might actually be not working not just a simple and obvious « I won't do it ».
I would like to know EXACTLY where the problem is.

- if it's the data, which column (and maybe the index of fautive rows?)
- if it's a schema field, which one? Item # + Term ID or Statement #, Reference # and/or Value # if also applicable.
- I could live with only the next error.

### Alternatives considered
Either search everything till it works, or cry…

### Additional context
[Please note that I did experience that issue a lot and it might have an impact on how I describe this issue.]

### Screenshots
image

### PR DESCRIPTION
**Pull request by wetneb**
Fixes #4724.

This adds explicit error messages indicating which parts of the schema are incomplete.
For now they can only be partially localized, but once backend localization is introduced in the Wikidata extension, the error messages that are generated there could also be localized too.

## Screenshot

image

### CODE REVIEW

**Review by elebitzero — APPROVED** [review]
1. If I add statement, and leave the property empty and click 'Save Schema', I see an exception. (Screenshot#1):
image

2.  If I add a term, and leave it empty and then click 'Save Schema', it appears to do it (Screenshot#2), but the previous behavior would not save and displays an error message "Your schema is incomplete so it cannot be saved yet" (Screenshot#3):
image

image

**Comment by wetneb** [comment]
Thanks a lot, this was very sloppy on my side!

In terms of user experience, I am not completely satisfied with the current situation. The validation errors are displayed in the Issues and Preview tab, but will users look for them there? Should we change the message in the alert to indicate that users can go to the issues tab to see the validation errors? Alternatively, we could remove this alert and simply switch users to the Issues tab whenever they try to save an incomplete schema, perhaps?

**Comment by wetneb** [comment]
Since this is getting stale, let's just merge it and deal with any improvements in follow-up PRs.

**Comment by lozanaross** [comment]
> In terms of user experience, I am not completely satisfied with the current situation. The validation errors are displayed in the Issues and Preview tab, but will users look for them there? Should we change the message in the alert to indicate that users can go to the issues tab to see the validation errors? Alternatively, we could remove this alert and simply switch users to the Issues tab whenever they try to save an incomplete schema, perhaps?

I think a better alert message would be preferable to just unexpetedly switching users to another tab. Something like: "You schema is incomplete so cannot be saved yet. Go to the Issues tab to review validation errors."

**Pull request merged**
