### PR TITLE
Extend cross() function to support multiple-value-cell-input

### LINKED ISSUE #1289: Extend cross() function to support multiple-value-cell-input
From a user perspective, I would like to call the cross function with a separator as 4th argument, so that multiple values (separated by a custom separator, e.g. ␟) in an input cell get "crossed".

### project "Christmas Gifts"

| gift | recipient |
| ------------- | ------------- |
| lamp  | mary  |
| clock  | john  |
| sweets  | mary,john  |
| wine  | anne,mary  |

### project "My Address Book"

| friend | address |
| ------------- | ------------- |
| john  | 120 Main St.  |
| mary  | 50 Broadway Ave.  |
| anne  | 17 Morning Crescent |

### Transformation

add values from column "address" from project "My Address Book" based on keys (with multiple values separated by ",") in column "recipient" from project "Christmas Gifts"

`forEach(value.cross("My Address Book", "friend", ","),r,r.cells["address"].value).join(",")`

### Output

| gift | recipient | address |
| ------------- | ------------- | ------------- |
| lamp  | mary  | 50 Broadway Ave. |
| clock  | john  | 120 Main St. |
| sweets  | mary,john  | 50 Broadway Ave.,120 Main St.
| wine  | anne,mary  | 17 Morning Crescent, 50 Broadway Ave.

## History

see last few comments in #1204

### PR DESCRIPTION
**Pull request by claussni**
Resolves #1289

### CODE REVIEW

**Comment by thadguidry** [comment]
@claussni fix the [testng] FAILED: crossFunctionCaseSensitiveTest

**Comment by claussni** [comment]
@thadguidry fixed it

**Comment by wetneb** [comment]
hey @thadguidry I think it'd be safer if you let another coder review code contributions. Having a green Travis is not enough in general, especially for PRs like this one which change some non-trivial things. I think this has been pointed out in the past so let's try stick to that rule.

**Comment by thadguidry** [comment]
@wetneb Reverted for you.  Can you comment on any changed lines (using Github line commenting) where you have concerns so that everyone can share and hear your thoughts ?  We can certainly make our review policy more strict and adhere to a +2 +2 policy (2 reviewers saying good to merge) as well.

**Comment by claussni** [comment]
This PR is in a limbo state now. I already deleted my branch and fork. Will see if I can reconnect a new branch...

**Comment by wetneb** [comment]
@thadguidry thanks! I did not have strong feelings about this particular PR, it was just a matter of principle. I have re-created it in  #1292.

**Pull request merged**
