### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Shamanou**
Hi i am with DTL and i am working on a openrefine distribution called the Fairifier. 

Its basically openrefine with the rdf extension build and and some additional tools to make data FAIR.
For more information on FAIR look at:
https://www.dtls.nl/fair-data

The additional functionalities are:
- posting rdf to a tripple store (right no virtuoso but more could be implemented)
- upload metadata to a fair datapoint (the  nodes of the fair architecture)
- upload data to a FTP (for an easy demo)
- for these purposes we implented front and back-ends with functionality

### CODE REVIEW

**Comment by thadguidry** [comment]
Hi @Shamanou !  Thanks for working on an extension to OpenRefine !
We wouldn't want to merge this into our project directly of course.  Although we appreciate the request.
Its more likely that folks would download OpenRefine and then could install your extension. Or could just download your Fairifier from your Github repo or website and install and run it.

Anything else we can help you with ?

**Comment by Shamanou** [comment]
Hi thanks for the quick response

i will let you know when i need any help

**Comment by thadguidry** [comment]
BTW @Shamanou , once you provide a distribution, we would be happy to also list it here http://openrefine.org/download.html with the other distributions.

**Comment by jackyq2015** [comment]
I know it is not small effort. But if you can split your project into several coherent PRs that will make it feasibility to merge into the master.

**Pull request closed without merging**
