### PR TITLE
WIP: Add unicode support to Jython

### PR DESCRIPTION
**Pull request by Monstrofil**
Fixes #{issue number here}

Changes proposed in this pull request:
- 
- 
-

### CODE REVIEW

**Comment by wetneb** [comment]
Thanks for this pull request!
Looking at your code changes I am a bit puzzled as to what you are trying to achieve.

Is there an issue that describes the problem you are tackling here? If so, you could edit the description of your pull request and insert "Fixes #1234", where #1234 is the corresponding issue number.

**Comment by Monstrofil** [comment]
Hi,

I'm still testing this change, but overall it makes possible to use unicode
symbols in jython scripts.

Before the change, any attempt to compare cell value to something like
"значение" failed because this piece of code replaced all non-ascii symbols
with "?" chars.

I'll update the pull request soon.

пн, 2 січ. 2023 р., 22:31 користувач Antonin Delpeuch <
***@***.***> пише:

**Comment by wetneb** [comment]
Thanks a lot! It would be great if you could add a unit test demonstrating the change too.

**Comment by wetneb** [comment]
Hi @Monstrofil! Thanks for adding this test, it helps a lot. As you can see in the "checks" section of this pull request, this fails to build. Could you check that your changes compile and the tests pass on your side?

**Comment by Monstrofil** [comment]
I'm closing this PR until I find a way to fix tests. Sorry to disturb.

**Pull request closed without merging**
