### PR TITLE
Minimal preference management for the Preferences page

### PR DESCRIPTION
**Pull request by antoine2711**
Related to #4745

Changes proposed in this pull request:
- Add getPreferences and setPreferences
- var thePreferences
- Duplicata code from Project.js

### CODE REVIEW

**Comment by antoine2711** [comment]
@Babi-B: If you want to play with the code, the JavaScript console is really a great place to test things. It could help you for #4745.

Here, I added getPrefs and setPrefs to the Preferences Page, so you can test it there.
image

Feel free to merge this PR into your code. It's not perfect, but it's a fair shot and it will help you. I promise to fix anything related to this code if the need arise! ;-)

Regards,
   Antoine

**Comment by Babi-B** [comment]
Ok thank you @antoine2711

**Comment by antoine2711** [comment]
> Should we close this PR now that it has been integrated in #4745?

I didn't wanted to complicate @Babi-B’s code, so I did YET integrated in this PR the changes the usage of setPreferences and getPreferences IN the code (actual use) as that « could » (read a theoratical potential) of causing problems. But, I have that code written. 

@wetneb: should we:
1. close this PR and open another for the actual usage in the code? (keep a certain logic and linking of code) 
2. keep this PR open, and continue to modify it to use the function in the code? (separate the 2 task as the reality has already done.)

Regards, Antoine

**Comment by wetneb** [comment]
If your intention is to propose changes to another PR, like #4745, then you could simply open a pull request which has the PR's branch as target (in this case, `Babi-B:I-4539-sidebar-dismissible`). This has two benefits:
* the author of the original PR can integrate your proposals directly, by accepting the PR
* your PR appears in their fork, not in this repository

So I would indeed propose we close this PR.

**Pull request closed without merging**
