### PR TITLE
POI 5.0.0 release

### PR DESCRIPTION
**Pull request by pjfanning**
useful for https://github.com/OpenRefine/OpenRefine/issues/2601

Release notes - https://www.apache.org/dyn/closer.lua/poi/release/RELEASE-NOTES.txt
Change log - https://poi.apache.org/changes.html#5.0.0

### CODE REVIEW

**Comment by tfmorris** [comment]
Thanks for the contribution. It would be useful to include a link to the release notes as well as a description of how much testing you've done.

Given that this is a major version upgrade for POI, we probably want to be relatively conservative in doing the upgrade and not rush to do it immediately before a little cooling off period to see how stable the release ends up being.

**Comment by wetneb** [comment]
@pjfanning thank you so much for proactively proposing the update! And for your work on POI in general. We just need to decide how this should fit in our release schedule but this should definitely make it to the users eventually.

**Comment by tfmorris** [comment]
Looks like there's already one fix targeted for a 5.0.1 in April. We probably want to continue to monitor this.
https://poi.apache.org/changes.html#5.0.1

**Comment by wetneb** [comment]
This fix looks important: https://github.com/apache/poi/pull/221
I don't know exactly which bug it fixes but by the looks of it it seems to be something we might rely on.
I propose we wait for 5.0.1. The update to that version should be proposed automatically by dependabot so we can close this PR. Or if @pjfanning wants to increment their commit count in OpenRefine, manual PRs are totally welcome too. Thank you again!

**Comment by pjfanning** [comment]
https://github.com/apache/poi/pull/221 affects Powerpoint tables

**Comment by pjfanning** [comment]
next POI release is likely to be v6.0.0

**Pull request closed without merging**
