### PR TITLE
Deal with localized numbers. Fixes OpenRefine#6351

### LINKED ISSUE #6351: Localized numbers not understood correctly in parsing options
The form inputs which expect numbers in the parsing panel (for instance for CSV/TSV) do not correctly understand numbers written with thousands separators such as "1,000" in English or "1 000" in French.

### To Reproduce
1. First, start a new project by uploading a CSV file with more than 1,000 rows
2. In the parsing options, input "1,000" in the "Load at most X lines" field

### Current Results

Observe that only one line is loaded in the preview, not one thousand.

### Expected Behavior

Numbers input with decimal separators should be understood properly, in all fields where a number is input.

### Versions
 - Operating System: Debian
 - Browser Version: Firefox 115.7.0esr
 - JRE or JDK Version: 17
 - OpenRefine: master branch (3.8-snapshot)

### Additional context

Discovered in a testing session with @cooperzoe.

Those input fields are currently marked as `type="text"`, but `type="number"` would feel more appropriate and likely solve this issue.

### PR DESCRIPTION
**Pull request by Xiayucheng1212**
Fixes #6351 

Changes proposed in this pull request:
This change helps all input fields under the parsing options to accept any kind of number input format, such as "1,000" or "1 000".
- Adapt the "parseIntDefault" function to different localized numbers.
  1. Remove the numbers after the decimal point
  2. Extract all the numbers remained
  3. Join them together

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
That looks a little custom: although it probably works for all the number formatting conventions I am aware of, it can well be that in some languages it breaks, no?

What do you think of my suggestion to letting the browser handle that for us by setting those input fields to `type="number"` instead of `type="text"`?

**Comment by Xiayucheng1212** [comment]
@wetneb  Yes, I think that will prevent potential problems. Thank you, I will try!

**Comment by wetneb** [comment]
@Xiayucheng1212 are you still working on this? See also the relevant discussion in #6352: moving to `type="number"` could mean that the field is not empty by default, but contains 0 instead (I haven't tried). Obviously we need to preserve the default behaviour of not limiting the import at all, ideally with a blank field.

**Comment by Xiayucheng1212** [comment]
@wetneb, Yes, I have tried the type="text", and it worked well. The defult value problem is also properly handled. I think it should be good to move on. Thank you!

**Review by wetneb — CHANGES_REQUESTED** [review]
Thanks a lot! Interestingly, the results are different in Chrome and Firefox.

In Chrome it looks like this, which is probably fine although the number inputs could be shorter:
image

In Firefox it looks like this:
image
As you can see, it's not very convenient to use such narrow input fields to input numbers with more than one digit. I would propose to bump `size="2"` to `size="7"` on those input fields, which would give something like this:
image

**Comment by wetneb** [comment]
@Xiayucheng1212 are you still working on this? I think this almost mergeable, we just need to adapt the width of the input fields for Firefox.

**Comment by Xiayucheng1212** [comment]
> @Xiayucheng1212 are you still working on this? I think this almost mergeable, we just need to adapt the width of the input fields for Firefox.

Yes! Thank you for your notice, I edited the input size to 7. It's ready to go now.

**Review by wetneb — APPROVED** [review]
Thanks a lot!

**Review by wetneb — CHANGES_REQUESTED** [review]
Sorry I just realized that there are a lot more such panels that we should probably fix in the same go, such as `excel-parser-ui.html`, `fixed-width-parser-ui.html` and so on.
Would you be willing to do that too?
Apologies again for realizing that so late.

Also, the `spellcheck="false"` attribute can probably be removed on those fields, as I don't think browsers will try enabling spellchecking on number inputs.

**Comment by Xiayucheng1212** [comment]
Sure, no problem! I will check it later!

**Review by wetneb — APPROVED** [review]
Thanks a lot!

**Pull request merged**
