### PR TITLE
Update the README.md for database extension

### LINKED ISSUE #3915: README.md for database extension is out of date
We need to update the database extension README.md to our more current architecture and documentation moves.

### PR DESCRIPTION
**Pull request by thadguidry**
Fixes #3915

Changes proposed in this pull request:
- Updated README.md for database extension with current Maven architecture and documentation links.

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
Thanks, it was indeed very outdated! Actually I think we can simplify those instructions even more since the extension is already maintained in the same repository, you don't need to pull both code bases separately or to edit any build file. So perhaps this file could just contain some description of the extension and instructions to add support for a new DB vendor? I don't think it is the right place to document how to install third-party extensions (since it is not one).

**Comment by thadguidry** [comment]
@wetneb sure, simplify away to your hearts content.  or someone else can come back to this PR and improve it.

This is what I got from @tcbuzor back in the day...
1. You'll want to register an additional Database Service:  https://github.com/OpenRefine/OpenRefine/blob/master/extensions/database/src/com/google/refine/extension/database/DatabaseService.java
2. Provide the connection and service classes, look at the PostgreSQL one or MySQL one as examples: https://github.com/OpenRefine/OpenRefine/tree/master/extensions/database/src/com/google/refine/extension/database
3. Then wire up the interface with defaults as desired: https://github.com/OpenRefine/OpenRefine/blob/master/extensions/database/module/scripts/index/database-source-ui.js#L93
4. Add drivers manually to the classpath, or update the pom file to provide them as dependencies as other DB libraries are done: https://github.com/OpenRefine/OpenRefine/blob/master/extensions/database/pom.xml

**Comment by wetneb** [comment]
Thanks, I just pasted that then!

**Review by thadguidry — COMMENTED** [review]
Great, looks good!

**Pull request merged**
