### PR TITLE
Initial support for schema templates.

### LINKED ISSUE #5043: Ability to save "schema templates": schemas where some values are left empty
Wikibase communities generally establish some data modelling conventions, which users are asked to follow when importing data.
For instance, a book on Wikidata will generally have a certain set of statements on it (title, author, date of publication…).

When importing data in a Wikibase instance, users need to have the knowledge of those modelling conventions. If they do not have this knowledge, a blank schema page can be quite daunting.

### Proposed solution
We should make it possible for users to define "schema templates" which represent a prototypical Wikibase schema for an import in a certain domain. Those schema templates would be incomplete Wikibase schemas, in the sense that some statement values could be left blank, for instance. After loading such a template, the user could then drag and drop the columns from their project to the appropriate locations in the schema.

For the implementation, we would just use the same classes as the ones that define schemas, but relax the validation in the constructors to allow for empty value. We would then add methods to check that a given schema is complete. This would be the opportunity to return more precise error messages when the schema is incomplete (#4724).

### Alternatives considered
Use [ShEx](https://en.wikipedia.org/wiki/ShEx) or [SHACL](https://en.wikipedia.org/wiki/SHACL). Those formats are not designed for the Wikibase data model, but rather for RDF. This means that it would not be possible to take a schema represented in one of those formats, and render it as a Wikibase schema with holes. Therefore this does not seem fitting here.

### Additional context
Requested by @trnstlntk @lozanaross in the context of the Wikimedia Commons integration project.

### PR DESCRIPTION
**Pull request by wetneb**
Closes #5043.

This adds the ability to start a schema from a previously saved schema template.
A schema template is a schema with some missing values.
It is also possible to pre-define some templates in the Wikibase manifest, so that those are added to OpenRefine when the manifest is first loaded.

I think it would be useful to add an interface to list existing schema templates, which would enable:
* deleting schema templates
* exporting a schema template to JSON (useful to add it to the manifest afterwards)

### CODE REVIEW

**Comment by trnstlntk** [comment]
I have just tested this, and I indeed am able to create and save new schema templates and then switch between them.
I can save them with or without prefilled values. I think that's good. See the difference between information/artwork and the Art photo example in the short screen recording I made:

https://user-images.githubusercontent.com/9881645/185386296-0e24659b-9951-45f7-9643-be706531eebb.mov

I noticed that I can't save schemas (not schema templates, but schemas) with empty values, is that indeed the behavior we want to maintain? I have no opinion (or memory of any decision) either way.

Also, if I recall correctly, @lozanaross suggested some changes in placement of certain buttons; that may be something to look at in a separate issue I can imagine.

**Comment by wetneb** [comment]
> I noticed that I can't save schemas (not schema templates, but schemas) with empty values, is that indeed the behavior we want to maintain? I have no opinion (or memory of any decision) either way.

Yes, a schema is meant to be something that is able to translate rows to edits: if there is a missing value in a schema, then we cannot use it to generate edits. This is consistent with the previous behaviour (not being able to use a schema if it is incomplete).

Of course this is different from the "novalue" / "somevalue" support (#1713), where the user would explicitly specify that they want to use those "special values" (rather than the schema being incomplete.

> Also, if I recall correctly, @lozanaross suggested some changes in placement of certain buttons; that may be something to look at in a separate issue I can imagine.

Yes, I am waiting for those issues and I think @lozanaross is aware.

**Comment by lozanaross** [comment]
What issues are missing? I thought I made everything that was agreed to be feasible within this round of funding as issues a while back in July / August.

**Comment by wetneb** [comment]
Correct, there is https://github.com/OpenRefine/OpenRefine/issues/4819 already actually!

**Pull request merged**
