### PR TITLE
Make cross() function work for all columns

### LINKED ISSUE #1950: Cross() function not working if applied to a column different from the column used for matching
**Describe the bug**
Cross() function not working if applied to a column different from the column used for matching.
Not sure it is fully reproducible, but happended to me twice, with big OR projects (a lot of transformations, including moving columns, before applying the cross function)

I cannot join the files because they weigh 200 Mo...

**To Reproduce**

**Current Results**

The normal behavior (matching 2 project, based on "IDAloes", the 1st column of each project, and applying the formula to the 1st column)
image

The error (matching the same projects on the same column, but applying the formula to the 2d column)
image

No warning in console

**Expected behavior**
A clear and concise description of what you expected to happen or to show.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac and PC, same behavior
 - Browser Version: FF
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version : OpenRefine 3.1

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

### PR DESCRIPTION
**Pull request by afkbrb**
Fix #1950 

Now the cross() function works for all columns.

### CODE REVIEW

**Comment by afkbrb** [comment]
Yeah, you're right. 

I just studied the join mechanism used currently. Another problem is that whether we update the source project or the target project, the join cache will be removed.  If we use the new mechanism you mentioned, we'll only deal with the target project, so the join cache is likely to be removed, and accordingly it may be more efficient actually. 

I'd be glad to make the change if you agree.

**Comment by wetneb** [comment]
That would be fantastic!

It would be worth making sure `cross` can still take Cells as first argument, to maintain backwards compatibility.

**Comment by thadguidry** [comment]
> That being said, I still don't see why the cross function should necessarily take a Cell as first argument. Why can't we just have a function taking:
> 
>     * a value
> 
>     * a project name
> 
>     * a column where to look for the value in the project
> 

Questions:
1. "a project name" is ANY project (current or another)?
2. a column where to look for the value in ANY project (current or another)?

**Comment by wetneb** [comment]
I guess it's a violation of the row-wise computation of expression values if you use `cross` on the same project, so we could potentially want to forbid that (I haven't checked if it is currently allowed).
But there are other GREL functions which introduce dependencies outside the row/record context (such as `facetCount`) so I am not sure it's worth forbidding.

**Comment by thadguidry** [comment]
I don't think we want to forbid it allowing where to lookup.  I have always wanted it to work more a bit more similarly to VLOOKUP() in Excel and LibreOffice.  David said at the time there was some modeling limit or GREL snafu that limited our ability when he first hacked on it. Can't recall but I remember him mentioning it to me.  Dunno, would have to ask him.

I think its also important that we document the differences in handling just for posterity:

VLOOKUP() | cross()
------------|-----------
value to lookup | value to lookup
lookup range is same workbook or another, containing full table or partial table range Ex. `VLOOKUP(D8,'<filepath>'#$<sheetname>.$B$1:$I$65255,8,0` | lookup range is full table in another project
column index | column name
exact or similar match | exact match (hard coded)

Cosmetically, do we agree the above is our current functioning of our `cross()` ?

**Comment by antoine2711** [comment]
> * "a project name" is ANY project (current or another)?
> * a column where to look for the value in ANY project (current or another)?

Yes, I think it important this it keeps this functionality, it now works that way (you can self-join your project).
And of course, the column parameter can be any column, as long as it's in the project referred by the « project's name » ;-)

Regards, Antoine

**Comment by antoine2711** [comment]
> Another problem is that whether we update the source project or the target project, the join cache will be removed. If we use the new mechanism you mentioned, we'll only deal with the target project, so the join cache is less likely to be removed, and accordingly it may be more efficient actually.

If we use the cross() function on the same project, then, from your explanation, I understand that you will have to build the local « join cache » on the spot? But you could do that if it's a self-join, and not if it's an external project, so the time price is not always paid?

Regards, A.

**Comment by antoine2711** [comment]
> if you use `cross` on the same project, so we could potentially want to forbid that (I haven't checked if it is currently allowed).

Yes, @wetneb, you can do that right now. See this self-join:
image

**Comment by afkbrb** [comment]
> If we use the cross() function on the same project, then, from your explanation, I understand that you will have to build the local « join cache » on the spot? But you could do that if it's a self-join, and not if it's an external project, so the time price is not always paid?

@antoine2711 , sorry I didn't make it clear. I am talking about the current join mechanism, not the one I am about to implement (which is not join-based). The `join cache` can be used between any two projects, including the same project. 

If it's a self-join, the efficiency of the two mechanism won't differ too much, because only one project is involved in this situation.  So, yes, the time price is not always paid.

But I assume that the cross() function is usually used between two different projects (the source project and the target project). In that case, if we change the source project, we'll need to remove the cache in the current implementation and **won't** need to do it in the new implementation. So in the new implementation, the cache will be more likely to stay valid and less likely to be computed again. That's why I think the new implementation will be more efficient.

**Comment by afkbrb** [comment]
Done!

**Comment by afkbrb** [comment]
@wetneb Thanks for the approval! 

I just reformated  the code, since most files in the project are using 4 spaces instead of a tab.

**Comment by antoine2711** [comment]
Nice work! Well done @afkbrb.

Little question for you: is your new cross() function will work on other types of data than strings? If my key column is composed of numbers, will your function work? Because right now, if it's not text, it won't work…

Regards, Antoine

**Comment by afkbrb** [comment]
@antoine2711 The behavior is almost the same as before, it's an implementation change, not an API change. It's possible to support number, but the previous implementation explicitly requires the first argument to be String or Cell, not sure why we don't support number in that implementation. Maybe we should ask @wetneb .

**Comment by wetneb** [comment]
I think it'd be nice to support numbers too (especially since the underlying index uses `Object` to store values already), but I agree it's a different change, so we can do it in another PR.

**Comment by thadguidry** [comment]
Please support numbers also.  Many scientific datasets have a KEY field that is composed of Long numbers.  Great job thus far @afkbrb !

**Comment by afkbrb** [comment]
Great! Now this PR is merged and I can work on supporting number then.

**Comment by antoine2711** [comment]
@afkbrb: good job. I'll go test that right now.

Regards, Antoine

**Comment by antoine2711** [comment]
@afkbrb: do you thing you could improve the cross function by making the second parameter optional (i.e. if empty…)? 

That way, it would represent the current project, and it would make the code more readable. One other added benefit would be that the same transformation could would on similarly based project without change, and would still work in a same project that would have changed name.

Regards, Antoine

Regards, Antoine

**Comment by afkbrb** [comment]
@antoine2711 Good idea! It's not difficult to do it and it's helpful for reusing. I think you could open a new issue for it since this PR has alreay been closed.

**Comment by antoine2711** [comment]
> @antoine2711 Good idea! It's not difficult to do it and it's helpful for reusing. I think you could open a new issue for it since this PR has already been closed.

I'll get to work for the PR…

**Comment by felixlohmeier** [comment]
@afkbrb and all, I just want to say a big thank you for this new feature! cross supporting values (instead of only cells) is what I dreamed of since 2017: #1204, #1289, #2234 . 

I have only recently found a [solution for my use case with Jython](https://gist.github.com/felixlohmeier/a5a893190e4aa8e26091664908d04e20). But it was quite a hack. It's great that with OpenRefine 3.4 it now works in GREL natively.

**Comment by felixlohmeier** [comment]
@wetneb you wrote on https://github.com/OpenRefine/OpenRefine/wiki/Changes-for-3.4:
> The cross function is no longer restricted to source values from the column where it is invoked

I didn't realize it at first. Should we highlight the new options, e.g. "The cross function now supports any value for input (instead of just cells) and is no longer restricted to the column where it is invoked"?

**Comment by wetneb** [comment]
@felixlohmeier Yes feel free to tweak the changelog!

**Comment by antoine2711** [comment]
> @wetneb you wrote on https://github.com/OpenRefine/OpenRefine/wiki/Changes-for-3.4:
> 
> > The cross function is no longer restricted to source values from the column where it is invoked
> 
> I didn't realize it at first. Should we highlight the new options.

Yes, the overhaul of the cross function is major, in v3.4.

But in v3.5 (Issue « Enhance cross() with empty "project name" calling parameter to represent the current project and empty column name to represent the index #2504 »), you can even do:
`cross(index+1)[0].cells.ColName.value` to get the value of the next row of the cell « ColName ».

It's because, this call is like `cross(index+1, "ProjectName", "")[0].cells.ColName.value`where an empty column name actually means « using the internal index ».

If you think about it, it's pretty cool. The index can now be a column for the `cross()` function.

How do you like that? ;-)

Regards,
   Antoine

**Pull request merged**
