### PR TITLE
Issue 3420 more facets filters

### PR DESCRIPTION
**Pull request by fgiroud**
Scatterplot testing
Introduces Cypress Image Snapshot to perform assertions against reference images.
Doc has been enriched with a section describing this new approach

### CODE REVIEW

**Review by kushthedude — COMMENTED** [review]
@fgiroud I am getting this error on my local
```sh


  1) cypress/integration/project/grid/column/facet/scatterplot-facet.spec.js
       Test image rendering inside the facet (visual testing):
     TypeError: The following error originated from your application code, not from Cypress.
  > Cannot read property 'css' of undefined

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

      at adjust (http://127.0.0.1:3333/project-bundle.js:40616:36)

      at $.imgAreaSelect.setOptions (http://127.0.0.1:3333/project-bundle.js:41023:9)

      at ScatterplotFacet.reset (http://127.0.0.1:3333/project-bundle.js:41243:28)

      at HTMLDivElement.<anonymous> (http://127.0.0.1:3333/project-bundle.js:41388:12)

      at HTMLDivElement.dispatch (http://127.0.0.1:3333/project-bundle.js:5228:27)

      at HTMLDivElement.elemData.handle (http://127.0.0.1:3333/project-bundle.js:4880:28)
```

**Comment by fgiroud** [comment]
woo, that's great, I was unable to reproduce it locally, which OS/browser are you using @kushthedude  ?

**Comment by kushthedude** [comment]
> woo, that's great, I was unable to reproduce it locally, which OS/browser are you using @kushthedude ?

Its sort of flake, with MacOS and Edge.

**Comment by fgiroud** [comment]
Do you mind to try again @kushthedude ?, I removed the flaky tests

**Review by kushthedude — APPROVED** [review]
works fine for me!

**Pull request merged**
