### PR TITLE
chore: align test-suite name with npm standards

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

### CODE REVIEW

**Comment by kushthedude** [comment]
@wetneb I have also renamed ~Java CI~ OpenRefine, since we have cypress tests as well as server tests and build checks in the CI.

**Comment by wetneb** [comment]
"OpenRefine" seems a bit generic, no?

**Comment by kushthedude** [comment]
> "OpenRefine" seems a bit generic, no?

We can add a CI prefix to the name, and make the jobs name more specific like `server_build`, `server_tests` & `ui_tests`

**Comment by wetneb** [comment]
Yes, I'd say let's change "Java CI" to just "Continuous integration", and then change the "build" job into "server_tests". Using "ui_tests" instead of "cypress_tests" also makes sense, it's more transparent.

**Review by wetneb — APPROVED** [review]

**Pull request merged**
