### PR TITLE
Issue 6304 unfolding triangle bug

### LINKED ISSUE #6304: Unfolding triangle in Wikibase edit preview
As I looked through the Preview in my Wikibase edit, I expected to be able to click on the little triangle next where it says **1 references** in the below screenshot and unfold my references right below. Instead I needed to click on the **1 references** text itself. 

Let's make the little triangle itself clickable too.

### PR DESCRIPTION
**Pull request by amparab**
Fixes #6304

Changes proposed in this pull request:

In this pull request, I have fixed the bug in which the referenceContainer was not unfolding on clicking of the triangle icon.

PFA Evidence.

https://github.com/OpenRefine/OpenRefine/assets/37299522/841f28db-7f15-4ea2-b07e-5d390574def2

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
Thanks a lot! This seems to be changing the DOM structure, because `referenceToggle` is becoming part of the `triangle` element. Wouldn't it be simpler to just add the `on('click', …)` event listener to `referencesToggleContainer` instead, keeping the rest of the structure?

**Comment by amparab** [comment]
> Thanks a lot! This seems to be changing the DOM structure, because `referenceToggle` is becoming part of the `triangle` element. Wouldn't it be simpler to just add the `on('click', …)` event listener to `referencesToggleContainer` instead, keeping the rest of the structure?

Makes sense @wetneb Thankyou! I have made the change.

**Comment by cooperzoe** [comment]
Thank you @amparab for tackling this!

**Review by wetneb — APPROVED** [review]

**Comment by magdmartin** [comment]
@amparab thank you for your two contributions in the last few weeks :tada:  

We have an [introduction thread](https://forum.openrefine.org/t/introductions-thread/69) on our forum where members can introduce themselves and share their interest in OpenRefine. You can also write a few lines about yourself if you'd like to and get to know the other contributors.

**Comment by amparab** [comment]
Thankyou @magdmartin !!
A bit late to the party but I have introduced myself on the thread! :)

**Pull request merged**
