### PR TITLE
Browser redirect to http://localhost not http://0.0.0.0 #2336

### PR DESCRIPTION
**Pull request by darecoder1999**
resolves issues #2336

### CODE REVIEW

**Comment by ostephens** [comment]
@darecoder1999 thanks very much for this. @kushthedude had already done a PR for this so it's probably worth just checking if anyone is already working on the issue before doing a PR

**Comment by darecoder1999** [comment]
Sorry, I will keep that in mind. :smile:

**Comment by kushthedude** [comment]
This PR should be closed then.

**Comment by wetneb** [comment]
It might be worth asking to be assigned to an issue before working on it, to avoid duplication of efforts. I don't recall running into this issue before - it's great to see the activity pick up!

@kushthedude if you could update your pull request to address the review comments there, we can merge it and close this one. Otherwise this one will work too. (but no need to react negatively to this PR - I am sure @darecoder1999 did not want to scoop you)

**Comment by kushthedude** [comment]
Updating the PR.

**Comment by wetneb** [comment]
Closing this then. Thanks @darecoder1999 though!

**Pull request closed without merging**
