### PR TITLE
Update deprecated method for Mockito initMocks()

### PR DESCRIPTION
**Pull request by thadguidry**
Changes proposed in this pull request:

- Deprecated.  Use openMocks(Object) instead.
- Updates it for database extension testing.
- https://javadoc.io/doc/org.mockito/mockito-core/5.3.1/org/mockito/MockitoAnnotations.html

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
According to [the documentation you linked](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/MockitoAnnotations.html#initMocks(java.lang.Object)), the point of doing this migration to `openMocks` is to keep track of the `AutoCloseable` it returns and close it appropriately (when tests have run), so it'd be good to do that in the same go - unless it's not needed given our usage?

**Comment by thadguidry** [comment]
Either my VSCode IDE is not setup right...or there's something I'm not familiar with regarding TestNG.
I've pushed 1 small change to demonstrate the annotation config... but something else is going on when I test that one class...

```
{"name":"testStarted","attributes":{"name":"com.google.refine.extension.database.cmd.ConnectCommandTest#testCsrfProtection()"}}{"name":"testFinished","attributes":{"name":"com.google.refine.extension.database.cmd.ConnectCommandTest#testCsrfProtection()","duration":"402"}}{"name":"testStarted","attributes":{"name":"com.google.refine.extension.database.cmd.ConnectCommandTest#testDoPost()"}}{"name":"testFailed","attributes":{"name":"com.google.refine.extension.database.cmd.ConnectCommandTest#testDoPost()","message":"No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]","trace":"com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
```

Help further?

**Comment by wetneb** [comment]
Well, the CI is red so it looks like the test fails also there, which seems to indicate that the test failure is not specific to your IDE. More work is likely needed to adapt the test to use `openMocks` correctly :) Should we mark the PR as draft in the meantime?

**Comment by thadguidry** [comment]
Oh, it's totally DRAFT... yes please.

**Comment by wetneb** [comment]
@thadguidry are you still working on this?

**Comment by thadguidry** [comment]
I think I'll give up

**Pull request closed without merging**
