### PR TITLE
make dialogs focusable

### PR DESCRIPTION
**Pull request by Abbe98**
Makes dialogs focus-able, makes it possible
to use dialog headers as modal labels, and
automatically set focus when a dialog is displayed.

### CODE REVIEW

**Comment by Abbe98** [comment]
Failing tests^^, looks like there is a dialog without a header.

**Comment by elebitzero** [comment]
@Abbe98, I checked and there are two tests failing.
I'm not sure why the tests are failing in the following two files:
  * undo_redo.cy.js
  * importing-data-into-openrefine.cy.js
 

I see your branch doesn't have the latest Cypress update that was just merged https://github.com/OpenRefine/OpenRefine/pull/5503  but that shouldn't matter.

I just created a new PR for Cypress 12.4.0 and all of the tests are passing.

You could just trigger a new build to see if the failures are repeatable, or pull the latest master which has the updated Cypress.

You could also try running the Cypress tests locally and see if you still get the errors.

**Comment by Abbe98** [comment]
>  I'm not sure why the tests are failing in the following two files:

@elebitzero yeah I think there is a dialog somewhere without a header, will have a look next time I'm on it to see if the code changes should be hardened or if another change is motivated.

**Comment by Abbe98** [comment]
I ended up hardening the changes after considering that enforcement of headers might be a breaking change for some extensions.

**Review by elebitzero — APPROVED** [review]

**Pull request merged**
