### PR TITLE
Added Links

### PR DESCRIPTION
**Pull request by risav-sarkar**
Added links of Jdk and Apache Maven for ease of use

### CODE REVIEW

**Comment by thadguidry** [comment]
@risav-sarkar I'm not sure we can truly say that to **Run from source** as a developer you need JDK 8 any longer.  It builds and runs fine with JDK 15 (backward compatibility) from [https://jdk.java.net/](https://jdk.java.net/) where that generic JDK download link is probably a better link to use.  I'm not sure we even want to keep that section in our Readme, since we'll be changing many things about our developer docs and improving them.  For instance, we already have lots of detail and that needs updating on this Wiki page: https://github.com/OpenRefine/OpenRefine/wiki/Building-OpenRefine-From-Source

**Comment by risav-sarkar** [comment]
I had given the link of the latest JDK(https://www.oracle.com/in/java/technologies/javase-downloads.html). Should I change it to (https://jdk.java.net/) ?

**Comment by wetneb** [comment]
I think it's a good idea to add links here! For the JDK, I would point people to https://adoptopenjdk.net/ instead, no?

**Comment by thadguidry** [comment]
@wetneb It's changing however what we already have on the User manual.  OpenJDK page points to the same link https://jdk.java.net from https://openjdk.java.net/

**Review by wetneb — APPROVED** [review]

**Pull request merged**
