### PR TITLE
Adds the Search for match option

### LINKED ISSUE #6110: Cells with reconciliation errors should let the user match them manually
### To Reproduce
1. Reconcile a column via a recon service which returns errors (for instance, disable your internet connection during reconciliation)

### Current Results

The cells which store errors do not have a "Search for match" link like the ones which were successfully reconciled

### Expected Behavior
The "Search for match" link should be present and work as expected.

### Screenshots

Screen Shot 2023-08-25 at 7 42 48 AM

### Versions
 - OpenRefine: 3.8-SNAPSHOT

### Additional context

Follow-up to #6006

### PR DESCRIPTION
**Pull request by ayushrai206**
Fixes #6110

Changes proposed in this pull request:
- Now the cells with errors can be matched manually with "Search For Match" button

### CODE REVIEW

**Comment by elebitzero** [comment]
I submitted a PR #6194 that fixes the test that is failing (Copy reconciliation data Copy reconciliation data from species to species_copy).

**Comment by wetneb** [comment]
@ayushrai206 you should be able to rebase your branch on top of master and this will likely fix the failing test

**Comment by wetneb** [comment]
@ayushrai206 could you rebase your branch on top of master? It should only take you a few minutes.

**Comment by ayushrai206** [comment]
> @ayushrai206 could you rebase your branch on top of master? It should only take you a few minutes.

Yes, doing it asap, sorry for the delay!

**Review by wetneb — APPROVED** [review]

**Pull request merged**
