### PR TITLE
Add test coverage and code analysis reports with Codacy

### PR DESCRIPTION
**Pull request by wetneb**
This adds Jacoco test coverage to the build file.

Developers can use the HTML reports are generated in `build/report/html` by `./refine server_test`. XML reports are submitted by Travis to Codacy and can be viewed [on their interface](https://www.codacy.com/app/OpenRefine/OpenRefine/dashboard).

I have changed the Travis script to run `./refine server_test` instead of `./refine test` because the browser tests are broken (they rely on Windmill, which is abandoned: see #733). This saves a few seconds of build time.

I have added a Codacy badge to the README.md : [Codacy Badge](https://www.codacy.com/app/OpenRefine/OpenRefine).
There is another badge that displays coverage ([Codacy Badge](https://www.codacy.com/app/OpenRefine/OpenRefine)) but we need to merge this into master before adding it.

I have also enabled Codacy integration on GitHub, so this PR will be reviewed by Codacy (and I hope it will be happy with it! I suspect it will not find any issue because I did not touch the Java code at all).

@thadguidry I have seen your Gradle file, but it seems easier to me to add Jacoco in the ant build - this way, it works both with your new Gradle setup and with the current build system.

### CODE REVIEW

**Comment by wetneb** [comment]
Hmm, Codacy did not find anything to say here. It did find issues for this one though: https://github.com/OpenRefine/OpenRefine/pull/1216
By the way, this closes #1224.

**Comment by wetneb** [comment]
Following the discussion on #1216 I merge this first.

**Comment by wetneb** [comment]
@thadguidry @jackyq2015 I need admin rights to add a GitHub hook for Codacy integration (so that the dashboard gets updated when we push things on master). I've sent you an invite link for Codacy if you want to do it yourself.

**Comment by thadguidry** [comment]
@wetneb I did install the webhook for Codacy manually.  Looks like their auto-install ON/OFF switch for it is a bit buggy even for an admin.  no one online in their chat at this hour to talk to about it.  Regardless, it looks like its setup for PUSH monitoring now.  I've given you admin access, and your now part of the CORE team.  We know where you sleep. :)  Welcome to CORE !

**Pull request merged**
