### PR TITLE
Technical documentation for clustering

### LINKED ISSUE #3033: Document clustering algorithms
The documentation on the clustering algorithms is scant, and in some cases, non-existent. The user interface should provide a brief description of each algorithm as well as guidance on how to pick the most appropriate one for their application as well as any pertinent tradeoffs.

Some are obvious from their names (or at least easily Google-able), but other are much more opaque.

PPM is a particularly egregious example, but since I just looked at the implementation, here's what it does:

PPM stands for [Prediction by Partial Matching](https://en.wikipedia.org/wiki/Prediction_by_partial_matching) which is an arithmetic coding technique. The implementation that OpenRefine uses is based on the MIT SIMILE project's Vicino package, which, in turn, uses Bob Carpenter's arithcode package, which has a tutorial available here: https://raw.githubusercontent.com/bob-carpenter/java-arithcode/master/arithcode-1.2/doc/tutorial.html. The two strings to be compared are concatenated together and then "compressed" using the coder. The PPMModel uses 8 bytes of context and returns as the score the length of the encoded output. This is used four times to compute distance scores for (x,y), (y,x), (x,x), (y,y) (because the scores are directional) which are then combined together in this fashion to generate a final score: 

`10.0d * ((d(x,y) + d(y,x)) / (d(x,x) + d(y,y)) - 1.0d)`

This score is relatively computationally expensive to compute and has to be done in a pairwise fashion for every pair of strings. To prevent an N^2 explosion, both the "nearest neighbor" clustering algorithms first divide the strings into manageable sized blocks and only does the pairwise comparison for members of the block. Depending on the blocking algorithm used, it's possible for two similar strings to end up in different blocks and never get compared to each other.

### PR DESCRIPTION
**Pull request by Babi-B**
Fixes #3033

Changes proposed in this pull request:
- describes metaphone3 algorithm for OpenRefine

### CODE REVIEW

**Comment by Babi-B** [comment]
Hello @antoine2711. Excuse me but I edited the [wiki](https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth#metaphone3) before realizing I had to do a pull request for your permission first. If you do not approve this changes I will take out what I had done.

**Comment by antoine2711** [comment]
> Hello @antoine2711. Excuse me but I edited the [wiki](https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth#metaphone3) before realizing I had to do a pull request (…).

Actually, you did right. We do not have a « request first » modus operandi, people just make changes there as they see fit.

We are slowly phasing out of the Wiki, so I would say: make sure that the information you add in the Wiki is also in the Docs, and that will pass thru our supervision mechanism, and reviewers will see you changes there, so if a correction to your work is requested in the PR for the Docs, you could also apply that correction to the Wiki.

Are my explanation clear? If not, please ask me to clarify.

Regards, Antoine

**Comment by Babi-B** [comment]
>Are my explanation clear? If not, please ask me to clarify.

@antoine2711 it is clear. Thank you

**Comment by wetneb** [comment]
@Babi-B it looks like your PR fails to build on Netlify: that might mean Docusaurus has found some errors in your changes. Can you have a look? You can click on the `Details` links in the checks for this PR to find out more.

**Comment by Babi-B** [comment]
Ok @wetneb. I'm on it

**Comment by Babi-B** [comment]
Hello @antoine2711, I have completed the documentation. Could you please review it?

**Review by wetneb — CHANGES_REQUESTED** [review]
As far as I can tell, the page is still not reachable from the rest of the documentation. Also, this PR adds an image which should probably be deleted.

**Comment by Babi-B** [comment]
@wetneb I don't know where I am making the error. I followed the instructions outlined in this [readme](https://github.com/OpenRefine/OpenRefine/tree/master/docs#readme) file and was able to run the docs locally (http://localhost:3000/next). 

I made some test changes to other files and they displayed however the file I added did not

**Comment by wetneb** [comment]
You could add a link to your file from other files, or add it to the sidebar (see `sidebar.json`).

**Comment by Babi-B** [comment]
@wetneb thank you. I added it successfully

**Review by wetneb — APPROVED** [review]
Thank you!

**Pull request merged**
