### PR TITLE
tests: UX Test for project list deletion, sort, filter

### LINKED ISSUE #3413: Add UX Test for the projects list
Improve the tests we have on the projects list page (project management)

Screen Shot 2020-12-16 at 13 08 48

#### Test the "About" panel

* Editing of metadata
* test the panel

#### Test the Delete behavior

Test project deletion and ensure it's been really deleted, not only removed from the list.

#### Test the sorting of tagging list
To be tested

* Sort by tags
* Filter by tags

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>

Fixes #3413

### CODE REVIEW

**Comment by kushthedude** [comment]
The failure here is due to #3479 since few projects from past tests still remained which caused the failure

**Comment by kushthedude** [comment]
Looks like I made a mistake while linking the PR 😅

**Comment by fgiroud** [comment]
@kushthedude , the test is technically valid.
However there might be a more simple way to compare indexes, see below
```javascript
cy.get('a.project-name').contains('projectA').then((projectALink) => {
    cy.get('a.project-name').contains('projectZ').then((projectZLink) => {
        cy.log('Index for project A is ' + projectALink.parent().parent().index() + ', Index for project Z is ' + projectZLink.parent().parent().index());
        // assertion can be placed here
    });
})
```

[This article contains useful resours about variables](https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Return-Values)
Basically they recommend to use their own wrapper `.as()`, but you found an interesting way to get the row index with `(rows.index(element))`, does it means it was a closure and you get the result immediately?


Also, do you think it's best to add a unique suffix (Date) to project names to ensure the test is running with fresh projects ? Just because we already have issues with the deletion method, and I wonder if it would fail the test if the project is not deleted properly

**Comment by kushthedude** [comment]
> @kushthedude , the test is technically valid.
> However there might be a more simple way to compare indexes, see below
> 
> ```js
> cy.get('a.project-name').contains('projectA').then((projectALink) => {
>     cy.get('a.project-name').contains('projectZ').then((projectZLink) => {
>         cy.log('Index for project A is ' + projectALink.parent().parent().index() + ', Index for project Z is ' + projectZLink.parent().parent().index());
>         // assertion can be placed here
>     });
> })
> ```
> 
> [This article contains useful resours about variables](https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Return-Values)
> Basically they recommend to use their own wrapper `.as()`, but you found an interesting way to get the row index with `(rows.index(element))`, does it means it was a closure and you get the result immediately?

Yes; rows.Index returns the returns immediately. We can use the above code too if it's required, anyway works with me.

>Also, do you think it's best to add a unique suffix (Date) to project names to ensure the test is running with fresh projects ? Just because we already have issues with the deletion method, and I wonder if it would fail the test if the project is not deleted properly

About the test names, I guess we can rather have names as `test${Date.Now()}` rather than `Date.Now()` as it may create hindrance in testing specs for projects. How this sounds to you?

**Comment by fgiroud** [comment]
> About the test names, I guess we can rather have names as `test${Date.Now()}` rather than `Date.Now()` as it may create hindrance in testing specs for projects. How this sounds to you?

Good idea !

**Comment by kushthedude** [comment]
@fgiroud Modified the code here to according to latest changes, please review and merge

**Review by fgiroud — APPROVED** [review]

**Pull request merged**
