### PR TITLE
parse the date time string with offset

### PR DESCRIPTION
**Pull request by jackyq2015**
To fix issue #1564

### CODE REVIEW

**Comment by jackyq2015** [comment]
Though both return OffsetDateTime, the ParsingUtilities.stringToDate always return the Zulu time, but the toDate will keep the offset as is.

**Comment by wetneb** [comment]
That does not solve the bug I reported. The behaviour of stringToDate was changed and this breaks the data extension operation, among others. Please make sure that stringToDate supports all the formats it supported before.

**Comment by wetneb** [comment]
Hi @jackyq2015, have you seen my report in #1564? Just reconcile a column (for instance containing the names of famous people) and fetch dates from that (for instance their date of birth, P569) and you will observe the error.

So, here is the situation. In commit 23ec54b78 you have changed the behaviour of `ParsingUtilities.stringToDate`. Many parts of the code rely on this function to parse dates. Therefore, this potentially introduces bugs in all these areas. I have shown you two instances of such bugs, but of course we should not fix just them: they are just the symptoms and we should fix the root cause. The root cause is that `ParsingUtilities.stringToDate` previously supported ISO dates with offsets, and now it fails on them. So, it would be great if you could fix that.

If it helps, here is a test case that should pass (it passes before 23ec54b78 and breaks after):
```
    @Test
    public void parseOffsetDate() {
        String offsetDate = "1958-08-29T00:00:00+00:00";
        OffsetDateTime parsed = ParsingUtilities.stringToDate(offsetDate);
        OffsetDateTime expected = OffsetDateTime.parse(offsetDate);
        Assert.assertEquals(expected, parsed); 
    }
```

If anything is still unclear, do let me know (I am happy to discuss that directly over hangouts for instance). If you want me to take this over, I can also do that.

**Comment by jackyq2015** [comment]
@wetneb I cannot reproduce this. I reconciled name "George Washington" and use "Add column from reconciled data"  to get the "date of birth", I can get the 1732-02-22T00:00:00Z without issue. And I can reload it after I bounce the OR. You need have the master code and a refresh project in order to work. If you can get a detail step to reproduce the issue I will give another try. 

Please see my comment [here](https://github.com/OpenRefine/OpenRefine/issues/1564#issuecomment-381005850). The commit 23ec54b is actual to restore the original behaviour, not to change it.

But still you can go ahead to improve it whatever you think it's appropriate.  Maybe I am mistaken

**Comment by wetneb** [comment]
Hmm, it's curious that you cannot reproduce the issue… Which JDK are you using? I can observe the issue with OpenJDK8.

I'll go ahead and propose another version that should hopefully work for everyone.

**Comment by jackyq2015** [comment]
$ java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

**Pull request closed without merging**
