### PR TITLE
[#3243] Ignore JSON comments by default

### PR DESCRIPTION
**Pull request by zyadtaha**
Fixes [#3243](https://github.com/OpenRefine/OpenRefine/issues/3243)

Changes proposed in this pull request:
- Ignore JSON comments by default while importing JSON files

### CODE REVIEW

**Comment by zyadtaha** [comment]
Hi @wetneb, 
I am here from GSoC 2024 and have solved this [issue](https://github.com/OpenRefine/OpenRefine/issues/3243) and I hope you assign it to me and merge the pull request.
Waiting for your feedback and excited to start contributing to another good first issue!

**Review by wetneb — CHANGES_REQUESTED** [review]
Hi @zyadtaha, thanks for this, it looks very good to me!
Could you add a unit test demonstrating the support of comments?
Adding a test case in `JsonImporterTests` should be sufficient for this.

**Comment by zyadtaha** [comment]
Hi @wetneb, 
I've added a unit test to cover the 3 types of JSON comments
please review again.

**Comment by zyadtaha** [comment]
Done @wetneb

**Comment by zyadtaha** [comment]
Thanks! @wetneb ,
What's next ? Should I start to write the proposal or contribute to more good first issues ?

**Comment by wetneb** [comment]
There is no set number of PRs we expect applicants to have submitted for their GSoC application. Depending on the project you want to do, it might be useful to also try making changes to the frontend, to be familiar with that part too.
Feel free to look at other issues, not just the ones tagged as good first issues, since you have already fixed your first issue.

**Comment by zyadtaha** [comment]
Great! Is there any recommended frontend issues to fix ? 
Also, when I was testing, I found a flaky test in `ColumnAdditionByFetchingURLsOperationTests.testInvalidUrl` which gives me `process failed to complete within timeout 3000` and to pass, we just need to change the timeout to be 30000 instead of 3000 in line 216.
So should i just ignore it or make an issue and fix it ?

**Pull request merged**
