### PR TITLE
Expose Wikibase editing errors in the grid

### LINKED ISSUE #1782: Find a way to report failures of item creations for new editors in Wikidata extension
**Describe the bug**
It seems that some new item creations are blocked for new editors. Maybe we should just slow down the edit rate to help with that (check needed with Wikidata admins).
We need a way to report creation failures to the user - for now we need to look up the logs but they are not always easily available (for instance when running OR on a mac).

### LINKED ISSUE #5166: Make error messages more useful
When an error occurs it's not clear which edit gives a problem, I'm trying to correct 73 records and everytime at 40% it gets stuck. In the console I get an error, but no idea which edit exactly gives the problem.

### Proposed solution
Add the statement that is being sent to Wikidata in the error message, so it's easier to debug where the error could be.

### Alternatives considered
Add the Qid of the statement that gives the problem.

### Additional context
```
Exception in thread "Thread-8" java.lang.IllegalArgumentException: Statements describe different subject.
        at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
        at org.wikidata.wdtk.datamodel.implementation.StatementDocumentUpdateImpl.<init>(StatementDocumentUpdateImpl.java:68)
        at org.wikidata.wdtk.datamodel.implementation.LabeledDocumentUpdateImpl.<init>(LabeledDocumentUpdateImpl.java:64)
        at org.wikidata.wdtk.datamodel.implementation.TermedDocumentUpdateImpl.<init>(TermedDocumentUpdateImpl.java:78)
        at org.wikidata.wdtk.datamodel.implementation.ItemUpdateImpl.<init>(ItemUpdateImpl.java:91)
        at org.wikidata.wdtk.datamodel.implementation.DataObjectFactoryImpl.getItemUpdate(DataObjectFactoryImpl.java:405)
        at org.wikidata.wdtk.datamodel.helpers.Datamodel.makeItemUpdate(Datamodel.java:1219)
        at org.openrefine.wikidata.updates.ItemEdit.toEntityUpdate(ItemEdit.java:165)
        at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:173)
        at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:262)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by wetneb**
Closes #1782.

This follows the design proposed [on the forum](https://forum.openrefine.org/t/partial-results-of-long-running-operations/482).
The Wikibase upload operation creates a new column (or reuses the column, if it already exists) to store the editing errors of edits related to a given row:
image
Runnning the operation also creates a facet which can be used to select the rows based on whether they encountered errors or not:
image
This facet is generated by the GREL expression `if(isError(value), 'failed edit', 'successful edit')`.

For successful edits I think it would be nice to store some value (to distinguish it from no edit being made). I thought about adding a URL to the diff view of the edit (such as https://www.wikidata.org/w/index.php?diff=1920784148&oldid=1919995661).

This also closes #5166, since it makes it possible to relate the errors to the offending lines better.

You can try this PR on [this sample project](https://github.com/OpenRefine/OpenRefine/files/11822075/Wikibase-editing-error-example.openrefine.tar.gz): uploading that project to Wikidata will not make any edits (the first row fails to create an item, the second one does not make any edit because the data being pushed matches what is already on Wikidata).

cc @OpenRefine/designers

This is meant to be a basic implementation that can be improved on (for instance, localization can be improved). I would like to release this in 4.0-alpha2 to gather feedback about the UX. One other question is where to insert the column with the editing results. Currently it is added after all other columns, which might be a bit inconvenient for projects with many columns.

### CODE REVIEW

**Comment by thadguidry** [comment]
May be a "view" option that would collapse all columns except the entity and the Wikibase error column? The view option could be a menu item under Wikibase extension?

**Comment by elebitzero** [comment]
@wetneb

I pulled the branch and tried importing your sample project, but the project page is blank.
I see an error in the JavaScript console:

```
project-bundle.js:37578 Uncaught TypeError: Cannot read properties of undefined (reading 'css')
    at resize (project-bundle.js:37578:4)
    at initializeUI (project-bundle.js:37638:3)
    at project-bundle.js:38224:9
    at Object.success (project-bundle.js:37742:21)
    at fire (project-bundle.js:3215:31)
    at Object.fireWith [as resolveWith] (project-bundle.js:3345:7)
    at done (project-bundle.js:9619:14)
    at XMLHttpRequest.<anonymous> (project-bundle.js:9880:9)

```
It seems to be related to a change you have made in the 4.0 branch:
image

**Comment by elebitzero** [comment]
Also, is 4.0 supposed to be able to load 3.x projects?  Because when I switched to 4.0 branch and built and ran OpenRefine, I don't see any of my 3.x projects in the project list.

**Comment by wetneb** [comment]
@elebitzero Thanks a lot for checking it out, it's very curious! I looked into it and I am unsure why you are getting this. Could it be some sort of caching error, with `project.vt` being left over from the master branch? That is where this `notificationContainer` is defined.

Did you `./refine clean` after switching to this branch (although it's not clear to me why not doing it would cause this). I wonder if you have the same issue with the snapshot builds for 4.0:
* [Linux](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=linux&p=tar.gz)
* [MacOS](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=mac&p=dmg)
* [Windows without embedded JRE](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=win&p=zip)
* [Windows with embedded JRE](https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=win-with-java&p=zip)

> Maybe a "view" option that would collapse all columns except the entity and the Wikibase error column? The view option could be a menu item under Wikibase extension?

That's an interesting idea! One problem is that the entity on which the edit is made is not necessarily generated from a column (it can be a constant, directly input in the schema). We can definitely consider explicitly including the subject entity in the error message, though (maybe that's a better fix of #5166).

**Comment by wetneb** [comment]
And about projects from 3.x not appearing, yes that is normal: OpenRefine 4 uses a separate workspace. I intend to emphasize that in the release notes but maybe it would be worth adding some note about that in the tool itself (for instance by changing the note shown when the list of projects is empty?).

**Comment by elebitzero** [comment]
> Did you `./refine clean` after switching to this branch (although it's not clear to me why not doing it would cause this). I wonder if you have the same issue with the snapshot builds for 4.0:

I am on Windows and I did:
```
refine.bat clean
refine.bat build
refine.bat run
```

I thought since you changed that line, maybe you would know what happened. If someone else tries it we will see if they get the same error. I can look into it further.

**Comment by wetneb** [comment]
Closing as it is stale. I'll reopen after rebasing.

**Pull request closed without merging**
