### PR TITLE
Resolved Issue 6316: Use SVG logo and icons instead of png

### LINKED ISSUE #6316: Use SVG logo and icons instead of png
Hello,
I was very surprised to see OpenRefine still use a png image for its logos displayed in the application
image

image

SVG (vector image format) are great : fast, light, can resize easily, etc.. and work perfectly in a web browser. Moreover, it's not a lot of work since the logo is already available in svg
https://fr.wikipedia.org/wiki/OpenRefine#/media/Fichier:OpenRefine_favicon_(2018-present).svg

### Proposed solution
To use svg version of these pictures

### Alternatives considered
N/A
### Additional context
N/A

### PR DESCRIPTION
**Pull request by JasonZelmanovich**
Fixes #6316

### CODE REVIEW

**Comment by wetneb** [comment]
Hi @JasonZelmanovich, are you still working on this?

**Comment by JasonZelmanovich** [comment]
Yes, I plan to fix those issues by end of the day

**Comment by wetneb** [comment]
@JasonZelmanovich I have opened a broader issue about removing all uses of raster icons in the tool: #6538.
As part of that I have identified multiple copies of the OpenRefine logo, all of which would be worth deleting in this PR (I would say):
* [main/webapp/modules/core/images/logo-gem-126.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/logo-gem-126.png)
* [main/webapp/modules/core/images/logo-openrefine-550.png](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/images/logo-openrefine-550.png)
* [extensions/gdata/src/com/google/refine/extension/gdata/logo-openrefine-550.png](https://github.com/OpenRefine/OpenRefine/blob/master/extensions/gdata/src/com/google/refine/extension/gdata/logo-openrefine-550.png)

Let me know if there is anything I can help you with here :)

**Comment by wetneb** [comment]
@JasonZelmanovich are you still working on this PR or should we close it?

**Comment by wetneb** [comment]
@JasonZelmanovich I'm closing this to keep our PR backlog manageable, but feel very invited to reopen a PR if you want to get back to it.

**Pull request closed without merging**
