### PR TITLE
Create new GitHub action for CodeQL

### PR DESCRIPTION
**Pull request by stweil**
CodeQL adds code scanning for critical security issues. The results will be shown for project owners on
https://github.com/OpenRefine/OpenRefine/security.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
CodeQL replaces the deprecated LGTM, see issue #2006.

**Comment by tfmorris** [comment]
Thanks for the contribution! It looks like the autobuild is using the command

```
mvn clean package -f "pom.xml" -B -V -e -Dfindbugs.skip -Dcheckstyle.skip -Dpmd.skip=true -Dspotbugs.skip -Denforcer.skip -Dmaven.javadoc.skip -DskipTests -Dmaven.test.skip.exec -Dlicense.skip=true -Drat.skip=true -Dspotless.check.skip=true 
```
which fails when it can't find the tool `genisoimage`.

Replacing the autobuild with `./refine build` may fix this, but I haven't tried it.

**Comment by stweil** [comment]
> Replacing the autobuild with `./refine build` may fix this, but I haven't tried it.

Let's try it. I pushed a commit with the suggested modification.

**Comment by stweil** [comment]
It seems to work now for the Java code, too. I get 80 security related items.

**Review by tfmorris — COMMENTED** [review]
LGTM, but I'll let @wetneb approve.

**Comment by tfmorris** [comment]
Note: The UI test failure is due to a flaky test which is failing across multiple branches/PRs.

The CodeQL CI failure due to the flagged issues is more problematic. It'd be a heavy lift to fix all the problems immediately, but super annoying to have to live with the CI going red when this is merged.

**Review by wetneb — APPROVED** [review]
Fine with me too, let's give it a try!

**Comment by wetneb** [comment]
@stweil I've invited you to the organization in case you have any interest in fixing some of the reported issues.

**Pull request merged**
