### PR TITLE
added margin prop to move cell editor 1cell size down

### LINKED ISSUE #1116: Move "Edit" cells window to lower position
Modal window, that opened by cells "Edit", should be lower, to be able to see full string you edit (just to size of one row lower of current position).

### PR DESCRIPTION
**Pull request by elroykanye**
Fixes #1116

Changes proposed in this pull request:
- an additional margin rule for the `data-table-cell-editor` to move cell editors one cell down when editing the content

### CODE REVIEW

**Comment by elroykanye** [comment]
### Before
 - cell-edit before
 Case 1
 - cell-edit before 1
 Case 2

### After
- ce--edit after
Case 1
 - ce--edit after 1
 Case 2

**Comment by wetneb** [comment]
It seems like a relatively safe move to me! In general cells can contain multiple lines, so it does not guarantee that we still see the entire original cell content while editing, but perhaps that is not a big deal. I would like to check what happens when editing a cell at the very bottom of the screen, I suspect the edit dialog could then be hidden.

**Comment by elroykanye** [comment]
> It seems like a relatively safe move to me! In general cells can contain multiple lines, so it does not guarantee that we still see the entire original cell content while editing, but perhaps that is not a big deal. I would like to check what happens when editing a cell at the very bottom of the screen, I suspect the edit dialog could then be hidden.

Oh! That is true. I will look into this.

**Comment by wetneb** [comment]
Hi @elroykanye, are you still working on this?

**Comment by wetneb** [comment]
Ooops, I closed the PR accidentally while commenting: feel free to reopen if you are still working on it!

**Pull request closed without merging**
