### PR TITLE
Updated dependabot to check dependencies in the main webapp.

### PR DESCRIPTION
**Pull request by elebitzero**
Changes proposed in this pull request:
- Updated dependabot to check dependencies in the main webapp.

### CODE REVIEW

**Comment by wetneb** [comment]
I suspect we also need to add a `package-lock.json` file to the repository, no?

**Comment by elebitzero** [comment]
I don't think the package-lock.json is required.  The other package.json that Dependabot is checking in docs/ and main/tests/cypress do not have package-lock.json checked in either.

**Comment by wetneb** [comment]
At least that is what I am seeing in the GitHub UI:

image

**Comment by elebitzero** [comment]
I added the package-lock.json.

**Review by wetneb — APPROVED** [review]

**Pull request merged**
