### PR TITLE
Pressing "Enter" in the project name field at the preview stage should create the project

### LINKED ISSUE #3137: Pressing "Enter" in the project name field at the preview stage should create the project
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

When previewing an importer's results, there is a text field to enter the project name. When pressing Enter in this field, I would expect the project to be created (without having to click the "Create Project" button).

image

### PR DESCRIPTION
**Pull request by khadijm**
Fixes #3137

Changes proposed in this pull request:

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
Thank you! Have you tried using the `form.submit` event instead, by wrapping this field (and the corresponding button) in a `<form>` element? I think that would be more accessible.

**Comment by khadijm** [comment]
@wetneb 
don't know if it's a bug i run `mvn clean install` and i got this in my terminal 
https://pastebin.com/cJfHjbrM

./refine will give me this error on the browser 
Screenshot from 2022-04-05 08-32-06

**Comment by wetneb** [comment]
You should rather go through the 'refine' script to make sure Frontend dependencies are also installed.

**Comment by wetneb** [comment]
Hi @khadijm, are you still working on this?

**Comment by khadijm** [comment]
yep

**Comment by khadijm** [comment]
@wetneb 
i run `./refine build` and i got the same error 
https://pastebin.com/cJfHjbrM

`./refine` will give this error on the browser 
Screenshot from 2022-04-05 08-32-06

i thinks it's a bug, should I open an issue to report for it's ?

**Comment by wetneb** [comment]
The pastebin link you provided shows a normal test output, none of those lines indicate a bug (we should make sure our tests pass without printing stack traces in the console, but that is a different thing).

**Comment by antoine2711** [comment]
> `./refine` will give this error on the browser Screenshot from 2022-04-05 08-32-06

The JS console log show that jQuery is not loaded. And you have a lot of 404, also pointing some network issue. These point to a major problem, but I would first check my own system and network environnement before pointing OR.

Also, I find that sometime, `./refine clean; ./refine build; ./refine` works better than just build & run. Not sure why though. @wetneb, if I recalled correctly, suggested it once.

Regards, Antoine

**Comment by wetneb** [comment]
Closing this per inactivity - we can reopen if there is interest in continuing the work.

**Pull request closed without merging**
