### PR TITLE
Adding 3 prefs in the documentation: ui.browsing.pageSize, ui.browsing.facetsHistoryPanelWidth & cell-ui.previewMatchedCells

### PR DESCRIPTION
**Pull request by antoine2711**
Adding 2 prefs in the documentation : ui.browsing.pageSize & ui.browsing.facetsHistoryPanelWidth

Changes proposed in this pull request:
- Preference documentation for `ui.browsing.pageSize`
- Preference documentation for `ui.browsing.facetsHistoryPanelWidth`
- Preference documentation for `cell-ui.previewMatchedCells`

Regards,
   Antoine

### CODE REVIEW

**Comment by wetneb** [comment]
In general it would be better to update the docs in the same PR as the one that makes the changes in the code: so, the addition of `ui.browsing.facetsHistoryPanelWidth` in #2772. Not a big deal for this time, but maybe think about it next time?

**Comment by antoine2711** [comment]
> In general it would be better to update the docs in the same PR as the one that makes the changes in the code: so, the addition of `ui.browsing.facetsHistoryPanelWidth` in #2772. Not a big deal for this time, but maybe think about it next time?

Yes, I tried, but I was not able, it would have created a new PR… :-( 

Also, I have seen a third prefs missing: `cell-ui.previewMatchedCells`. @wetneb : Is it still useful?

I did also add a new column, « Since version », so I thought it would justify a new PR. 

But yes, next time, I will do it in the same PR.

Regards,
   Antoine

**Comment by wetneb** [comment]
Yes it could be useful to document that missing preference too!

**Comment by antoine2711** [comment]
> Yes it could be useful to document that missing preference too!

`ui.previewMatchedCells` is added.

Regards, A.

**Pull request merged**
