### PR TITLE
Update Java version

### PR DESCRIPTION
**Pull request by thadguidry**
since the older JDK 14 version page says its been superseded with the new version

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
Hmm, actually users should not need a JDK, only a JRE (Java Runtime Environment), so we should update this page to replace all mentions of "JDK" by "JRE".

**Comment by thadguidry** [comment]
@wetneb The **Run from source** section was originally put on the Readme prior to our Snapshot releases, and also to give devs, not users, a quick glance at how to run OpenRefine.  I don't think we need that section at all anymore on the Readme.  Instead, I'd remove it since we already have a links further down for Contribution (Developers Guide & Architecture).

**Comment by thadguidry** [comment]
@wetneb In that case actually...we should probably just tell them about https://www.java.com to download JRE and the rest of all those technical details actually should go into the Technical docs, I would think?  I mean, for User docs, do we really need to go into all the details for "Install or upgrade Java"?

**Comment by allanaaa** [comment]
Oh! How interesting. Is JDK required for anything? Development?

**Comment by wetneb** [comment]
Yes JDK is required for development only.

**Comment by thadguidry** [comment]
@allanaaa Thanks this looks much better and makes more sense.

**Comment by allanaaa** [comment]
If we're good with this, let's merge it - there are people testing the docs right now. :)

**Review by wetneb — APPROVED** [review]

**Pull request merged**
