### PR TITLE
Refactor row count handling for ProjectMetadata. Remove from GetRows.

### LINKED ISSUE #1380: Update "Last modified" date only when project is actually modified and not when it is just opened
In the project list under "Open Project", each time a project is opened, the "last modified" date of the project is reset, even when no edits were made. The time stamp however should only be updated when actual changes are made to the project (i.e. steps are added to the history). 

Steps to reproduce: 

- Start OpenRefine
- Go to "Open Project" and select an old project (preferably one that is not on top of the list)
- Open the project and do nothing
- Go back to the OpenRefine start page
- Refresh the page by pressing F5
- Go to "Open Project"
- The viewed project is now on top of the list with the current time as "last modified"

Alternatively a second column for "Last viewed" could be added for this kind of behavior but the "Last modified" column should remain stable until the project is actually modified. 

System Info
- OpenRefine 2.8 (this behavior was not present in 2.7)
- Windows 7
- Tested with Firefox 57 and Chrome 63.

### LINKED ISSUE #3475: Row count is returned as 0 occasionally from the server while fetching metadata
While writing tests for project_metadata #3474 , I encountered an occasional bug. Table row metadata is being returned as zero sometimes from the openrefine server and hence Rows is being shown as 0.
### To Reproduce
1. Visit the `Open Project` page
2. See table columns, row is sometimes returned as 0 from the server

### Response returned by the server

```json
{
    "projects": {
        "2610263550897": {
            "created": "2021-01-15T17:30:02Z",
            "modified": "2021-01-15T17:30:02Z",
            "name": "1610731802333",
            "tags": [],
            "creator": "",
            "contributors": "",
            "subject": "",
            "description": "",
            "rowCount": 0,
            "title": "",
            "version": "",
            "license": "",
            "homepage": "",
            "image": "",
            "importOptionMetadata": [
                {
                    "includeFileSources": false,
                    "includeArchiveFileName": false,
                    "encoding": "US-ASCII",
                    "ignoreLines": -1,
                    "headerLines": 1,
                    "skipDataLines": 0,
                    "storeBlankRows": true,
                    "storeBlankCellsAsNulls": true,
                    "separator": ",",
                    "guessCellValueTypes": false,
                    "processQuotes": true,
                    "quoteCharacter": "\"",
                    "trimStrings": true,
                    "projectName": "1610731802333",
                    "fileSource": "food.mini.csv",
                    "archiveFileName": null
                }
            ],
            "customMetadata": {}
        }
    }
}
```
Screenshot 2021-01-16 at 1 00 52 AM

Meanwhile, when I click on the project, it shows two rows.
Screenshot 2021-01-16 at 1 01 01 AM

### LINKED ISSUE #5387: Rows are counted only after the project is opened
### To Reproduce
1. First, upload a file via API
2. Then, open the projects' list

### Current Results
`Rows` column shows 0 rows.

### Expected Behavior
Rows should be displayed.

### Versions
 - Operating System: Linux
 - Browser Version: Firefox
 - JRE or JDK Version: OpenJDK Runtime Environment 17.0.4+8-nixos
 - OpenRefine: 3.6.2 and 3.6.1

### Additional context
Opening the project link updates the `rows` column.

Workaround: GET request toward `/command/core/get-rows?project=PROJECT&start=0&limit=0`.

### PR DESCRIPTION
**Pull request by tfmorris**
Fixes #1380 Fixes #5387 Probably fixes #3475

Changes proposed in this pull request:
- refactor row counter maintenance in ProjectMetadata so it's done when row list is updated rather than on every GetRows command. (#1380)
- Update row count when project is created/registered (#5387)
- Update row count for when opening legacy projects which were created before row count was stored in metadata (but do it in a way that doesn't change the Modified date for the project)

### CODE REVIEW

**Comment by ostephens** [comment]
>add a ToDo to GetRows command where setRowCount is being called in the first place (which seems totally wrong)

Not sure if this is related, but just noted this issue where the row count is reported incorrectly as zero #3475

**Comment by tfmorris** [comment]
@ostephens Thanks for the pointer. I added a comment which describes ways that failure mode could be triggered. The refactoring for #1380 and  #5387 will likely cure #3475 as well.

**Review by wetneb — APPROVED** [review]
Thanks a lot! It looks like there are test failures which are likely not spurious and worth fixing, but the approach looks good to me.

**Comment by tfmorris** [comment]
> It looks like there are test failures which are likely not spurious and worth fixing

Yes, there's a test that knows about internal implementation details and is testing those instead of the external behavior. :(
I didn't change the approach, but adjusted it to track the new internals.

**Pull request merged**
