### PR TITLE
File type detection fails when multiple files are imported at once

### LINKED ISSUE #6772: File type detection fails when multiple files are imported at once
The heuristic to detect file types seems to have a weird behavior when working on multiple files, even though those files have a consistent file type which OpenRefine is able to detect correctly when they are imported individually

### To Reproduce

Create two text files `test.md` and `test2.md`, both containing the following content:
```
## Markdown test

This is a [test](https://gnu.org) test
```

2. Import both of those files at the same time (by selecting them both in the same folder)

### Current Results

The files are incorrectly detected as Excel files, which obviously fails.

### Expected Behavior

They should be detected as text files (which indeed happens when selecting only one file)

### Screenshots

image

### Versions
 - Operating System: Debian testing
 - JRE or JDK Version: 19
 - OpenRefine: 3.9-SNAPSHOT
 
### Additional context
Observed at Wikimania 2024

### PR DESCRIPTION
**Pull request by sunilnatraj**
Added definition for MD format files

Fixes #6772 

Changes proposed in this pull request:
- Added definition for MD format files 
- Performed test with multiple file formats
-

### CODE REVIEW

**Comment by tfmorris** [comment]
Thanks for sticking with this. I think your previous PR was closer to what we need. Perhaps we should focus on fixing the test failure in that one.

Adding a definition for Markdown files is really just a workaround, because there will always be other types of text files with extensions that we don't recognize, and we would still like things to work in that case.

**Comment by sunilnatraj** [comment]
@tfmorris I will look into the logic for identification of file contents. Do i open a new issue to review and address the FormatGuesser issue?

**Comment by tfmorris** [comment]
> Do i open a new issue to review and address the FormatGuesser issue?

If you think there is a problem with it, yes, please open an issue with as much detail as possible. Thanks!

**Comment by tfmorris** [comment]
I'm going to close this since it's not really the direction we want to go. I've reopened #6788 and provided some feedback there on the failing tests.

**Pull request closed without merging**
