### PR TITLE
fixed href tag creation for URLs in cell text

### LINKED ISSUE #2519: Hyperlink is created for cell value even when invalid and text datatype is choosen
**Describe the bug**
Hyperlink is created for cell value, even when text is specified as the datatype.

**To Reproduce**
1. Edit a cell's value
2. Choose datatype: Text
3. Paste the following text exactly (includes whitespace):
```
https://www.wikidata.org/wiki/Property:P670 https://www.wikidata.org/wiki/Property:P669 are now mapped to https://schema.org/streetAddress via https://www.wikidata.org/wiki/Property:P2235
```

4. Click Apply

**Current Results**
Notice that cell value is shown completely as a clickable hyperlink rather than just text.

**Expected behavior**
The cell's value should be rendered with only those pieces which represent valid URLs hyperlinked. For the example above, there should be four hyperlinks with unlinked text " are now mapped to " and " via " between them.

Browsers now have native support for URL detection and we should take advantage of that.  See comment https://github.com/OpenRefine/OpenRefine/issues/2519#issuecomment-612645821

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Firefox
 - JRE or JDK Version: JDK8

**OpenRefine (please complete the following information):**
 - Version: Trunk (master)

**Additional Context**
The use case that I actually had here in #2519 was that of a cell of text that might contain multiple URLs would be convenient to be able to click on the URLs and it open a browser for quick verification during reconciling processes.

As long as scrolling the grid still works, editing the cells still works, running GREL operations on the cell text, and exporting the cells still works, then I think it satisfies most of the needs that will come up within GLAM reconciling processes with multiple URLs in a cell text for clicking and verifying.

### PR DESCRIPTION
**Pull request by singhakshita**
fixes #2519
- added <a>href tag creation for URLs in cell text.
- added tests.

### CODE REVIEW

**Review by thadguidry — CHANGES_REQUESTED** [review]

**Review by thadguidry — APPROVED** [review]

**Comment by wetneb** [comment]
@thadguidry hmm, since when do you merge PRs without a code review?

**Comment by thadguidry** [comment]
@wetneb Hi Antonin, I tested his changes, reviewed them, requested changes, he made the changes, I verified, and merged.  Sorry, which parts am I allowed to do or not? Oh, did our process change where we need to have 2 reviewers now?  Please explain and happy to adjust.

**Comment by wetneb** [comment]
I think we have a long-standing agreement that you do not merge PRs with code changes without the approval of a developer. If you want to stick to the roles defined in the gouvernance document, then I think you should not be a committer anymore.

**Comment by kushthedude** [comment]
Hi @wetneb @thadguidry , can this PR be reverted as it changed around 3k lines in code, or should I open a followup pr to fix them? It has undone many formatting changes in the cypress-test-suite, which will create more conflicts with the ESlint.

**Comment by wetneb** [comment]
@kushthedude yes, done.

@singhakshita I am sorry that we had to undo this merge - your PR was merged erroneously by @thadguidry without review by a developer. If you could open a new pull request with your changes it would be great. If you want help with that let me know.

**Comment by singhakshita** [comment]
> Hi @wetneb @thadguidry , can this PR be reverted as it changed around 3k lines in code, or should I open a followup pr to fix them? It has undone many formatting changes in the cypress-test-suite, which will create more conflicts with the ESlint.

@kushthedude i have added changes to two files ,one is cell.ui.js and other is the test file proper-displayjs ,if i run prettier 
it apply changes to all the tests files and increases the number of changes , and without runing prettier if i send the PR its fails my ui.integration test ,can you please suggest me  what should be done.

**Comment by thadguidry** [comment]
I agree with @singhakshita as I saw the same thing local with prettier and thought it was conforming against those 3k lines

I think we need to understand why that is and document the right steps for verifying the correct formatting locally.

@wetneb sure I will remove my watching on repo.

**Comment by kushthedude** [comment]
This changes were due to seperation of concerns in eslint and prettier PR,
as can be seen prettier flow is already merged but eslint is still
remaining to go into master.

**Pull request merged**
