### PR TITLE
Restore log levels after Jetty update

### LINKED ISSUE #3782: Generous logging since the Jetty upgrade
Since the Jetty upgrade we have more logging lines showing up by default:
```
20:06:58.400 [...eclipse.jetty.util.log] Logging initialized @386ms to org.eclipse.jetty.util.log.Slf4jLog (0ms)
20:06:58.416 [            refine_server] Starting Server bound to '127.0.0.1:3333' (16ms)
20:06:58.416 [            refine_server] refine.memory size: 1400M JVM Max heap: 1468006400 (0ms)
20:06:58.548 [            refine_server] Initializing context: '/' from '/home/antonin/Programmation/ORmaster/main/webapp' (132ms)
20:06:58.690 [            refine_server] Starting autoreloading scanner...  (142ms)
20:06:58.832 [..pse.jetty.server.Server] jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 11.0.11-ea+4-post-Debian-1 (142ms)
20:06:59.579 [..dardDescriptorProcessor] NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet (747ms)
20:06:59.594 [..se.jetty.server.session] DefaultSessionIdManager workerName=node0 (15ms)
20:06:59.594 [..se.jetty.server.session] No SessionScavenger set, using defaults (0ms)
20:06:59.597 [..se.jetty.server.session] node0 Scavenging every 600000ms (3ms)
20:06:59.634 [..util.DeprecationWarning] Using @Deprecated Class org.eclipse.jetty.servlets.GzipFilter (37ms)
20:06:59.636 [..tty.servlets.GzipFilter] GzipFilter is deprecated. Use GzipHandler (2ms)
20:06:59.683 [...handler.ContextHandler] Started o.e.j.w.WebAppContext@6a6cb05c{OpenRefine,/,file:///home/antonin/Programmation/ORmaster/main/webapp/,AVAILABLE}{/home/antonin/Programmation/ORmaster/main/webapp} (47ms)
20:06:59.719 [..erver.AbstractConnector] Started ServerConnector@5b464ce8{HTTP/1.1,[http/1.1]}{127.0.0.1:3333} (36ms)
20:06:59.719 [..pse.jetty.server.Server] Started @1726ms (0ms)
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/antonin/Programmation/ORmaster/main/webapp/WEB-INF/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/antonin/Programmation/ORmaster/server/target/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
20:07:01.663 [                   refine] Starting OpenRefine 3.5-beta [09c2e06]... (0ms)
20:07:01.665 [                   refine] initializing FileProjectManager with dir (2ms)
20:07:01.665 [                   refine] /tmp/data (0ms)
20:07:01.686 [       FileProjectManager] Using workspace directory: /tmp/data (21ms)
20:07:01.692 [       FileProjectManager] Loading workspace: /tmp/data/workspace.json (6ms)
20:07:01.693 [       FileProjectManager] Loading workspace: /tmp/data/workspace.temp.json (1ms)
20:07:01.693 [       FileProjectManager] Loading workspace: /tmp/data/workspace.old.json (0ms)
20:07:01.693 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (0ms)
20:07:01.713 [                butterfly] Starting butterfly ... (20ms)
20:07:01.713 [                butterfly] Properties loaded from /home/antonin/Programmation/ORmaster/main/webapp/WEB-INF/butterfly.properties (0ms)
20:07:01.713 [                butterfly] Autoreloading is enabled (0ms)
20:07:01.782 [                butterfly] > process properties (69ms)
20:07:01.783 [                butterfly]  Butterfly home: /home/antonin/Programmation/ORmaster/main/webapp (1ms)
20:07:01.784 [                butterfly] < process properties (1ms)
20:07:01.784 [                butterfly] > load modules (0ms)
20:07:01.863 [                butterfly] < load modules (79ms)
20:07:01.864 [                butterfly] > create modules (1ms)
20:07:01.943 [                butterfly] < create modules (79ms)
20:07:01.944 [                butterfly] > load module wirings (1ms)
20:07:01.944 [                butterfly]  Loaded module wirings from: /home/antonin/Programmation/ORmaster/main/webapp/WEB-INF/modules.properties (0ms)
20:07:01.945 [                butterfly] < load module wirings (1ms)
20:07:01.945 [                butterfly] > wire modules (0ms)
20:07:01.945 [                butterfly]  mounting modules (0ms)
20:07:01.946 [                butterfly]  No mount point defined for module 'database', mounting to '/extension/database' (1ms)
20:07:01.946 [                butterfly]  No mount point defined for module 'jython', mounting to '/extension/jython' (0ms)
20:07:01.946 [                butterfly]  No mount point defined for module 'phonetic', mounting to '/extension/phonetic' (0ms)
20:07:01.947 [                butterfly]  No mount point defined for module 'pc-axis', mounting to '/extension/pc-axis' (1ms)
20:07:01.947 [                butterfly]  No mount point defined for module 'gdata', mounting to '/extension/gdata' (0ms)
20:07:01.947 [                butterfly]  No mount point defined for module 'wikidata', mounting to '/extension/wikidata' (0ms)
20:07:01.947 [                butterfly]  No mount point defined for module 'sample', mounting to '/extension/sample' (0ms)
20:07:01.948 [                butterfly] < wire modules (1ms)
20:07:01.948 [                butterfly] > configure modules (0ms)
20:07:02.914 [                butterfly] < configure modules (966ms)
20:07:02.914 [                butterfly] > initialize modules (0ms)
20:07:10.375 [                butterfly] < initialize modules (7461ms)
20:07:10.377 [                butterfly] GET / [main] (2ms)
20:07:11.157 [                butterfly] GET /wirings.js [main] (780ms)
20:07:11.160 [                butterfly] GET /styles/common.less [main] (3ms)
20:07:11.169 [                butterfly] GET /styles/util/encoding.less [main] (9ms)
20:07:11.177 [                butterfly] GET /styles/util/dialog.less [main] (8ms)
20:07:11.192 [                butterfly] GET /index-bundle.js [main] (15ms)
20:07:11.200 [                butterfly] GET /styles/pure.css [main] (8ms)
20:07:11.228 [                butterfly] GET /styles/index.less [main] (28ms)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mozilla.javascript.MemberBox (file:/home/antonin/Programmation/ORmaster/main/webapp/WEB-INF/lib/js-1.7R2.jar) to method sun.net.www.protocol.file.FileURLConnection.getInputStream()
WARNING: Please consider reporting this to the maintainers of org.mozilla.javascript.MemberBox
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
20:07:11.286 [                butterfly] GET /styles/index/create-project-ui.less [main] (58ms)
20:07:11.363 [                butterfly] GET /styles/index/open-project-ui.less [main] (77ms)
20:07:11.398 [                butterfly] GET /styles/index/import-project-ui.less [main] (35ms)
20:07:11.472 [                butterfly] GET /styles/index/default-importing-controller.less [main] (74ms)
20:07:11.493 [                butterfly] GET /styles/index/default-importing-file-selection-panel.less [main] (21ms)
20:07:11.521 [                butterfly] GET /styles/index/default-importing-parsing-panel.less [main] (28ms)
20:07:11.527 [                butterfly] GET /styles/index/default-importing-sources.less [main] (6ms)
20:07:11.575 [                butterfly] GET /externals/jquery-ui/css/ui-lightness/jquery-ui.css [main] (48ms)
20:07:11.580 [                butterfly] GET /externals/tablesorter/theme.blue.css [main] (5ms)
20:07:11.584 [                butterfly] GET /externals/select2/select2.css [main] (4ms)
20:07:11.615 [                butterfly] GET /styles/views/data-table-view.less [main] (31ms)
20:07:11.625 [                butterfly] GET /styles/index/fixed-width-parser-ui.less [main] (10ms)
20:07:11.626 [                butterfly] GET /styles/jquery-ui-overrides.less [main] (1ms)
20:07:11.638 [                butterfly] GET /styles/index/xml-parser-ui.less [main] (12ms)
20:07:11.672 [                butterfly] GET /styles/index/json-parser-ui.less [main] (34ms)
20:07:11.699 [                butterfly] GET /extension/database/styles/pure.css [main] (27ms)
20:07:11.702 [                butterfly] GET /styles/index/wikitext-parser-ui.less [main] (3ms)
20:07:11.709 [                butterfly] GET /extension/database/styles/jquery.contextMenu.css [main] (7ms)
20:07:11.729 [                butterfly] GET /extension/database/styles/bootstrap.css [main] (20ms)
20:07:11.750 [                butterfly] GET /extension/database/styles/database-import.less [main] (21ms)
20:07:11.768 [                butterfly] GET /extension/gdata/styles/importing-controller.less [main] (18ms)
20:07:11.931 [                butterfly] GET /images/logo-gem-126.png [main] (163ms)
20:07:11.948 [                butterfly] GET /images/logo-openrefine-550.png [main] (17ms)
20:07:12.227 [                   refine] POST /command/core/load-language (279ms)
20:07:12.322 [                   refine] GET /command/core/get-preference (95ms)
20:07:12.400 [                   refine] POST /command/core/load-language (78ms)
20:07:12.419 [                   refine] POST /command/core/load-language (19ms)
20:07:12.443 [                   refine] POST /command/core/load-language (24ms)
20:07:12.504 [                butterfly] GET /scripts/index/create-project-ui-source-selection.html [main] (61ms)
20:07:12.617 [                butterfly] GET /scripts/index/create-project-progress-panel.html [main] (113ms)
20:07:12.782 [                butterfly] GET /scripts/index/create-project-error-panel.html [main] (165ms)
20:07:12.823 [                   refine] POST /command/core/get-importing-configuration (41ms)
20:07:12.829 [                butterfly] GET /scripts/index/open-project-ui.html [main] (6ms)
20:07:12.880 [                   refine] GET /command/core/get-all-project-tags (51ms)
20:07:12.927 [                   refine] GET /command/core/get-all-project-metadata (47ms)
20:07:12.966 [                butterfly] GET /scripts/index/import-project-ui.html [main] (39ms)
20:07:12.996 [                   refine] GET /command/core/get-csrf-token (30ms)
20:07:13.023 [                butterfly] GET /scripts/index/lang-settings-ui.html [main] (27ms)
20:07:13.080 [                   refine] GET /command/core/get-languages (57ms)
20:07:13.212 [                   refine] GET /command/core/get-version (132ms)
20:07:13.590 [                   refine] GET /command/core/get-csrf-token (378ms)
20:07:13.593 [                   refine] GET /command/core/get-csrf-token (3ms)
20:07:13.600 [                butterfly] GET /scripts/index/default-importing-sources/import-from-computer-form.html [main] (7ms)
20:07:13.631 [                   refine] POST /command/core/set-preference (31ms)
20:07:13.634 [                   refine] POST /command/core/set-preference (3ms)
20:07:13.678 [                butterfly] GET /scripts/index/default-importing-sources/import-from-web-form.html [main] (44ms)
20:07:13.710 [                butterfly] GET /scripts/index/default-importing-sources/import-from-clipboard-form.html [main] (32ms)
20:07:13.743 [                butterfly] GET /extension/database/scripts/index/database-import-form.html [main] (33ms)
20:07:13.802 [                   refine] GET /command/database/saved-connection (59ms)
20:07:13.856 [                butterfly] GET /extension/gdata/scripts/index/import-from-gdata-form.html [main] (54ms)
20:07:13.904 [                butterfly] GET /images/large-spinner.gif [main] (48ms)
```

All the ones that start with `[                butterfly]` are new. It's not clear to me if we want to have them or not. It should be possible to remove if we do not.

### PR DESCRIPTION
**Pull request by wetneb**
Fixes #3782.

For some reason the logging levels are now taken from the `log4j.properties` file in the `main` module, not the `server` one. Not sure why. Anyway, this restores the previous log levels, which makes the output less verbose.

### CODE REVIEW

**Comment by wetneb** [comment]
I think it would be good to have this merged before the 3.5 beta. Perhaps @afkbrb could review it?

**Comment by afkbrb** [comment]
Maybe we should keep only one `log4j.properties`, as suggested by https://stackoverflow.com/questions/10890505/multiple-log4j-properties-files-in-classpath#comment27749949_10966948. We'd better figure out why the effective `log4j.properties` became the one in the main module instread of the one in the server module, make the one in the server module effective and delete the one in the main module. Or do you have better ideas?

**Comment by wetneb** [comment]
Yes it is not clear to me why one took precedence over the other. I would also be fine with having a single one, it would probably be cleaner indeed.

**Comment by wetneb** [comment]
Merging this in the coming days unless anyone has concerns.

**Pull request merged**
