### PR TITLE
pass the limit as int from javascript

### PR DESCRIPTION
**Pull request by jackyq2015**

### CODE REVIEW

**Comment by wetneb** [comment]
@thadguidry hmm… did you just merge this PR without discussion? I have reverted it.

@jackyq2015 I think it would be better that the server accepts JSON where the limit is either an int or a string. That would be more robust, for instance if people reuse existing JSON edit histories or use OR as a server for batch processing.

**Comment by thadguidry** [comment]
@wetneb I just checked and looks like older versions did actually perform a stringify and set the limit param as a String value and not as an Int.
capture

**Comment by wetneb** [comment]
@thadguidry yes, that's why it's really important to make sure we are maintaining compatibility with previous versions.

**Comment by thadguidry** [comment]
@wetneb thanks for keeping us honest. :)  our old memories are fading, but your young blood keeps the team FRESH :) :)

**Pull request merged**
