### PR TITLE
Translation ES

### PR DESCRIPTION
**Pull request by nestorjal**
Partial translation in Spanish

### CODE REVIEW

**Comment by magdmartin** [comment]
Thanks for the pull request Nestor! This is awesome! 
Checking your changes it seems you have a translation for every string. Can you precise what's need to be done to make the translation complete?

If you are interested, I can ask for contribution on the OpenRefine mailing list (you can do it too) and twitter account.

**Comment by nestorjal** [comment]
I'd like to precise which strings require translation, however I don't know how to put that in the JSON file, do you have any advice on that? I've a copy of the file with "TODOs" but in that way the JSON will be useless.

**Comment by magdmartin** [comment]
Sorry for the late answer. You may create the item in your TODO in [new issue](https://github.com/OpenRefine/OpenRefine/issues/new) with a Spanish translation tag to easily sort them.

@tfmorris are you ok to merge this partial translation so it is easier for other contributors to help? Should be we do that on a separated branch?

**Comment by tfmorris** [comment]
Thanks for the contribution.  I've merged what's been done so far.  Leaving the English strings for untranslated pieces is a good default so that users at least see something.  Please open a new pull request when you've made more progress on the translation.  We'd prefer that the pull requests be made from a feature branch (ie not "master") to reduce the chances of unintentional changes getting mixed in.  Thanks again!

**Comment by magdmartin** [comment]
related to issue #958

**Pull request merged**
