### PR TITLE
Wikidata login: form submittion by pressing Enter key

### PR DESCRIPTION
**Pull request by Bhanu-mbvg**
#2194 Issue Resolved

### CODE REVIEW

**Comment by wetneb** [comment]
Thanks a lot for this! I have noticed a few issues, here they are.

You duplicated existing code: the code for the Enter key and the code for the click on the Login button are the same. It would be better to define a function and reuse it in both places.

Pressing Enter in the login form now triggers a login _twice_, because there are two `keydown` events for a given key press. You can check that with your developer tools: you will see that two requests to `/command/wikidata/login` are generated for each key press.

Also, your event listener stays registered even when the dialog has been closed, which leads to the following problem:
* Open the dialog and try to login with invalid credentials.
* Close the dialog.
* Open any other dialog, or add a text facet for instance, input a few things in a text input and press Enter;
* You will see that requests to `/command/wikidata/login` are still fired.

So this could lead to the user logging in when they do something unrelated!

I think this issue could be solved by adding a function on the `<form>` element with the `onsubmit` attribute.

**Comment by Bhanu-mbvg** [comment]
Sure, thank you for mentioning the issues. Should I make a new pull request after making the required changes and close this pull request or make changes in this one only?

**Comment by wetneb** [comment]
@Bhanu-mbvg as you prefer!

**Comment by Bhanu-mbvg** [comment]
@wetneb I have worked and tresolved above 3 issues by : 

- Duplicated code converted into a `Login()` function
- Login form now triggers a login _once_ by having a variable `isOpen` variable
- keydown listener only active when this `isOpen` is set to _true_

**Comment by wetneb** [comment]
Thank you!

I still think this would be cleaner via `onsubmit`, so with jQuery's `submit()` function on the form element:
https://api.jquery.com/submit/

Have you tried it?

**Comment by Bhanu-mbvg** [comment]
Yes, @wetneb I tried that and on using the `onsubmit` the localhost page kept reloading and not show anything so chose to go with the pure Javascript approach.

**Comment by wetneb** [comment]
Thanks! I have changed it slightly to use `jQuery.submit`: that handles form submissions by click and Enter key in the same go. I had to make sure the submit button was in the form for that. Do you see any problem with this solution?

**Comment by Bhanu-mbvg** [comment]
The solution works fine just that we need to add a submit button inside form also one thing using jQuery increases the timespan for the login trigger.

**Comment by wetneb** [comment]
Ok! I think this is a bit safer than registering an event listener that stays registered even when the form is not there anymore.

**Pull request merged**
