### PR TITLE
enable spaces in data directory

### PR DESCRIPTION
**Pull request by Rots**
* pass options as proper bash list items so that even if directories
contain spaces, they will be properly passed on to java - #1623
* ignore empty options

### CODE REVIEW

**Comment by thadguidry** [comment]
hmm, this breaks it on Windows now.

**Comment by wetneb** [comment]
@thadguidry hang on, you are running the `refine` script on windows? Shouldn't you use `refine.bat` instead?

**Comment by thadguidry** [comment]
I am using `refine.bat` on Windows within a Windows Command Prompt.  Using this as a test...
`C:\Users\THAD\OpenRefine>refine /d "C:\Users\THAD\test Workspace A"`

but my old workspace still shows up in Refine.

**Comment by Rots** [comment]
Does `.bat` file need to be adjusted as well? I don't have Windows to test, sorry.

**Comment by wetneb** [comment]
@thadguidry right, so this PR did not touch `refine.bat` at all, so the problem should not be new (we can reopen the corresponding issue if this is still a problem on windows).

**Comment by thadguidry** [comment]
@wetneb it is not a feature of the `refine.bat` that I personally use.  I was just testing it out.  Sure, you guys can open an issue for the `refine.bat` to fix the /d option not working as it does on Mac/Linux.  Up to you guys, but it doesn't affect me as I said since I personally don't use that `/d` option on Windows, but others might want to see it fixed.

**Comment by wetneb** [comment]
If anyone knows batch files and wants to work on that great. This does not seem like a huge priority as I expect most Windows users use our `.exe` releases (whereas the `refine` script is the default for Linux users). But of course it would always be good to have.

**Pull request merged**
