### PR TITLE
Added SQLite support

### PR DESCRIPTION
**Pull request by mrcsparker**
* Added SQLite support
* Fixed database import javascript code that was sending a null value

This module uses the following values when connecting to SQLite:

_Database_: location of sqlite file

### CODE REVIEW

**Comment by thadguidry** [comment]
OMG ! Thank you so much for this Chris !

**Comment by wetneb** [comment]
Very nice! It looks like the JDBC driver is missing - you probably just need to add the corresponding dependency to `extensions/database/pom.xml`.

**Comment by mrcsparker** [comment]
@wetneb I missed the updated pom file. Just added

**Comment by wetneb** [comment]
Thanks! Now it looks like tests do not pass on Windows (via Appveyor). See this build:
https://ci.appveyor.com/project/openrefine/openrefine/builds/30973735

**Comment by mrcsparker** [comment]
@wetneb Fixed and rebased

**Comment by tfmorris** [comment]
Thanks for the PR. This fixes #2281. This also adds the feature requested in #1951. In the future, let's separate bug fixes from features and also include references to the open issues that are addressed.

**Pull request merged**
