### PR TITLE
chore: Cleanup sorting controllers

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: kushthedude <kushthedude@gmail.com>
- We are not using sortingControllers in View-Panel Header.

### CODE REVIEW

**Comment by kushthedude** [comment]
I double checked it, there is no use for this neither the UI is rendered
for this.

**Comment by wetneb** [comment]
Click on any column, and sort it by any criterion. This works on the master branch and breaks with your change.

**Comment by kushthedude** [comment]
I didnt know we had sort on click too.

**Comment by wetneb** [comment]
I am not sure how you double checked that this was dead code but please use a different method in the future.

**Comment by kushthedude** [comment]
> I am not sure how you double checked that this was dead code but please use a different method in the future.

@wetneb I overlooked the following conditional 
```js 
if (this._sorting.criteria.length > 0) {		
     this._renderSortingControls(elmts.sortingControls);		
   }
``` 
& presumed there was no call to renderSortingControls. Hence made the PR.

**Pull request closed without merging**
