### PR TITLE
feat: add firefox for ui_tests

### LINKED ISSUE #3367: Having UX tests running on Firefox
Tests are broken on Firefox
Basically the browser get stuck and the requests are not even hitting OpenRefine.

### Proposed solution

In case backend API calls are causing the bug : Move them to a Cypress plugin, so node will take care of the API calls, and not the browser itself

Try with Firefox developer edition

### Alternatives considered

Escalate to Cypress support

### Additional context

Problem has been detected on Travis and local (Macos)
Firefox support is relatively new for Cypress

### PR DESCRIPTION
**Pull request by kushthedude**
fixes #3367

### CODE REVIEW

**Comment by kushthedude** [comment]
@wetneb 
Setting MOZ_FORCE_DISABLE_E10S=1 env variable solves the issue, this disables the multiprocess mode in Firefox which was making the tests stuck on cypress. This is a known issue in cypress https://github.com/cypress-io/cypress/issues/6449

**Comment by thadguidry** [comment]
> @wetneb
> Setting MOZ_FORCE_DISABLE_E10S=1 env variable solves the issue, this disables the multiprocess mode in Firefox which was making the tests stuck on cypress. This is a known issue in cypress [cypress-io/cypress#6449](https://github.com/cypress-io/cypress/issues/6449)

Actually, that's a workaround because Cypress doesn't quite do all the things it should for Firefox and using Marionette more fully.

> Marionette provides an asynchronous, parallel pipelining user-facing interface. Message sequencing limits chances of payload race conditions and provides a uniform way in which payloads are serialized.

If anyone had more time, the way to help with these issues is to help Cypress code development with Marionette in various areas such as:
https://github.com/cypress-io/cypress/pull/1359/files#diff-f6e2b0467cc6d86d8281fc4f0dcae07f8c357d2ee7897b8a1059eb6c75e0af7b

More Info https://www.browserstack.com/guide/geckodriver-vs-marionette

**Comment by kushthedude** [comment]
@fgiroud Tests are passing on local too with firefox;
here are logs
```sh
    /Volumes/T/c/OpenRefine/m/te/cypress    kushthedude-patch-1  yarn run cypress run --browser firefox --headless --quiet
yarn run v1.22.4
$ /Volumes/T7/code/OpenRefine/main/tests/cypress/node_modules/.bin/cypress run --browser firefox --headless --quiet


  cypress/integration/language/change_language.spec.js
    ✓ Check elements on the langage page (1540ms)


  1 passing (3s)



  cypress/integration/preferences/change_preference.spec.js
    ✓ Edit a preference (2154ms)
    ✓ Add a new preference (1942ms)


  2 passing (5s)



  cypress/integration/project_management/create_project.spec.js
    ✓ Test the create project page (2792ms)
    ✓ Test project naming (5498ms)
    ✓ Test project tagging (7205ms)
    ✓ E2E, Creates a simple project, based on a CSV (4584ms)


  4 passing (21s)



  cypress/integration/project_management/export_project.spec.js
    ✓ Export a project (1455ms)


  1 passing (3s)



  cypress/integration/project_management/import_project.spec.js
    ✓ Check the layout for importing a project (1365ms)
    ✓ Import a project (2368ms)
    ✓ Import a project, test the renaming (2698ms)


  3 passing (8s)



  cypress/integration/project_management/list_projects.spec.js
    ✓ List an existing project, ensure a newly created project is displayed (1424ms)
    ✓ Visit a project from the Open project page, ensure link is working (1919ms)


  2 passing (5s)



  cypress/integration/project_management/open_project.spec.js
    ✓ Open an existing project by visiting the URL directly (968ms)


  1 passing (2s)



  cypress/integration/project/edit/edit_cells.spec.js
    ✓ Ensure the Edit button is visible on mouse over a cell (1226ms)
    ✓ Ensure the Edit button opens a popup (1215ms)
    ✓ Test a simple edit (1490ms)
    ✓ Test a simple edit, using keyboard shortcut (1666ms)
    ✓ Test the cancel button (1503ms)
    ✓ Test the cancel button, using keyboard shortcut (1485ms)
    ✓ Test edit all identical cells (1450ms)
    (Attempt 1 of 3) Test edit all identical cells, using the shortcut
    ✓ Test edit all identical cells, using the shortcut (1743ms)


  8 passing (1m)

(node:21301) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:21301) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit


  cypress/integration/project/facets/facets.numeric.spec.js
    ✓ A numeric facet must be casted first (1670ms)
    (Attempt 1 of 3) Changing the type of the column for numeric
    ✓ Changing the type of the column for numeric (2553ms)


  2 passing (1m)

(node:21339) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)


  cypress/integration/project/facets/facets.spec.js
    ✓ Test the facets text (no facets yet) (1990ms)
    ✓ Create a simple text facet (2784ms)
    ✓ Create a facet, Sort by count (2421ms)
    ✓ Create a facet, Sort by count, then by name (6716ms)
    ✓ Test the display of multiple facets (2576ms)
    ✓ Test editing a facet (2191ms)
    ✓ Test editing a facet / Preview (2168ms)
    ✓ Test editing a facet / History (1859ms)
    ✓ Test editing a facet / Starred (2028ms)
    ✓ Test editing a facet / Help (2072ms)


  10 passing (29s)

(node:21301) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 capture:video:frames listeners added to [Project]. Use emitter.setMaxListeners() to increase limit


  cypress/integration/project/sorting/sorting.spec.js
    (Attempt 1 of 3) Perform a basic sort
    ✓ Perform a basic sort (1500ms)
    ✓ Perform a basic sort + Reverse (1436ms)
    ✓ Perform a basic sort + Remove Sort (1643ms)


  3 passing (12s)



  cypress/integration/project/undo_redo/apply.spec.js
    ✓ Apply a JSON (2786ms)


  1 passing (4s)



  cypress/integration/project/undo_redo/extract.spec.js
    ✓ Test select/unselect all (3585ms)
    ✓ Test select/unselect individual entries (2710ms)
    ✓ Test the close button (2377ms)
    ✓ Ensure action are recorded in the extract panel (2072ms)


  4 passing (12s)



  cypress/integration/project/undo_redo/undo_redo.spec.js
    ✓ Ensure the Undo button is visible after deleting a column (1468ms)
    ✓ Ensure the Undo button is effectively working (1764ms)
    ✓ Delete 3 columns, then successively undo and redo the modifications using the Undo/Redo panel (2738ms)


  3 passing (7s)

✨  Done in 339.42s.
```

**Comment by wetneb** [comment]
For me the priority is that tests pass reliably, to avoid a flaky CI. At the moment, tests on Chrome seem to fail quite often, like this:
https://github.com/OpenRefine/OpenRefine/runs/1775260191?check_suite_focus=true
So I am slightly worried that if we add too many browsers we'll make it even more likely that things break down.

The [current market share for desktop web browsers](https://gs.statcounter.com/browser-market-share/desktop/worldwide) seems to be:
* 65.96% for Chrome
* 10.43% for Safari
* 8.39% for Firefox

So we should definitely test on Chrome, then Firefox or Safari. I think we might be able to remove Edge (although tests seem to be more reliably passing than on Chrome sadly).

**Comment by kushthedude** [comment]
The current flaky tests in chrome is an issue with Cypress latest version,
there is already an issue opened in the upstream. Let's see if cypress guys
gives any workaround or fix for this.

**Comment by fgiroud** [comment]
Yes, tests are flaky, i've opened #3509, and following-up with Cypress community

**Comment by wetneb** [comment]
@kushthedude @fgiroud it's not clear to me what is the status of this PR - do you know if this has been fixed in Cypress?

**Comment by kushthedude** [comment]
It has been fixed in cypress. This PR was ready to merge but we decided to
put it on hold until we have fixed more flakes. @fgiroud is it good to move
ahead with this now?

**Comment by wetneb** [comment]
I agree that stability of the build is the priority here.

**Comment by fgiroud** [comment]
Unfortunately, it looks like Firefox usage doesn't stop decreasing. 10% now
https://gs.statcounter.com/browser-market-share/desktop/worldwide

Shall we support it?
Maybe @thadguidry also have an opinion about if we should test on Firefox

**Comment by thadguidry** [comment]
I absolutely think we should support Firefox.  It is the only purely **free** browser now on the market.

**Comment by kushthedude** [comment]
Should we go on to merge this then? I have updated the branch and resolved
conflicts.

**Comment by thadguidry** [comment]
@kushthedude I have not tested this commit.  Have either of you?  If you did and you are satisfied that it:
1. fixes the ui_tests with our current Cypress version we are using.
2. doesn't break our build

Then I think we can merge this.

**Comment by kushthedude** [comment]
Yes I did test again locally with cypress on my machine. Due to the
boundations of pullrequesttarget, we cant do test on ci unless merged.

**Review by fgiroud — APPROVED** [review]

**Pull request merged**
