### PR TITLE
fixes ui of scatterplot-facet and dialog ,fix for issue #3228

### LINKED ISSUE #3228: Scatterplot facet UI regression
The UI of the scatterplot has got more ugly between 3.4 and the current development version.

### To Reproduce
Steps to reproduce the behavior: create any scatterplot facet.

### Current Results (master)

image

### Expected Behavior (3.4)

image

### Versions
 - Operating System: Linux
 - Browser Version: Firefox 68
 - JRE or JDK Version: 11

### PR DESCRIPTION
**Pull request by rachittiwari8562**
The bug is due to the jquery-ui widget function checkboxradio() which was adding icon to the input field.
Fix :
To override this a class "no-icon" is applied to individual input (radio) button on which we use checkbox("option","icon","false") to remove the icons.
Also added some css modification in the main/webapp/modules/core/styles/project/facets.less file.

Fixes #3228

### CODE REVIEW

**Comment by rachittiwari8562** [comment]
Can someone point out why i am getting these these errors as these are nowhere related to any of the openrefine-docs .Please review it..

**Comment by wetneb** [comment]
Sorry I'll get these fixed!

**Comment by tfmorris** [comment]
Thanks for the PR! I'll try to review it tonight (~12 hrs)

>

**Comment by wetneb** [comment]
@rachittiwari8562 the problem should go away if you rebase your branch on `origin/master`. By the way, we recommend that you do not use the master branch of your fork to submit pull requests, but rather a specific branch for each pull request.

**Comment by rachittiwari8562** [comment]
Should i submit another pull request after rebasing my branch.Or this branch can be merged?

**Comment by wetneb** [comment]
You should be able to keep this pull request open and rebase your own master branch on top of our master branch.

**Comment by rachittiwari8562** [comment]
Is something wrong or missing in this pull request??

**Comment by wetneb** [comment]
@rachittiwari8562 let's leave @tfmorris some more time to have a look at this since he has been following the issue closer than I have.

**Review by tfmorris — APPROVED** [review]
LGTM. Thanks for the contribution!

The rotation buttons aren't working, but I consider that a separate bug. All the cosmetic issues appear to be fixed.

**Comment by tfmorris** [comment]
Sorry for the delay in getting this review. It doesn't mean that we don't appreciate your contribution. We do!

For future pull requests, please:
* create separate branch, rather than using `master`, as suggested by @wetneb 
* include the phrase "fixes #3228" (or whatever the original issue number is) so that the PR and issue will be linked together and the issue will automatically get closed when the PR is merged.

Thanks again!

**Pull request merged**
