### PR TITLE
Cell split regex

### PR DESCRIPTION
**Pull request by ostephens**
Added options to split multi-valued cells using a regular expression as the separator, or to split by lengths as per #1268

### CODE REVIEW

**Comment by wetneb** [comment]
@ostephens would it make sense to add a few unit tests for this feature?

**Comment by ostephens** [comment]
@wetneb probably a good idea, but writing tests isn't something I've done much, and not in Java or OR at all. I tried to look for tests for similar bits of functionality (e.g. split into multiple cols) but couldn't see any.

Any examples or pointers to get me started?

**Comment by wetneb** [comment]
@ostephens here is an example: https://github.com/OpenRefine/OpenRefine/blob/820b6f395ad37c52d5fc091fc4642d1d72ccf780/main/tests/server/src/com/google/refine/tests/model/UrlFetchingTests.java

Let me know if I can help to clarify anything!

**Comment by ostephens** [comment]
@wetneb I've written some tests - although now waiting for some feedback on desired behaviour as my test raised a question (which is good - my test failed in an interesting way :). Just a quick question - in terms of which directory the test should live in - I notice that KeyValueColumnizeTests is in  /tests/model - is there any reason why? I would have expected these to go under /tests/operations or similar, but that doesn't seem to exist?

**Comment by wetneb** [comment]
@ostephens Yes I completely agree with you, this is a mess. Feel free to reorganize as you wish.

**Comment by ostephens** [comment]
@wetneb I'm seeing codacy issues relating to the naming of methods in the tests I've written. I followed existing tests for these methods - can I ignore these, or should I be fixing?

**Comment by wetneb** [comment]
@ostephens yes we can ignore them. @thadguidry could you disable them please?

**Comment by ostephens** [comment]
@wetneb thanks! OK - I think I've done everything to get this ready for merging - as long as you are happy!

**Comment by thadguidry** [comment]
@wetneb @ostephens @jackyq2015 I'd rather not disable that particular PMD rule... its a fairly best practice : Method names should always begin with a lower case character, and should not contain underscores.

I understand that our current quality with existing code / tests is lackluster and violates many of the quality rules in Codacy, but that is also something that each one of us can take responsibility towards and begin cleaning up as we touch our aging code base.

When time is of the essence... ignore...but then clean up later as we can.  It helps other contributors coming into the project to see understandable clean best practice syntax :)

**Comment by wetneb** [comment]
@thadguidry if you want to keep that then I'll just vote for getting rid of Coveralls integration altogether… It really clutters PRs with a lot of useless stuff. If you like going to coveralls itself, fine, just let's disable the GitHub integration so that we can work of PRs in peace.

**Comment by thadguidry** [comment]
@weblate Coveralls ? or you meant Codacy right ?

**Comment by wetneb** [comment]
@thadguidry Yes sorry! And we can replace Codacy by Coveralls, it's much cleaner in PRs.

**Comment by thadguidry** [comment]
@weblate Coveralls is cleaner because Checkstyle is OFF by default.  So perhaps your asking to just turn off Checkstyle... that I can agree on I guess... we (the other devs that care about this) can always work on style improvements on as needed basis directly with Codacy analysis through their site itself https://www.codacy.com/app/OpenRefine/OpenRefine/dashboard 

Turning off Checkstyle now in Codacy ...

**Comment by thadguidry** [comment]
@weblate OK, I've turned off all the "non-sensical" style checks.  There might be more within PMD that might cause you some grief... just let me know on those as they come up.

**Comment by thadguidry** [comment]
@weblate actually, even better I think for everyone, I turned off the Pull Request Commenting from Codacy... it should only now provide the summary checking and then you can click on Details to see more.

**Pull request merged**
