### PR TITLE
Prevent XML importer from creating many empty lines (#1095)

### LINKED ISSUE #1095: Open XML file from URL generates lots of empty lines
In the 2.6RC2 installed on Linux from https://github.com/OpenRefine/OpenRefine/releases/download/2.6-rc.2 I get blank lines displayed when importing XML from a URL.

eg importing XML from  http://api.worldbank.org/countries/all/indicators/SP.POP.TOTL?date=2000:2001

image

Empty lines:

image

If the parsing of this can't be fixed, an `ignore empty rows` setting would be useful?

### PR DESCRIPTION
**Pull request by Nishtha3512**
Closes #1095
After reading the comments on issue #1095  i tried to resolve.
Now,there is no need to uncheck "preserve empty strings" and check "Trim leading & trailing whitespace from strings" While importing XML file. 
Please review it and let me know if i have done any mistake :)

### CODE REVIEW

**Comment by thadguidry** [comment]
@Nishtha3512 Thanks!  Can you also supply some test cases?

**Comment by Nishtha3512** [comment]
@thadguidry  You mean Screenshots of issue which i has fixed?

**Comment by wetneb** [comment]
No, we mean Java unit/integration tests ensuring the importer works as expected. You can find existing ones for the XML importer in `main/tests/server/src/com/google/refine/importers/XmlImporterTests.java`. You could add another test method there, with an example dataset which would demonstrate the issue.

**Comment by Nishtha3512** [comment]
Ohk I will.

**Comment by wetneb** [comment]
Marking as draft until the tests are included

**Comment by tfmorris** [comment]
I'm going to close this since there hasn't been any progress in two months, but please feel free to reopen it if you are able to add some tests. Thank you for working on it.

**Pull request closed without merging**
