### PR TITLE
fixes #3172 Reconcile > Use values as identifiers" does not reconcile #4655

### LINKED ISSUE #3172: "Reconcile > Use values as identifiers" does not reconcile
### To Reproduce
Run "Reconcile" > "Use values as identifiers" on any column, whether it contains properly-formatted unique IDs for the given service or not. You will see that it seems not to reconcile at all - it only says, whatever your cell contents are, it's 100% matched and generates a real-looking URL, whether or not that URL will resolve. 

### Expected Behavior
Reconciliation seems to be missing the part where it actually validates these unique IDs to see if they match up with existing entities. I expect failures to say so. 

### Screenshots
error1

I tested on Wikidata and VIAF. VIAF gives no hover-information, the matches just send you to 404s, e.g. http://viaf.org/viaf/Q17291. None of the content in that VIAF column should be matching (Q### is an invalid format) except that first value, which resolves correctly to https://viaf.org/viaf/38242123/.  

There are two things happening on Wikidata that I thought I'd mention - IDs that don't exist give the error in the above screenshot. IDs that seem to exist but have yet to be assigned (something that fits the Q### format) look a bit different (so that may be a second bug to work out). I would expect these to have some other kind of obvious error message or flag. 
error2

### Versions
Windows, Firefox
 - OpenRefine: the new 3.4 release, as well as 3.4 beta 2 (last week)

### PR DESCRIPTION
**Pull request by WaltonG**
Fixes #{3172}
Notice added when selecting service

### CODE REVIEW

**Comment by WaltonG** [comment]
@wetneb I submitted anew pull request https://github.com/OpenRefine/OpenRefine/pull/4664 but more files are being added.
This is what I did
1.Forked the repository
2. Built the repository-This is when the files were introduced via npm install. 
3. Made a commit with message First build.
4. Created a branch to work on the issue , made a commit and pushed to origin.

Thats when the pull request was opened but it included the files from the first commit

**Comment by wetneb** [comment]
When you make your commit, you should have an option to select which files to add to your commit. You should only add those which are relevant to your pull request. If you are using git from the command line, then the relevant step is when you do `git add`. You should only run this command on the files that you actually want to update in your pull request.

**Comment by wetneb** [comment]
Another small detail: in your pull request description, you can write "fixes #3172" rather than "fixes #{3172}" so that GitHub recognizes it as an issue number.

**Comment by WaltonG** [comment]
Thank you for the clarification. I have always been using git add . which happens to add all the files. I guess I'll have to submit another pull request

**Pull request closed without merging**
