### PR TITLE
Fix issue #1509

### PR DESCRIPTION
**Pull request by jackyq2015**

### CODE REVIEW

**Comment by thadguidry** [comment]
@jackyq2015 this will fix for any importer ?

**Comment by jackyq2015** [comment]
This is not to do with the actual memory the data set consumed. It will only take 100 rows as the sample to infer the type. After that it will be gced. 

@thadguidry It will apply to all importers.

**Comment by wetneb** [comment]
Oh okay - I had not noticed the copying indeed. So I think this should solve this particular issue - but I am still worried about the overall instability brought by the Data Package PR. What is now clear is that it has introduced bugs that are unrelated to Data Packages.

The risk is high that some of the bugs it has introduced have still not been discovered and could make it into the next release. I tried my best to scrutinize the PR but it was very hard given its poor state. The fact that we have serialization issues is serious - potentially, that could lead to corrupting users' projects and losing data. This is a high risk to pay for a feature that will go mostly unnoticed given the lack of integration in the UI.

**Comment by thadguidry** [comment]
@wetneb Besides reverting the PR... what are you proposing to improve the PR ? More tests ?  An alternate form of testing this somehow or seeing the impacts ?  How can we bring confidence to the importers and Data Package / Metadata enhancements ?

**Comment by wetneb** [comment]
* Each update of dependency should be made in its own PR, explaining why the update is needed and assessing how the library is currently used in the code. It does not need to be extremely detailed, of course: it's just about assessing what are the sort of changes made in the library (any breaking ones) and see what sort of risk it implies for us. For instance, when we updated Jython it was fairly clear that we were touching a fairly well isolated part of the code base, and we saw that their new release included mostly bug fixes, so that's good. It's just an analysis that needs to be done.
* No dead code should be introduced - currently there are loads of constraint checkers that are not exposed at all in the UI: it's much safer just not to include them at all.
* iIf the Data Package library we rely on is not quite ripe yet, fix it. Yes, that takes time, but it's necessary to avoid ugly hacks like the use of reflection to handle datatypes.
* More unit testing. A lot more.
* Commits should reflect logical changes and have meaningful commit messages. That makes reviewing much easier: you can just look at each commit in order, understand its logic and assess it independently of the rest. It's impossible to do that if the PR is crippled with unrelated commits and merges: you have to review the final diff and it's much harder to spot problems.

Generally speaking, just pretending to do some quality software engineering…

**Comment by jackyq2015** [comment]
@wetneb It is interesting to see that you say it is not related to the data package.  It looks like you are the only guy who can do the quality software work in the world.  I am speechless at your attitude. that's all I can say.

**Comment by wetneb** [comment]
Well, it's related because it was introduced by your PR, but take the standpoint of a user: they just want to import an XML file and they don't care at all about Data Packages. These are two unrelated things for users. What I mean is that it is a lot more serious than any bug in the Data Package exporter for instance (which are not going to disturb any existing user workflow).

Sorry if it sounds like I am trying to teach you a lesson - I was just trying to give concrete points to @thadguidry. I am just trying to point out some elementary principles that could have helped avoid the critical bugs that you have introduced in OpenRefine. Bugs happen, it's a normal thing - but these ones are really serious and you are getting paid for this work. There is just a minimum quality standard that should be met.

I clearly have a lot to learn myself about good practices in software engineering - and I will soon submit a PR for the Wikidata package where your criticism will be valued. I am happy to skype today if you want to discuss things directly.

**Comment by thadguidry** [comment]
@jackyq2015 I don't think anyone is displaying an attitude.  Antonin is trying to help improve things and had legitimate concerns as did I, but most of those concerns are removed.  Let's not be too harsh, after all, its only the few of us that I can count on 1 hand. :) right ?  And thanks to both of you for even caring about this little project called OpenRefine that we all work so hard on !

OK, so, let's get to work as the awesome team we are ... we know we need to improve the tests here, around Project Creation and Importers... @jackyq2015 any other areas that you feel would help to assure quality in future PR's around Data Package and Metadata that you can think of ?  Also, Antonin brought up a good point about the Data Package java library...should we invest some time to help fix that up, anything within that concerned you while working with it Jacky ?

**Comment by jackyq2015** [comment]
The first thing I want to address is that this change is integral part of the data package change. It is NOT unrelated change. Since we need to apply the types infer defined by data package and that has to be done at the import stage. From the QA aspect, I agree we need more UT and that won't solve all the problem. That part of code  is covered by UT and not that that similar test data which can break it. For this particular case, I will write a UT to cover it.

**Comment by thadguidry** [comment]
@jackyq2015 Awesome, thanks Jacky. that will help.

**Comment by wetneb** [comment]
@jackyq2015 sorry yes, I should have made clear that I am actually more worried about the other issues #1517 and #1508 than this one…

And just to be clear: the tests that were already in place in OpenRefine are really sparse (the test coverage is so low!), so it really does not help us in our work… typically, this bug should have been caught by an existing test for the XML importer (one that you should not have needed to write)!

**Comment by jackyq2015** [comment]
@thadguidry The infer only impact the column model, the row model is impacted.

**Pull request merged**
