### PR TITLE
WIP - Adds new JavaFX launcher

### LINKED ISSUE #3221: Allow easier running, stopping, logging of OpenRefine
We want to make running and stopping easier for OpenRefine on Windows and Linux (we assume MacOS is good enough for now).

#### Windows
On Windows, allow running OpenRefine as a native application, possibly with tray icon support (without displaying the console by default).
- JAVA - The current supported and recommended community practice in **Java** world is to code a small **JavaFX** application.
- RUST - But we might also instead use an actual systems programming language like **Rust** with **Druid** or **Relm** ((see Alternatives below).

The MVP for the application would be:
1. The application window UI would have the following elements:
   - scrollable console text output (configurable line history display buffer with default at 3000)
   - File menu with options
     - **Exit** to ask a standard "Are you sure - OK/Cancel" and then gracefully shutdown OpenRefine and then the GUI app.
   - Close button (red X) on the GUI app would offer a confirmation dialog **Are you sure you wish to exit OpenRefine?**
   - Minimize/Maximize buttons
2. OPTIONAL - 
   - **Save Log** to allow saving the entire log output since beginning of application startup to a file
   - System Tray icon support
   - Right click on the System Tray gives only a single option **Exit OpenRefine**.
   - Double-click System Tray icon opens the application UI.
   - Toast notifications on Windows 10/11
    
#### Linux
**TODO:** On Linux, allow running OpenRefine as / with ???  

#### MacOS
Nothing to do ?

### Alternatives considering
1. @dante9992 also mentioned that [Tauri](https://github.com/tauri-apps/tauri) also supports [system tray icon on Windows](https://tauri.studio/en/docs/usage/guides/visual/system-tray) and can do app signing, self updating, toast notifications, etc.  It also allows the app to be packaged as a .deb (Debian package) file.  @thadguidry asked and paid for the Tauri team (see comments below) to put together a prototype with Tauri and Rust with code now stored here:  https://github.com/OpenRefine/openrefine-tauri

2. @timClicks said to me on Discord that we could just use Rust and [Druid](https://github.com/linebender/druid/tree/master/druid) or maybe [Relm](https://github.com/antoyo/relm)

3. some very hacky Launch4j opensource wrappers that are not 100% ideally compatible with Windows 10. (they were mostly coded and made for pre Win8.1 OS and no longer sufficient)

4. Electron - has some non-free issues (see [comment](https://github.com/OpenRefine/OpenRefine/issues/3221#issuecomment-867067089) below)

### Additional context
------
#### JAVA

~From what I read so far, not entirely sure if AWT is really needed for SystemTray support (it was in JavaFX 8).  Newer OpenJFX 11 or 15 might not need AWT at all, dunno.  But just in case, here's some good info I found about showing/hiding the application when clicking the systray icon
https://javafxpedia.com/en/knowledge-base/12571329/javafx-app-in-system-tray~

One of the nice things about using a library like FXTrayIcon below is that it hides AWT / Swing complexity, since AWT is still necessary for System tray support on OS's, unfortunately.

JavaFX might be a nice way to optionally allow running OpenRefine on all 3 OS's, Linux, MacOS, Windows.

[GlucoStatusFX](https://github.com/HanSolo/glucostatusfx) (which has nice source code to follow along) uses JavaFX and the [FXTrayIcon](https://github.com/dustinkredmond/FXTrayIcon) library which allows it to run the application in the system tray of Windows and MacOS. The system tray feature, however, doesn’t work on all Linux distributions. In that case, the application is available through the dock.  Which is likely a perfect balance for our Linux users.

Oracle provides a very useful guide for Self -Contained Application Packaging that covers Windows, Linux, Mac
https://docs.oracle.com/javase/10/deploy/self-contained-application-packaging.htm
[OpenJFX](https://openjfx.io/) has wide community support now and can be utilized to code a small JavaFX application that runs OpenRefine from a system tray utilizing a library like [FXTrayIcon](https://github.com/dustinkredmond/FXTrayIcon).
OpenJFX Intro:  https://openjfx.io/openjfx-docs/#introduction
OpenJFX Wiki:  https://wiki.openjdk.java.net/display/OpenJFX/Main

------
#### RUST

Even though Rust provides a way to handle system tray and a WebView, it's likely much more approachable for our existing contributors & core team to instead leverage JavaFX which can also use WebView and all the bells and whistles such as CSS, Canvas, etc.  Still, below are some Rust references for the daring:

##### Iced 
https://github.com/hecrj/iced

##### Druid
https://raphlinus.github.io/rust/druid/2020/09/28/rust-2021.html
https://github.com/linebender/druid/tree/master/druid
https://linebender.org/druid/
https://docs.rs/druid/0.7.0/druid/

##### Relm
https://github.com/antoyo/relm

##### Tauri
https://tauri.studio/en/
https://github.com/tauri-apps/tauri
https://tauri.studio/en/docs/usage/guides/visual/system-tray

------

### PR DESCRIPTION
**Pull request by thadguidry**
Fixes #3221

DRAFT - Work In Progress
- initial module that can be run independently.

TODO:
- [X] make start button launch main app
- [X] stop
- [X] close X should confirm with verify message "ARE YOU SURE?  Yes/No"
- [ ] views:
  - [X] logging (works minimally - but no Copy or Save button yet) - not even sure if we want logs written to disk as check box option?
  - [ ] JVM details?
  - [ ] JVM memory?

### CODE REVIEW

**Comment by thadguidry** [comment]
Hi @tfmorris Any idea why I'm having so much difficulting on this PR with the linting and why it's so painful?  Maybe because I am on Windows? 
1. I've already changed the line endings to LF in my IntelliJ IDE, and the `./refine lint` command does the same thing as
2. I tried:  `mvn formatter:format impsort:sort`
and I get no failures:

```
[INFO] ----------------------< org.openrefine:launcher >-----------------------
[INFO] Building launcher 3.9-SNAPSHOT                                   [12/12]
[INFO]   from launcher\pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- formatter:2.24.1:format (default-cli) @ launcher ---
[INFO] Processed 3 files in 283ms (Formatted: 0, Skipped: 3, Unchanged: 0, Failed: 0, Readonly: 0)
[INFO]
[INFO] --- impsort:1.9.0:sort (default-cli) @ launcher ---
[INFO] Processed 3 files in 00:00.002 (Already Sorted: 3, Needed Sorting: 0)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OpenRefine 3.9-SNAPSHOT:
[INFO]
[INFO] OpenRefine ......................................... SUCCESS [  0.505 s]
[INFO] OpenRefine - main .................................. SUCCESS [  1.438 s]
[INFO] OpenRefine - server ................................ SUCCESS [  0.049 s]
[INFO] OpenRefine - extensions ............................ SUCCESS [  0.007 s]
[INFO] OpenRefine - Jython extension ...................... SUCCESS [  0.045 s]
[INFO] OpenRefine - Wikibase extension .................... SUCCESS [  0.348 s]
[INFO] OpenRefine - Database extension .................... SUCCESS [  0.097 s]
[INFO] OpenRefine - Gdata extension ....................... SUCCESS [  0.038 s]
[INFO] OpenRefine - PC-axis extension ..................... SUCCESS [  0.027 s]
[INFO] OpenRefine - packaging ............................. SUCCESS [  0.040 s]
[INFO] OpenRefine Java JMH benchmarks ..................... SUCCESS [  0.023 s]
[INFO] launcher ........................................... SUCCESS [  0.559 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.353 s
[INFO] Finished at: 2024-08-18T17:50:25+08:00
[INFO] ------------------------------------------------------------------------
```

What shall I do ?  Kill the PR and then perhaps push with a new one?  I'm open to any suggestions to more easily remedy this.

**Comment by tfmorris** [comment]
@thadguidry sorry I missed your earlier ping. Since I don't know anything about JavaFX, I hadn't even looked at this PR.

The problem that you're running into was introduced back in 2018. I don't understand why the change was made, but I've created #6841 to fix it and put it back the way it was. With the current setup anyone attempting to develop on Windows is going to have great difficulty.

**Comment by thadguidry** [comment]
Ok then I will force LF endings which actually should be our default since Windows IDEs can handle this now.

I think most other open source projects do that.

**Comment by thadguidry** [comment]
Moving to new branch and PR

**Pull request closed without merging**
