### PR TITLE
Fix Uncaught RangeError when using Cell Edit button to change String to Date data type.

### LINKED ISSUE #6534: Using Cell Edit button to change String to Date data type gives Uncaught RangeError
Console error when changing a cells data type from Text to Date via Cell Edit button.

### To Reproduce
1. First, click Edit Cell and type in a String such "2023-12-01" and click Apply button
2. Then, .click on Edit Cell and choose from it's dropdown to change to `Data type: date`
3. Finally, click Apply button

### Current Results

1. The console immediately shows the following error (No Java stacktrace shows in Terminal log however):

```
project-bundle.js:46913  Uncaught RangeError: toString() radix argument must be between 2 and 36
    at Number.toString (<anonymous>)
    at HTMLButtonElement.commit (project-bundle.js:46913:21)
    at HTMLButtonElement.dispatch (project-bundle.js:5147:27)
    at elemData.handle (project-bundle.js:4951:28)
```
as shown:
image    

2. If I try to use a partial format in the cell value, then I get a popup alert for "not a valid date." as shown:

image

3. If I try to use the full format as is recommended above the Cell Edit dialog, then I get the previous Console error as shown:

image

### Expected Behavior
The cells' String value is converted to Date data type when the correct format is used.
I assume that when following the Steps to Reproduce, that a cell text value of "2023-12-01" would be good enough to convert to the Date data type?
But no format seems to be working.

If I use Edit Cell -> Common Transform -> to Date , then that method does seem to be working however.
So the issue is just likely somewhere in the Edit button on a Cell and perhaps the Javascript function or callbacks? 

### Versions
 - Operating System: Windows 11
 - Browser Version: Edge Latest
 - JRE or JDK Version: JDK 21
 - OpenRefine: 4.0 Snapshot

### PR DESCRIPTION
**Pull request by GittyHarsha**
Fixes #6534 

## Issue
The date entered in the cell is parsed using the `Date.parse()` method which returns a timestamp. This timestamp is converted to a formatted date string using `toString("YYYY-MM-DDTHH:mm:ss.sssZ")`.

but concerning the below link
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_radix

The `toString` method has an optional parameter radix, which should be an integer between 2 and 36. But here the radix is given a string as an argument.

## Changes proposed in this pull request:
- use `toISOString` method on a new Date object constructed using the parsed date value.

image

### CODE REVIEW

**Review by tfmorris — COMMENTED** [review]
Thanks for the contribution! Any chance you could add a Cypress test to make sure that we don't break this in the future?

Also, it's helpful if you can make the pull request title and commit message a little more descriptive so that they stand alone without having to refer to github.

**Comment by tfmorris** [comment]
I think here is where the test could go: https://github.com/OpenRefine/OpenRefine/blob/master/main/tests/cypress/cypress/e2e/project/grid/row/edit_cells.cy.js

**Comment by GittyHarsha** [comment]
Sure! I'll look into it

**Comment by GittyHarsha** [comment]
@tfmorris I added a test case. Should I add more to test any other scenarios?

**Comment by GittyHarsha** [comment]
@tfmorris I added a test case that simulates editing a cell to "2024-12-12" and changing the data type to date.
Should I add test cases for any other scenarios?

**Review by tfmorris — APPROVED** [review]
Awesome. Thanks for the test coverage!

**Comment by GittyHarsha** [comment]
Thanks!

**Pull request merged**
