### PR TITLE
Change static final private to Private static final

### PR DESCRIPTION
**Pull request by sherrif10**
Fixes [#{issue number here}](4808)

Issue  https://github.com/OpenRefine/OpenRefine/issues/4808

Changes proposed in this pull request:
- We can configure use of any specific linters for tracking these improvements. Could we use this as a starting point for using linters in this code base cc @antoine2711  @wetneb 

YOu can only see these issue by configuring any linter in IDE Forexample  linter in vscode
- 
-

### CODE REVIEW

**Comment by antoine2711** [comment]
If you want to move forward now with this issue, the first phase will really be some documentation. Here some ideas of what could be put in it:
- What rules would be enforced
- What changes to the code would that imply
- Our would it affect code comparaison between code revisions?
- What OS setup would have problem installing a compatible linter tool?
- Do a test yourself on the 3 platforms, or at least 2
- ...

The point of this is to mesure the impact such a change will have on the community and the developers. This should always be your main concern (with the users, of course), and it this case, it is a critical change with many implications.

Regards, Antoine

**Comment by sherrif10** [comment]
Thanks fo the detailed explanation. This is how we should handle this. Probably will add bit of documents thats regards to this work.

**Comment by AtesComp** [comment]
See my comment in issue #4808.

**Comment by wetneb** [comment]
Closing per https://github.com/OpenRefine/OpenRefine/pull/4844#issuecomment-1137442589

**Pull request closed without merging**
