### PR TITLE
Add Netlify logo to Footer

### PR DESCRIPTION
**Pull request by thadguidry**

### CODE REVIEW

**Comment by wetneb** [comment]
I would try to keep things minimal, but if they complain that the current acknowledgement is too minimal, we can add that I guess.

**Comment by thadguidry** [comment]
Yeap, exactly what I was thinking... I just got this from what others asked in the Community Forums and what they replied with.  We'll see what Netlify responds with to our Open Source Application.

**Comment by thadguidry** [comment]
OK, Joe @ CS&S found their [Open Source Plan Policy](https://www.netlify.com/legal/open-source-policy/) that states our options:

Must feature a link to our service on your main page, or all internal pages. You have two options:
 
1.  We have [premade badges](https://www.netlify.com/press/#badges) for your convenience, or
2. You may create your own link, which should read “This site is powered by Netlify”, and include a link back to our home page.

**Comment by wetneb** [comment]
Not needed, our application was accepted as such.

**Pull request closed without merging**
