### PR TITLE
WIP: Move to jquery.i18n (from wikipedia)

### LINKED ISSUE #1279: Use best practices in i18n
I applaud your attempt at internationalizing OpenRefine, however you did not read the manual. As you know other languages have their own grammar and using the English grammar on all languages is obviously not going to work:

https://github.com/OpenRefine/OpenRefine/blob/e5fdf48680a6f810c84706671344dc93d9a4fb75/main/webapp/modules/core/scripts/dialogs/clustering-dialog.js#L245

The jquery.i18n library has a lot of awesome features inherited from gettext such as string interpolation (and even custom plurals). This is not the only location in the code where messages are made up from pieces using concatenation, please use interpolation instead so that languages that use a different word order don't look broken.

Other example:

https://github.com/OpenRefine/OpenRefine/blob/e5fdf48680a6f810c84706671344dc93d9a4fb75/main/webapp/modules/core/scripts/preferences.js#L86

Please just use a construct like:

```javascript
if (window.confirm($.i18n('confirm-delete-key', key))) { 
```

It also seems that you added sections in your translation JSON, placing JSON objects where messages should be, which is probably going to break all the machinery (and is responsible for the awkward `i18n(...)[...]`). Please read library's manuals or at least [their repository's README before proceeding](https://github.com/wikimedia/jquery.i18n#message-format).

### PR DESCRIPTION
**Pull request by remram44**
This attempts to move to [wikipedia's jquery.i18n](https://github.com/wikimedia/jquery.i18n) so we can use modern features such as interpolation and plurals.

Currently WIP, don't merge.

Fixes #1279

### CODE REVIEW

**Comment by remram44** [comment]
It works, but I haven't gone over the extensions. In particular, do we want some kind of namespacing for the string IDs? Such as `core-discard`, `gdata-discard`, etc.

**Comment by remram44** [comment]
Can someone configure @codacy-bot to ignore external libs?

**Comment by thadguidry** [comment]
@remram44 yeah, on it now :)  5 mins :)

**Comment by thadguidry** [comment]
@remram44 Ignored all under /main/webapp/modules/core/externals/

**Comment by wetneb** [comment]
@remram44 I think prefixing the string ids with the module name would make sense indeed!

**Comment by remram44** [comment]
I will do that then: `core-msg`, `gdata-msg`. Thanks!

**Comment by ostephens** [comment]
@remram44 Is there anything I can do to help progress this work?

**Comment by remram44** [comment]
I've been really busy but I'll come back to this soon! Sorry about the delay.

**Comment by ostephens** [comment]
@remram44 no problem at all! V grateful for your work - just shout if there is anything I can do to help

**Comment by thadguidry** [comment]
@remram44 Hey Remi ! Just checking in on your progress.

**Comment by remram44** [comment]
I can update this patch for current OpenRefine. Note that once this is merged, translation files will have to be updated.

**Comment by wetneb** [comment]
@remram44 that would be fantastic! But I was thinking, maybe it would be better to avoid collisions of translation strings, by adding the namespacing mentioned above?

`$.i18n._('core-dialogs')["content"]` -> `$.i18n._('core-dialogs_content')`

instead of

`$.i18n._('core-dialogs')["content"]` -> `$.i18n._('content')` which looks more risky (especially because we have extensions)!

Also given that we have had quite a lot of changes since this PR was started, it might be easier to restart it from the current master branch.

I can with any of this - you already made a great contribution by pointing us to the right library and good practices :)

**Comment by wetneb** [comment]
@remram44 As this PR is quite old now, I'm taking it over and restart it from the current master. I'll try to reuse your commits where possible to preserve attribution.

**Comment by remram44** [comment]
Thanks @wetneb! Sorry I couldn't find time to finish this!

**Pull request closed without merging**
