### PR TITLE
feat: move to em from pixels

### LINKED ISSUE #3476: Move away from px to em in docs styling
We are using pixels for styling in docs which is absolute and can't vary according to screen size.
### Proposed solution

Support use of em which is relative to the screen resolution you are viewing on.

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
fixes #3476

### CODE REVIEW

**Comment by kushthedude** [comment]
This is very close estimations of em to px considering base as our fonts size & I have checked each page for any irregularity, I didn't find any irregularity in the styles or text.

**Comment by wetneb** [comment]
I can find at least one irregularity:
image

(comparing https://deploy-preview-3477--openrefine-docs.netlify.app/manual/starting to https://docs.openrefine.org/manual/starting/)

**Comment by wetneb** [comment]
For me there is still a pretty big difference at the same place, between https://deploy-preview-3477--openrefine-docs.netlify.app/manual/starting/ and https://docs.openrefine.org/manual/starting/. Both on Firefox and Chromium.

**Comment by kushthedude** [comment]
@wetneb taken care of the spacing, please take a look again

**Review by wetneb — APPROVED** [review]

**Pull request merged**
