### PR TITLE
Update to docusaurus-2.0.0-alpha.64 to fix security vuln in dependency

### LINKED ISSUE #3031: Update docusaurus to more recent version to validate internal links
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
It would be nice if the Docusaurus build could fail when the docs contain broken internal links. This is enabled by default in more recents versions of Docusaurus v2:
https://v2.docusaurus.io/docs/docusaurus.config.js#onbrokenlinks

The feature should initially be disabled while @allanaaa writes up the missing pages.

**Describe alternatives you've considered**
We could also consider validating external links.

**Additional context**
Discussed during a documentation meeting

### PR DESCRIPTION
**Pull request by tfmorris**
Also update docusaurus config to match new version and fixed some broken links in the documentation, but not sure
if the latter were related to the version change.

Not really much of a risk since it's in only in our documentation build system, but this will let us getting rid of the annoying nag.

Fixes #3031

### CODE REVIEW

**Comment by tfmorris** [comment]
Hmmn, looks like my local dev environment isn't as picky as CI, so converting back to draft.

@allanaaa @ostephens I would welcome help migrating the doc sources to be compatible with the new version so that we can check the box on this security vulnerability.

**Comment by ostephens** [comment]
@tfmorris I think most of the Netlify deploy issues are related to image filename case-sensitivity and caused by some of the png files having .PNG extension. I've fixed this (and a couple of incorrect links) in PR #3268 - if that's merged and then you rebase then I think with the changes you've already made in this branch it should build successfully 🤞 

@allanaaa probably just worth noting that image files in /static/img need to have the same case as any references to those files from inside the markdown - I'd suggest we standardise to always using lowercase for the file extensions

**Comment by wetneb** [comment]
I have not checked, but there could also be issues detected by link validation: #3031.

**Comment by ostephens** [comment]
@wetneb you are right, but I think with my corrections in #3268 and the ones that @tfmorris has already fixed in this PR then we have got them all

**Comment by tfmorris** [comment]
That rename operation made my case-preserving, but case-insensitive file system very unhappy. Let's avoid wonky file extensions in the future please!

Thanks for the fixups. I rebased the branch and fixed a couple of other broken links before realizing that #3031 contained the hint as to what changed in the new version. Disabling the default link checking fixed the build. I'll leave it to the pros to repair the broken links.

Should be ready for review now.

**Review by wetneb — APPROVED** [review]

**Pull request merged**
