### PR TITLE
New importer: wikicode tables

### LINKED ISSUE #363: Support Wiki table formats
_Original author: techtonik@gmail.com (April 16, 2011 15:47:13)_

<b>What steps will reproduce the problem?</b>
1. http://wiki.python.org/moin/PythonEditors?action=edit&amp;editor=text 2. Copy data, save into a file
3. Import using || separator

<b>What is the expected output? What do you see instead?</b>
1. empty columns to be removed automatically
2. '''bold''' formatting removed from headers
3. links should not be split into columns - they use single pipe | character

<b>What version of Google Refine are you using?</b>
2.0-r1836

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=363_
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/62939-support-wiki-table-formats?utm_campaign=plugin&utm_content=tracker%2F32795&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32795&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wetneb**
- automatic reconciliation to Wikidata based on wikilinks;
- support for cells spanning over multiple rows or columns;
- robust parser accepting incomplete inputs (sweble-wikitext)

This closes #363 and solves most of #56 (although not via HTML).

This PR adds a dependency to the wikitext parser:
http://sweble.org/sites/swc-devel/develop-latest/tooling/sweble/sweble-wikitext/
If it is not acceptable to add this dependency, I can move the importer to an extension that I will distribute separately.

Potential improvements:
- support lists
- support multiple tables in the same file
- support template expansion

### CODE REVIEW

**Comment by thadguidry** [comment]
@wetneb Sweble Wikitext Parser is ASL 2.0 license so its fine to include...but you have to also include a jar that contains the source code as well, like we do for the others here https://github.com/OpenRefine/OpenRefine/tree/master/main/webapp/WEB-INF/lib-src

**Comment by wetneb** [comment]
@thadguidry I've added the sources JAR and listed the library in our LICENSE.txt file, let me know if anything else is missing!

**Comment by thadguidry** [comment]
@wetneb Looks like there are still conflicting files that need to be addressed ?

**Comment by wetneb** [comment]
@thadguidry That is just something that will be solved when we merge. It's just that I have included 5390aa248cd044 in both branches so that the tests do not fail in this PR.

**Comment by thadguidry** [comment]
Ah ok. I'm still getting used to the new PR views with Codacy.

**Comment by wetneb** [comment]
@thadguidry yeah, I have to admit Codacy is too verbose to my taste. I tried disabling some of the patterns but I get a 404… And also, they never report any information about code coverage, which was the goal of the integration…

**Comment by thadguidry** [comment]
Well your welcome to switch out to something else that works well. Try one
of the other integrations from the Github Marketplace. Many to try out and
see if they fit better for us.

**Comment by thadguidry** [comment]
@wetneb Codacy does show coverage btw.  Its under View All link on the right side of dashboard under Coverage https://www.codacy.com/app/OpenRefine/OpenRefine/dashboard  But perhaps other tools show this a bit better or more towards your taste.  Just try a few other coverage tools to get a feel for what you prefer.  I have no preference, they all are similar, just some are more denser than others in the views. (easier for old eyes or not :)  )

**Comment by wetneb** [comment]
@thadguidry Yeah why not giving a try to Codecov - personally I just love Coveralls, all it adds on PRs is this: https://github.com/dissemin/dissemin/pull/426#issuecomment-319653015, and that's essentially all I need. Code issues are useful, but only if they can easily been enabled and disabled, IMHO.

**Comment by thadguidry** [comment]
@wetneb Codacy already gives us the badge on our main page...and we are at 20%.  The code smells can be tweaked in the Codacy admin pages... we probably should just set some time this weekend between the 3-4 of us and just come to agreements on all this... would be much easier I think.  I don't even have a good email address for you, btw... can you email me ?  I'll setup a Google Hangout for this weekend.

**Comment by thadguidry** [comment]
@wetneb OK, I tweaked Codacy for our project, should be better now that jquery libs are excluded.

**Pull request merged**
