### PR TITLE
fixes #2910 : Service remove button click event propagates to…

### LINKED ISSUE #2910: Service remove button click event propagates to underlying element
**Describe the bug**

When trying to remove a service the service gets selected 
**To Reproduce**
1. Reconcile ➡ Start reconcile... 
2. Click little cross symbol 
3. Service start loading 

**Current Results**
On selecting the cross precisely (it's small) it is still the underlying element that responds. When reloading the page the old service has been removed. 

**Expected behavior**
The service is removed, not loaded 

**Desktop:**
 - OS: Windows 
 - Browser Version: Chrome 
 

**OpenRefine :**
 - Version 
OpenRefine 3.4 beta 2

### PR DESCRIPTION
**Pull request by Gomaa**
fixes #2910

### CODE REVIEW

**Comment by Gomaa** [comment]
fixes #2910 : Service remove button click event propagates to underlying element

**Comment by tfmorris** [comment]
Thanks for the contribution. Can you please edit the main body of the PR to include the "fixes #2910" text from your first reply. It needs to be in the original for Github to recognize it, link it to the issue, and close that issue when this PR gets merged.

**Review by wetneb — COMMENTED** [review]
Thanks for this pull request!

In addition to Tom's comment, I would also recommend that (in the future) you create a branch in your fork, instead of committing your changes directly to master. This will help you work on multiple pull requests at a time, which can be quite useful.

Concerning the change itself, I tried it out and it does not seem to work for me (using Firefox on Linux). I am a bit puzzled by your code changes - intuitively I would expect that this bug could simply be solved by adding a call to `event.preventDefault()` at the end of the appropriate click handler (the one that removes the service).

**Comment by Gomaa** [comment]
Thanks @wetneb for your comments. I actually tried to use event.preventDefault in here $('<a>')
      .html("&nbsp;")
      .addClass("recon-dialog-service-selector-remove")
      .prependTo(record.selector)
      .click(function(e) {
        ReconciliationManager.unregisterService(service, function() {
          self._refresh(-1); 
          
        });
        e.preventDefault();
      });

But this line "self._serviceRecords.push(record);" is causing the loading to take place, that's why I moved this line to the selector link 'recon-dialog-service-selector', apparently, it didn't work though.

**Review by wetneb — APPROVED** [review]
Thanks a lot, it works now!

**Pull request merged**
