### PR TITLE
drop deprecated KeyboardEvent.keyCode property

### PR DESCRIPTION
**Pull request by Abbe98**

### CODE REVIEW

**Comment by tfmorris** [comment]
This is used in a few places. Would it make sense to change them all at the same time for consistency?

https://github.com/OpenRefine/OpenRefine/search?l=JavaScript&q=27

**Comment by Abbe98** [comment]
@tfmorris yeah definitively!

**Comment by Abbe98** [comment]
Updated.

**Comment by elebitzero** [comment]
What about this usage of `event.which`?

https://github.com/OpenRefine/OpenRefine/blob/8b749b3c5af83d8a963f3c36fbb8525094dbddc0/main/webapp/modules/core/scripts/views/data-table/data-table-view.js#L513

**Comment by Abbe98** [comment]
@elebitzero nice catch!

**Review by elebitzero — APPROVED** [review]
Looks good, there are a few more deprecations but they can be done in a later PR:

https://github.com/OpenRefine/OpenRefine/blob/a1e1ac3e21570d08fc4ff941374cd6ed95ce28da/main/webapp/modules/core/scripts/project/process-panel.js#L50

https://github.com/OpenRefine/OpenRefine/blob/14c274a3209d369799155bdd8c098d15af682fc9/extensions/wikibase/module/scripts/dialogs/perform-edits-dialog.js#L77

**Pull request merged**
