### PR TITLE
#486 add encoding guesser based on icu4j

### PR DESCRIPTION
**Pull request by stundzig**
Hi folks,

i've added a encoding guesser based on icu4j, which checks during _load-raw-data_ what is the most likely character encoding. Also currently i set the first found encoding, as initial ui-option.

I would also propose to update the icu4j version to the latest 56.1 -> http://icu-project.org/apiref/icu4j/

Regards
   Steffen...

### CODE REVIEW

**Comment by tfmorris** [comment]
Thanks for the contribution.  I'm not sure we've got the headroom to include ICU4J and still make it under Github's 100MB file size limit for the Mac kit, but I'll have a look.

**Comment by wetneb** [comment]
Looking at the latest releases, it seems that the aforementioned 100MB file size limit is no longer true (122MB for Mac). Should we merge this? I think it would be good to have a test or two to demonstrate the cases where that is useful. Maybe something based on #1197?

**Comment by thadguidry** [comment]
@wetneb I'll defer to @jackyq2015 as to how we should handle this.  @jackyq2015 thoughts ?

**Comment by jackyq2015** [comment]
Added the inline comments. But I agree that encoding detector such as ICU4J should be added into OR

**Comment by wetneb** [comment]
Closing because of failing build - feel free to rebase and resubmit, ideally with tests.

**Pull request closed without merging**
