### PR TITLE
Add Homebrew docs to both 3.5 and master docs

### PR DESCRIPTION
**Pull request by wetneb**
Adds back the text contributed by @joewiz which got lost in the versioning of the docs.

### CODE REVIEW

**Comment by wetneb** [comment]
For #4285.

**Comment by joewiz** [comment]
It appears this that one of the checks for this PR has stalled. Would it be possible to restart it?

**Comment by wetneb** [comment]
Those checks are not normally run for documentation-only PRs (I agree with you that the UI is confusing, we need to fix this). Let me add back the missing changes and finally merge this.

**Comment by joewiz** [comment]
@wetneb Thank you!

**Pull request merged**
