### PR TITLE
First part of Hebrew translations

### PR DESCRIPTION
**Pull request by noamoss**

### CODE REVIEW

**Comment by magdmartin** [comment]
@noamoss is your translation complete with cebb10f or there still work to do for RTL support?

**Comment by noamoss** [comment]
more work to be done...Taking it step by step.

**Comment by thadguidry** [comment]
@noamoss how's the Hebrew translation coming along ? :)  We'd like to get this in sometime in the future. Let us know.

**Comment by magdmartin** [comment]
@thadguidry we can also reach out to the community (twitter / discussion list) for help to complete the translation. This approach was successful with the Spanish one. 

We just need to have the initial work done by @noamoss  available on a branch so other contributors can send their PR.

**Comment by magdmartin** [comment]
If there is no one commenting against in the next five days, I will:
* fix the conflict (help welcome for that part)
* merge this PR in the new branch `hebrew-trans` 
* reach out to the twitter feed + mailing list for PR to complete the translation.

**Comment by wetneb** [comment]
I think it would be simpler to merge this directly in master. This will let users contribute via Weblate. Having a half-finished translation in master does not seem too harmful - users who select this language in their preferences will have English strings when the Hebrew translation is undefined.

**Comment by wetneb** [comment]
I have merged this, the translations can be edited directly there:
https://hosted.weblate.org/projects/openrefine/translations/he/

**Pull request closed without merging**
