### PR TITLE
Fix inconsistent Extract/Apply button location

### LINKED ISSUE #6432: Inconsistent location of Extract / Apply button
The button Extract / Apply are not consistently positioned between the project creation and after doing some operations.

After the project creation, the buttons are located under the information module 
image

After the user performs at least one operation, the button moves up. 

image

I would expect the button to always be at the top.

### PR DESCRIPTION
**Pull request by Redeem-Grimm-Satoshi**
Fixes #6432

Changes proposed in this pull request:
- Fix inconsistent Extract/Apply button location by making it stick to the top right

### CODE REVIEW

**Comment by Redeem-Grimm-Satoshi** [comment]
@wetneb

**Comment by Redeem-Grimm-Satoshi** [comment]
@wetneb  I simply just moved the `controls div `to the top of the `helper div`, I worked at my end as you can see below;
https://github.com/OpenRefine/OpenRefine/assets/45304978/a4546b78-1d45-4829-90d9-b4e76b467dd0

**Comment by Redeem-Grimm-Satoshi** [comment]
@wetneb I just noticed I didn't delete the previous `history-panel-controls` div and that is why those empty buttons were present at the top, I just removed it now and it works fine

**Review by wetneb — APPROVED** [review]
Thank you!

**Pull request merged**
