### PR TITLE
Update separator-based-parser-ui.html

### PR DESCRIPTION
**Pull request by isaomatsunami**
widen cell for "character encoding" to make it 1 line.
This word is hard to shorten in Japanese/Chinese
If you don't want, discard.

### CODE REVIEW

**Comment by magdmartin** [comment]
@isaomatsunami  thanks for taking care of this. Did you check for overflow in other translation> The issue was initially reported in  #974

I guess a single PR for #1458 #1459 #1460 will be appreciated by the dev team.

**Comment by isaomatsunami** [comment]
OK, I try to merge them, I will try and try.
And I will recheck in other languages.

**Comment by isaomatsunami** [comment]
I am very sorry to bother dev teams. Please discard #1458 #1459 #1460 #1461 #1462 #1463 
Basically it seems good in other languages. but I will reconsider more robust one. 
I will send it as a single PR, I will try.

**Comment by wetneb** [comment]
@isaomatsunami no problem, let us know if you need git help for that!

**Pull request closed without merging**
