### PR TITLE
Disables FacetContainer while computing clusters

### LINKED ISSUE #2675: facetContainer in Cluster dialog shows interactive when compute-clusters is running
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Clustering dialog shows facets in `facetContainer` to still be interactive even while `compute-clusters` is running in background.

**Describe the solution you'd like**
Grey out the `facetContainer` to make it non-interactive **until** the `/command/core/compute-clusters` operation is finished and the `<div class="clustering-dialog-table-container" bind=tableContainer">` is populated with Cluster entries.

**Describe alternatives you've considered**
Do not show `facetContainer` at all (instead of grey out non-interactive) and make it completely hidden until `compute-clusters` is finished.

**Screenshot**
The false impression that users get that they can still manipulate the facet sliders in 2. `facetContainer` while 1. `compute-clusters` is running.

image

### PR DESCRIPTION
**Pull request by darecoder1999**
fixes #2675
ezgif com-video-to-gif

### CODE REVIEW

**Comment by thadguidry** [comment]
@darecoder1999 Thanks for working on this!  Pulling and taking a look now...

**Comment by darecoder1999** [comment]
Yes, I have also noticed this vertical shift but this is not something disturbed due to my changes. 
If you want we can make its display none too as suggested in alternative solution in the issue.

**Comment by thadguidry** [comment]
@darecoder1999 Yes, let's make it `hidden` while Clustering compute is happening.

**Comment by wetneb** [comment]
@thadguidry please do not merge code PRs without the eyes of @tfmorris or me :)

**Pull request merged**
