### PR TITLE
Add new GREL function to calculate the edit distance #6613

### PR DESCRIPTION
**Pull request by dino2580**
Fixes #[6613](https://github.com/OpenRefine/OpenRefine/issues/6613)

Changes proposed in this pull request:
- Used Apache LevenshteinDistance.java
- Created editDistance grel

### CODE REVIEW

**Review by zyadtaha — CHANGES_REQUESTED** [review]
Hi @dino2580, thanks for this, it looks very good to me! However, I haven't reviewed the implementation super closely yet.

In the meantime, here are some improvements you can do: (Have a look on [this](https://github.com/OpenRefine/OpenRefine/pull/4752/files))
- Making the class implement `Function` interface
- Registering the function in the `ControlFunctionRegistry.java` file (`main/src/com/google/refine/grel/ControlFunctionRegistry.java`).
- Changing the class path to (`main/src/com/google/refine/expr/functions/strings`)
- Adding a unit test in the end demonstrating this functionality 

(P.S.: I changed your issue description so that it includes "Fixes https://github.com/OpenRefine/OpenRefine/issues/6613". This syntax is required for GitHub to properly link the pull request to the issue on the right-hand side)

**Comment by xinluz6** [comment]
Hi @dino2580, would you mind if I attempted to write some test cases for your function? I am trying to create test cases for a new function and would appreciate your permission to proceed with this task.

**Comment by dino2580** [comment]
Yes I would appreciate that

**Comment by xinluz6** [comment]
Hi @dino2580, thank you for letting me try to write test cases for this function. I have opened the new pull request #6634  with the test file after modifying the code based on the improvements suggested. Thank you again for the opportunity to contribute to this project.

**Comment by zyadtaha** [comment]
Hi @dino2580,
Are you still working on this?

**Comment by dino2580** [comment]
I completed the necessary work if still something is left I can do that

**Comment by zyadtaha** [comment]
@dino2580 Yes, please push your last commits to this pull request so I can review them.

**Comment by wetneb** [comment]
This doesn't seem to be worked on anymore, so I am closing this PR to keep our list of open pull request tidy. @dino2580 if you want to keep working on this, feel free to reopen a new PR which addresses the points brought up by @zyadtaha above. Thank you!

**Pull request closed without merging**
