### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by antoine2711**
Changes proposed in this pull request:
- Put main/webapp/package-lock.json in the ignored files because it is local to a user.

@wetneb: is this a good move?

Regards, Antoine

### CODE REVIEW

**Comment by wetneb** [comment]
I think it should indeed either be in `.gitignore` or be checked in. I think the recommended practice is to add it to the git repository. @elebitzero do you agree?

**Comment by antoine2711** [comment]
> I think it should indeed either be in `.gitignore` or be checked in. I think the recommended practice is to add it to the git repository. @elebitzero do you agree?

@wetneb: isn't it a file that records what's is installed on a machine, a as such, recreated on each machine? If if some modules are installed globally, the file will not be the same, if I understand correctly. Why not let each user created to tailor his needs?

Regards, Antoine

**Comment by wetneb** [comment]
According to this, the recommended practice seems to be to commit the file to the repository: https://nodejs.dev/learn/the-package-lock-json-file

**Comment by wetneb** [comment]
@elebitzero can you confirm that the current situation is fine (so we should close this PR without merging)?

**Comment by wetneb** [comment]
(sorry, I closed it by mistake - the intention was to wait for @elebitzero's feedback)

**Comment by wetneb** [comment]
Given that it is officially recommended to check it in per the link above, let us close this.

**Pull request closed without merging**
