### PR TITLE
migrate from JRDF to JENA library

### PR DESCRIPTION
**Pull request by jackyq2015**
To fix the #1560

### CODE REVIEW

**Comment by jackyq2015** [comment]
@thadguidry According to [this](https://jena.apache.org/documentation/io/rdf-input.html):
Much of the functionality is accessed via the Jena Model API; direct calling of the RIOT subsystem isn't needed. 

I tried to remove few of jars and all lead to exception when loading

**Comment by thadguidry** [comment]
@jackyq2015 is this an exposed option or not ?

To aid in checking for errors in UTF8-encoded files, there is a utility which reads a file of bytes as UTF8 and checks the encoding.

    utf8 -- read bytes as UTF8

**Comment by jackyq2015** [comment]
@thadguidry I cannot see the RIOT is a exposed option.

For the utf8 part, how is related to this change?

**Comment by thadguidry** [comment]
@jackyq2015 forget it.  we can deal with that option later.

**Pull request merged**
