### PR TITLE
Set up docs deployment process with Netlify

### PR DESCRIPTION
**Pull request by wetneb**
This is an attempt to deploy the docs with Netlify, which should provide PR previews.

### CODE REVIEW

**Comment by thadguidry** [comment]
Great!  Tested and locally works on Windows with the right steps!

But why is the theme not loading on Netlify? but does locally?

image

**Comment by wetneb** [comment]
The CSS loading issue will be fixed by this PR (as you can see in the PR preview, in the checks section).

**Comment by thadguidry** [comment]
Ah!  Thanks for the tip!  It is the last check!  netlify/openrefine-docs/deploy-preview   then I click Details link. Nice!

**Comment by thadguidry** [comment]
How is Netlify account itself managed?  Do we have backup admin credentials? Is it hooked into our GitHub Org?

Ah!  It's an installed integration into our Org!  Nice!  So any one of our Org admins can manage it (backup admins), correct?

image

**Comment by thadguidry** [comment]
@kushthedude OK, seems to build and start for me just fine after yarn installation in my node on Windows 10.  Anything that you see here that might cause some issue or slightly different than your output? (I'm not familiar with yarn package management yet)
```sh
E:\GitHub Repos\OpenRefine\docs>yarn
yarn install v1.22.4
warning package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] Resolving packages...
warning docusaurus > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning docusaurus > crowdin-cli > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning docusaurus > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning docusaurus > markdown-toc > gray-matter > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning docusaurus > markdown-toc > remarkable > autolinker > gulp-header@1.8.12: Removed event-stream from gulp-header
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning docusaurus > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 41.02s.

E:\GitHub Repos\OpenRefine\docs>yarn build
yarn run v1.22.4
warning package.json: No license field
$ docusaurus-build
generate.js triggered...
sitemap.js triggered...
Site built successfully. Generated files in 'build' folder.
Done in 6.31s.

E:\GitHub Repos\OpenRefine\docs>yarn start
yarn run v1.22.4
warning package.json: No license field
$ docusaurus-start
LiveReload server started on port 35729
Docusaurus server started on port 3000
```

**Comment by kushthedude** [comment]
> cause

Its perfect!
There were warning of missing license field as package.json manifest was missing. But I have added the manifest by PR #2570 , hence now there should not be any warning too.

**Comment by thadguidry** [comment]
@kushthedude and if I wanted to essentially do a reset?  Is that just the following?
```
yarn clean cache
yarn build
```

**Comment by kushthedude** [comment]
> @kushthedude and if I wanted to essentially do a reset? Is that just the following?
> 
> ```
> yarn clean cache
> yarn build
> ```

It's `yarn cache clean` .

**Comment by thadguidry** [comment]
@kushthedude yeah... but... its not a true "reset", it's still holding on to the cache.  This reminds me of `gradle` where there's a force, but here it doesn't seem to work... dependencies are not being pulled down again....its not a complete reset.  How to truly achieve that?

```
E:\GitHub Repos\OpenRefine\docs>yarn cache clean --force
yarn cache v1.22.4
success Cleared cache.
Done in 0.04s.

E:\GitHub Repos\OpenRefine\docs>yarn build
yarn run v1.22.4
$ docusaurus-build
generate.js triggered...
sitemap.js triggered...
Site built successfully. Generated files in 'build' folder.
Done in 3.97s.

E:\GitHub Repos\OpenRefine\docs>
```

**Comment by kushthedude** [comment]
> @kushthedude yeah... but... its not a true "reset", it's still holding on to the cache. This reminds me of `gradle` where there's a force, but here it doesn't seem to work... dependencies are not being pulled down again....its not a complete reset. How to truly achieve that?
> 
> ```
> E:\GitHub Repos\OpenRefine\docs>yarn cache clean --force
> yarn cache v1.22.4
> success Cleared cache.
> Done in 0.04s.
> 
> E:\GitHub Repos\OpenRefine\docs>yarn build
> yarn run v1.22.4
> $ docusaurus-build
> generate.js triggered...
> sitemap.js triggered...
> Site built successfully. Generated files in 'build' folder.
> Done in 3.97s.
> 
> E:\GitHub Repos\OpenRefine\docs>
> ```

If you want to update the dependencies, yarn will update them as soon as there is any change in `package.json` or `yarn.lock`. Coming to if you want to re-install all the dependencies, you will have to remove the `node_modules` folder and re-run `yarn`. I think there is no command for re-installing all dependencies for npm too, you will have to go by the old school of removing the `node_modules` & re-running `npm i`.

If you want to re-build the website, Yarn will build the website from the previous version until & unless there is no change in the files. If there is any change in code/docs, yarn will make new builds & cache it again. This is the advantage over npm where it always builds a new site in build folder regardless of knowing if there was any change or not.

**Comment by thadguidry** [comment]
@kushthedude I noticed that Netlify is building and deploying even on PR's that don't touch the docs/ path.  I read some here: https://docs.netlify.com/configure-builds/get-started/#basic-build-settings  So it seems like we should ideally setup a `netlify.toml` file (like we do for travis and appveyor) since we are using a monorepo style?  And within it set the base dir like so (and anything else needed within the [Netlify configuration file](https://docs.netlify.com/configure-builds/file-based-configuration/):

```toml
# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "docs/"
```

**Comment by kushthedude** [comment]
@thadguidry I think `base_directory` has already been set-up to `/docs` from netlify dashboard as we are getting successful deploys.

Coming to your point of checks, yes checks will be shown at every PR but if a PR is not concerned about the changes in the `doc` subdirectory, netlify will give this at the place of successful deploys : 
Screenshot 2020-04-19 at 9 28 55 PM

**Comment by thadguidry** [comment]
@kushthedude Yes, I saw that also, but still seems slightly wasteful to kick off Netlify deploy if not needed, but OK.

**Comment by kushthedude** [comment]
> @kushthedude Yes, I saw that also, and as you can see attempts scanning and processing for about 30 secs on their platform so still seems slightly wasteful to have Netlify run that if not really needed, but OK.

Even I was facing this problem on my other repositories, but I used https://github.com/ramigs/netlify-lambda-github-webhook-router/blob/master/functions/webhookParser.js for my personal projects. But I don't think this would be appropriate for a project like OpenRefine as it may expose some sensitive data.

**Comment by wetneb** [comment]
Yes, it would be nice to avoid Netlify builds on code-only PRs and Travis/Appveyor builds on docs-only PRs. Perhaps that's actually a good reason to use different repos. Thanks @kushthedude for the link above, it is interesting.

Merging this now to fix docs.openrefine.org, for now.

**Pull request merged**
