### PR TITLE
Rough draft for use of official accounts (Twitter)

### PR DESCRIPTION
**Pull request by thadguidry**
We'll probably need several passes on this until we come to something that is not so wordy and effectively shows or mimics how @magdmartin has so generously been handling our official tweeting and his practices!
My section that I think hits to the core of the issue that @wetneb brought up on list and provoked adding language into our Governance is in section `### Use of official OpenRefine accounts`

Jess @ CS&S provided their section `#### Tweeting`, which I have quickly, roughly cleaned up just so we could glance over it here in review and pick what we like, and remove what we don't need.

- [ ] It will be good to come to some agreement on a few points that Jess @ CS&S had put into theirs (like avoiding politics, etc.)
- [ ] The rest of her section kinda flows in and out of "how to properly tweet with OpenRefine's account", which I think can be pulled out, or just cleaned up, or alternatively put into another doc that is not Governance related.
- [ ] Maybe we want others like Sandra or Alicia or whomever from Steering committee to also help us a bit here?

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
Thanks! To me it feels a little bit over-complicated - it is not clear to me we need such a strong-handed policy for this.

As a follow up to this Gitcoin episode I would rather add just a few sentences, which would not be focusing on Twitter, but rather emphasizing that starting new crowdfunding campaigns, funding applications or other partnerships should be coordinated in the advisory committee first.

**Comment by thadguidry** [comment]
@wetneb Reading and thinking through my paragraph drafted and your feedback thus far.
Hmm, I think anyone in the community, if they want to start a crowdfunding campaign to help OpenRefine could do so, no? I mean, we can't really stop them or stop them from impersonating our official org.  Criminals will be criminals.

So this Governance is about those with access of our official accounts and using them for ANY funding campaign, yes?  I mean, the only bounds that I overstepped in your mind was that I didn't communicate enough with the whole advisory committee on using our official Twitter, yes?

**Comment by wetneb** [comment]
Ok my comment was not so clear: I would say that "starting new crowdfunding campaigns, funding applications or other partnerships **in the name of the project** should be coordinated in the advisory committee first."

Using the official Twitter account is one way of doing things "in the name of the project".

**Comment by thadguidry** [comment]
@magdmartin What are your thoughts also now after this last revision I made?  Looking better? Good enough for now?

**Comment by thadguidry** [comment]
@magdmartin Hi Martin, I had a followup reminder... asking again for your thoughts on the changes now and if we have agreement and further thoughts on full majority needed or not?

**Comment by wetneb** [comment]
Closing since we agree we can make progress on this topic in other ways.

**Pull request closed without merging**
