### PR TITLE
fix issue #873 2.6-beta1 does not open browser tab on start on a Mac

### PR DESCRIPTION
**Pull request by jackyq2015**
fix issue #873 2.6-beta1 does not open browser tab on start on a Mac

### CODE REVIEW

**Comment by tfmorris** [comment]
This is showing the entire file as changed in the diff on Github.  Can you fix that please? (Presumably a line ending issue)

**Comment by joewiz** [comment]
Appending ?w=1 to the URL of the diff view forces an ignore whitespace diff:

https://github.com/OpenRefine/OpenRefine/pull/1074/files?w=1

See https://github.com/blog/967-github-secrets

**Comment by tfmorris** [comment]
@joewiz Thanks for the tip, but we still need a clean patch.  Github is just reflecting what git sees in the repo.

**Comment by tfmorris** [comment]
Thanks for updating the patch -- and thanks for the fix!

**Comment by joewiz** [comment]
+1!

**Pull request merged**
