### PR TITLE
Add feature to trigger a button on hitting Enter to fix #3137 

### LINKED ISSUE #3137: Pressing "Enter" in the project name field at the preview stage should create the project
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

When previewing an importer's results, there is a text field to enter the project name. When pressing Enter in this field, I would expect the project to be created (without having to click the "Create Project" button).

image

### PR DESCRIPTION
**Pull request by leoshrey**
Fixes #3137 

- Pressing "Enter" in the project name field at the preview stage will now create the project.

check it out

sample123 (1)

### CODE REVIEW

**Comment by leoshrey** [comment]
Hi @wetneb , I tried to delete and recover some unneeded commits due to which my local branch became mess.
Because of which while creating a PR it showed "Can't automatically merge. Don't worry, you can still create the pull request.". 
Can you please review the changes and resolve the conflicts?
Also, Please ignore "1230743" commit as this was already done and merged under #3365 .

**Comment by leoshrey** [comment]
Should I open new PR by committing again if this is not acceptable?

**Comment by wetneb** [comment]
Hi @leoshrey,
Thanks a lot for this PR! This problem is caused by the fact that you have used the master branch of your fork to open your pull request. You should instead open one branch for each pull request you submit (branching off the master branch).

If I had to recover from this situation I would do the following:
- Create a branch for this issue: `git checkout -b 3137-project-name-enter master`
- Go back to master: `git checkout master`
- Update your master branch to match that of https://github.com/OpenRefine/OpenRefine, which you might have to register as a remote first:
```
git remote add upstream https://github.com/OpenRefine/OpenRefine
git fetch upstream
git reset --hard upstream/master
```
- Go back to your issue branch: `git checkout 3137-project-name-enter`
- Clean up the diff to master: `git reset master`, `git commit -a`

**Comment by leoshrey** [comment]
Thank you very much for https://github.com/OpenRefine/OpenRefine/pull/3404#issuecomment-743789387 , Creating a new PR in a minute.

**Comment by wetneb** [comment]
Closing this one as a duplicate of #3406.

**Pull request closed without merging**
