### PR TITLE
Recently selected choice will appear as default choice

### LINKED ISSUE #2316: "Match other cells with same content" keeps appearing as the default choice
**Describe the bug**

When doing reconciliation, I sometimes manually match entries to Wikidata items using "Search for match". I choose the correct match but the match is applied to _all entries with the same name_ because the radio button "Match other cells with same content" is always ticked by default. Even if I change it, next time this button will again be ticked. 

**Expected behavior**
It would be very cool if I could either choose the default button in settings, or OpenRefine could remember my last choice.

**Screenshots**
Bez názvu

**Desktop**
 - OS: [Windows 10]
 - Browser Version: Chrome version 80.0.3987.106
 - OpenRefine 3.3 Beta

### PR DESCRIPTION
**Pull request by khyati-agarwalss**
Fixes #2316

### CODE REVIEW

**Comment by khyati-agarwalss** [comment]
> Thanks! However I don't understand how this is supposed to work - where is the recently selected choice stored? Also, I tried running this and now the "Match" button does not do anything anymore.

@wetneb I thought it worked, but you are right, the Match button isn't working. I tried other methods of doing this, but nothing is leading to what is expected.

**Comment by wetneb** [comment]
The 2 options are radio buttons, so one of them must be selected by default, I would expect. You could replace both radio buttons by a single checkbox, but it would probably not be as clear as the current UI.

**Comment by khyati-agarwalss** [comment]
> The 2 options are radio buttons, so one of them must be selected by default, I would expect. You could replace both radio buttons by a single checkbox, but it would probably not be as clear as the current UI.

True. Also, changing that might break other functions.

**Comment by wetneb** [comment]
Closing per https://github.com/OpenRefine/OpenRefine/issues/2316#issuecomment-606469655

**Pull request closed without merging**
