### PR TITLE
remove ignorewarnings=0

### LINKED ISSUE #4472: Prevent users from uploading duplicate files to Wikimedia Commons
In some cases, people who use OpenRefine for uploading new files to Wikimedia Commons will not be aware that (some of) these files already exist on Wikimedia Commons. This may happen, for instance, in cases where a cultural institution (GLAM) wants to do a batch upload to Commons, where previously a volunteer may already have found and uploaded (some of) their files there, or vice versa.

### Proposed solution

_Exact_ duplicates can be tracked/identified during upload to Wikimedia Commons, and upload tools usually (but [not always](https://bitbucket.org/magnusmanske/flickr2commons/issues/80/not-tagging-duplicates-properly)) support discovery and rejection of upload of such duplicates. It would be really good if OpenRefine would indeed do this too.

[Commons:Guide to batch uploading](https://commons.wikimedia.org/wiki/Commons:Guide_to_batch_uploading#Check_for_duplicates) contains some pointers on how to check for duplicates: it is possible to [ask the Commons API](https://commons.wikimedia.org/w/api.php?action=query&titles=File:Example.jpg&prop=imageinfo&iiprop=sha1) to look for files with [a same SHA-1 hash](https://commons.wikimedia.org/w/api.php?action=query&list=allimages&prop=imageinfo&aisha1=d01b79a6781c72ac9bfff93e5e2cfbeef4efc840).

As an example, Wikimedia Commons' own UploadWizard provides the user with an immediate warning if they try to upload an exact duplicate of a file.
image

### What about nearly exact duplicates?

It would be great if it would be possible to also identify nearly exact duplicates (e.g. visually extremely similar files), but this seems not technically possible yet. 

As an example, [this file](https://commons.wikimedia.org/wiki/File:Naturalis_Biodiversity_Center_-_RMNH.AVES.110015_-_Chloridops_kona_Wilson,_1888_-_Kona_Grosbeak_-_specimen_-_lateral_view.jpeg) was uploaded in 2015 during a GLAM partnership (by a Wikipedian in Residence). The file [is also shared on the GBIF website](https://www.gbif.org/occurrence/2433871981) and was [uploaded again with another tool in 2022](https://commons.wikimedia.org/wiki/File:Chloridops_kona_S.B.Wilson,_1888_2433871981.jpg). While both files are visually identical, they do have different file sizes and EXIF data, so some processing has happened through time.

There are some [ideas and discussions](https://commons.wikimedia.org/wiki/User:F%C3%A6/Imagehash) around this issue on Wikimedia Commons, but to my knowledge no concrete/actionable steps yet (e.g. applying other types of image hashing). See also https://phabricator.wikimedia.org/T251026

### PR DESCRIPTION
**Pull request by Ambrosiani**
Fixes #4472 

Changes proposed in this pull request:
- remove `ignorewarnings=0` from code

perhaps additional code is needed to handle upload errors?

MediaWiki upload API: https://www.mediawiki.org/wiki/API:Upload#Upload_warnings

### CODE REVIEW

**Review by Abbe98 — COMMENTED** [review]
The errors could be parsed and returned in the `uploadFile` method.

 https://github.com/OpenRefine/OpenRefine/blob/608e2f8fccb161ca03ab224e5c57a6c594cfd46a/extensions/wikidata/src/org/openrefine/wikidata/editing/MediaFileUtils.java#L175

**Review by wetneb — APPROVED** [review]
It would make sense to return errors indeed, but we have not got any infrastructure to expose those errors to the users (#5032), apart from logging them in the server logs. So I think I would also be fine with merging this as is :)

**Comment by Abbe98** [comment]
@wetneb could we maybe log these to the console as a first step?

**Comment by wetneb** [comment]
It would be a great thing to have indeed! Also happy with including that in this PR (or a follow-up one).

**Review by Abbe98 — APPROVED** [review]

**Pull request merged**
