### PR TITLE
Update README.md for Emeritus contributors

### PR DESCRIPTION
**Pull request by thadguidry**
Stefano Mazzocchi and David Huynh have expressed that they no longer will contribute directly to OpenRefine but would like to be regarded as "Emeritus" status (having retired but allowed to retain their title as an honor)

### CODE REVIEW

**Comment by tfmorris** [comment]
In my mind the ordering is: 1) creators, 2) current contributors, and 3) all past contributors. I think 1 trumps 3, and David and Stefano (certainly David, since this project builds on much of his previous work at CSAIL etc) deserve pride of place as creators.

I'd probably reorganize this as two lists: 1) current contributors and 2) emeritus contributors with creators having special mention up front.

**Comment by thadguidry** [comment]
@tfmorris but David and Stefano wanted to specifically say "emeritus" to note they are no longer active, and not just say creators.  "emeritus creators" ???

**Comment by ostephens** [comment]
Just looking again at this, I think David's role as the originator is signalled through the opening para in the Credits section:

> This software was created by Metaweb Technologies, Inc. and originally written and conceived by David Huynh dfhuynh@google.com. Metaweb Technologies, Inc. was acquired by Google, Inc. in July 2010 and the product was renamed Google Refine. In October 2012, it was renamed OpenRefine as it transitioned to a community-supported product.

I think this works alongside the new Emeritus creators list

**Comment by thadguidry** [comment]
@ostephens yeah, I thought of that and thought ... "good enough" but OK, let me edit and make the "Emeritus Creators"

**Comment by ostephens** [comment]
Sorry - my comment was meant to say 'Emeritus Contributors' - basically I agree with you @thadguidry  - the Credit para + the two lists of Emeritus & Current contributors is sufficient.

**Comment by thadguidry** [comment]
@wetneb OK ready for merge now also :)

**Pull request merged**
