### PR TITLE
Fix help link for date formats

### LINKED ISSUE #3362: "Help" link on custom tabular exporter window doesn't work
### To Reproduce
custom-tab-exporter

### Current Results
When you click on the "Help" link (in the section about date formatting) it opens up a new tab and reloads the same project. 

### Expected Behavior
It should link to the new docs, I suppose? To 
https://docs.openrefine.org/manual/exploring#data-types
(Although I haven't yet explicated very thoroughly the different date format options shown here.)

If someone could confirm what the link was supposed to point to (a page on the wiki, or some other text) that would be helpful.

### Versions
 - Browser Version: Firefox
 - OpenRefine: 3.4.1

### PR DESCRIPTION
**Pull request by rachittiwari8562**
added link to <a> element for help on available date formats.
Fixes #3362

### CODE REVIEW

**Comment by wetneb** [comment]
Thanks @rachittiwari8562. Two small things:
* Make sure you write "fixes #3372" or "closes #3372" somewhere in the description of your pull request, so that GitHub understands that this issue will be closed when we merge this pull request. If you just mention the issue or write "fixes issue #3372" it will not work
* It can be useful to give a more descriptive title to your pull request, such as "Fix Help link for date formats" instead of "Fixes issue #3362"

**Comment by rachittiwari8562** [comment]
Thanks for this helpful advice .I would surely encapsulate these best-practices in future contributions.

**Comment by tfmorris** [comment]
> I would surely encapsulate these best-practices in future contributions.

You should be able to edit this pull request to incorporate those suggestions. Let us know if you run into a problem.

**Comment by allanaaa** [comment]
The PR with this change isn't merged yet (and won't be for a while) but a more specific link to use will be 
https://docs.openrefine.org/manual/exploring#dates
which is a subsection inside https://docs.openrefine.org/manual/exploring#data-types so it's not a huge difference if you want to go with the working link for now.

**Comment by rachittiwari8562** [comment]
fixes #3372 
Added link to point to documentation of custom date format.

**Comment by wetneb** [comment]
@rachittiwari8562 unfortunately this "fixes" keyword has to be in your first comment, at the top of the pull request (in the body text, not the title). It's not an extremely intuitive feature of GitHub for sure! Alternatively you should be able to link the pull request to the issue in the right-hand side menu of this page.

**Review by wetneb — APPROVED** [review]

**Pull request merged**
