### PR TITLE
Try to avoid invisible character exporting SQL

### LINKED ISSUE #4168: Export to SQL contains an invisible character in the name of the "id" column
According to [this tweet](https://twitter.com/RhesusNegatif/status/1440319559714496522) ("Absolument épuisée par un caractère invisible qui s'invite dans le nom de la 1e colonne (id) à chaque fois que j'exporte une table SQL dans OpenRefine"), there is an invisible a character in the name of the "id" column, which is present every time the SQL exporter is used.

### PR DESCRIPTION
**Pull request by xiao2k**
Fixes #4168

Changes proposed in this pull request:
- Have a try on the issue and Pull Request, the solution needs reconsider.

### CODE REVIEW

**Comment by LiGaOg** [comment]
辛苦了

**Comment by Unnamed-1408** [comment]
辛苦了

**Comment by xiao2k** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenRefine/OpenRefine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 凌晨2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenRefine/OpenRefine] Try to avoid invisible character exporting SQL (PR #4802)





 
辛苦了

**Comment by antoine2711** [comment]
@xiao2k: have you seen this?
https://github.com/OpenRefine/OpenRefine/runs/6148449600?check_suite_focus=true#step:7:56

**Comment by xiao2k** [comment]
> @xiao2k: have you seen this? https://github.com/OpenRefine/OpenRefine/runs/6148449600?check_suite_focus=true#step:7:56

Thanks for checking. I think I 'm doing wrong in maven formatting? I'll try that.

**Review by wetneb — COMMENTED** [review]
This PR goes in the direction of automatically cleaning up column names by trimming whitespace around them, but @thadguidry mentioned that it would be better not to do this behind the user's back, and mentioned that a warning would be preferable.

If we are going down the route of automated cleaning, I would rather do this earlier on, at the import stage, since having unexpected whitespace characters around column names can cause problems before export, in transformation workflows (for instance when referring to column names in GREL expressions).

**Comment by wetneb** [comment]
Tentatively closing this PR per inactivity and the potential change of approach needed.

**Pull request closed without merging**
