### PR TITLE
Cross error reporting

### PR DESCRIPTION
**Pull request by ostephens**
For #1976 
Refactor of cross (and related code) to:
* Fail with clear error to user when attempt to cross with non-existent project name
* Fail with clear error to user when attempt to cross using a non-unique project name
* No longer require the name of source project (from which the cross is being done) is unique

### CODE REVIEW

**Comment by wetneb** [comment]
@ostephens thank you very much for working on this! It looks very sensible to me. Have you considered adding a few tests to demonstrate?

**Comment by ostephens** [comment]
Happy to add some tests when I get some time (I'll try to find some time soon!)

**Comment by thadguidry** [comment]
So @ostephens there's going to be another PR to address the "column name not found" scenario also since you mentioned both project and column in #1976 ?
Currently its sorta silent if the column name is not found in a project that is found.... it returns `null` instead of a nice error to the user like "NonExistingTestColumn cannot be found in project clipboardCrossTest".
```
cell.cross("clipboardCrossTest", "NonExistingTestColumn")
```
returns `null`

Thanks so much Owen for this so far and looking forward to additional PR's to address the missing column name scenario and more tests!

**Comment by ostephens** [comment]
Added checks for non-existent columns and tests

**Pull request merged**
