### PR TITLE
Added support for .zst compressed files

### LINKED ISSUE #4058: Add support for importing "zst", "zstd" files
I would like to import a `.zst` or `.zstd` file but currently that file type is not recognized to be imported by OpenRefine.

### Proposed solution
Perhaps using Apache Commons Compress (we already have usage in `ImportingUtilities.java`)
https://commons.apache.org/proper/commons-compress/examples.html#Zstandard

### Additional context
RFC standard: `RFC 8478`
mime type: `application/zstd`
official website: https://facebook.github.io/zstd/
example file:  https://github.com/facebook/zstd/blob/dev/tests/golden-decompression/rle-first-block.zst
example code Apache Druid: https://github.com/apache/druid/blob/8296123d895db7d06bc4517db5e767afb7862b83/core/src/test/java/org/apache/druid/java/util/common/CompressionUtilsTest.java#L366

### PR DESCRIPTION
**Pull request by rachittiwari8562**
Fixes #4058 

Changes proposed in this pull request:
- Added `ZstdCompressorInputStream` from `org.apache.commons.compress.compressors.zstandard.ZstdCompressorInputStream` .
- Added a new dependency [zstd-jni](https://github.com/luben/zstd-jni) .

### CODE REVIEW

**Comment by wetneb** [comment]
Thanks! I think we currently do not depend on any JNI-based library, so we should probably consider the pros and cons carefully.
The jar itself weighs 5.7 MB, which is non-negligible. I guess if we keep it like this, we are effectively shipping the binaries for all platforms on all platforms. I do not know if Maven offers a way to be more selective.

I will also ask Markus, who maintains our Debian package, if packaging this Java library is doable.

If the addition of this new dependency is not a problem, then we will need some tests to make sure the feature works as expected (which will be especially interesting to run in our CI because of the platform-dependency).

**Comment by wetneb** [comment]
So I guess a natural question would be: is it imaginable to do this with a pure Java dependency instead? I have not checked if that exists. I assume that if the Apache Commons library relies on this one, it must be fairly trustworthy.

**Comment by rachittiwari8562** [comment]
> 

As far as my initial knowledge zstd-jni is the implementaion of zstd algorithm on java language as mentioned here https://facebook.github.io/zstd/ .

**Comment by wetneb** [comment]
One implication of adding JNI-based libraries is a more complicated signing process on Mac (since we need to extract the JAR, sign the dynamic library and put the JAR back together). So I am not really sure this is worth the effort and additional bundle weight, given that ZSTD is not so widespread.
I would be happy to add support for this with a more lightweight pure-Java solution though.

**Comment by thadguidry** [comment]
As I [mentioned in our dev mailing list](https://groups.google.com/g/openrefine-dev/c/j3sTfjJvROo/m/hNpwjZRYBAAJ) ,
Since we are only concerned with uncompressing during import time... would refactoring the PR to use native directly help?
Looks like there is an alternative (fewer features, but still it can decompress?)

https://stackoverflow.com/questions/60974402/lz4-and-zstd-for-java

**Comment by wetneb** [comment]
If the dependency has a compatible license and its jar is not too heavy, then I cannot think of other problems.

**Comment by thadguidry** [comment]
The native one "aircompressor" is Apache-2.0

**Comment by rachittiwari8562** [comment]
I have looked into 'aircompressor' and they are taking bytebuffer as input and providing the same as the output .While as far as I can see , we are using InputStream . Is it a good idea to open a file as byte[] and convert it into bytebuffer then pass it on to the decompressor?.....

**Comment by rachittiwari8562** [comment]
I have tried using the 'aircompressor' and tested it out on a 200mb zst file(600mb csv file) . It is working . Should I create a new branch for that implementation for comparision ... or should I overwrite in this branch only.

**Comment by wetneb** [comment]
As you prefer!

**Comment by rachittiwari8562** [comment]
I have added a new pr from a new branch  #4522.

**Comment by wetneb** [comment]
Thank you!

**Comment by luben** [comment]
zstd-jni also publishes architecture classified jars, e.g. [zstd-jni-1.5.2-1-linux_amd64.jar](https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1-linux_amd64.jar).

**Pull request closed without merging**
