### PR TITLE
Addition of a link to the GREL docs in the Help section of the Expression dialog

### LINKED ISSUE #1122: epoch is missing, well not really - but any reference to it is missing
The Help section of the Expression dialog has a reference to the SimpleDateFormat docs, and would be benefited by the addition of a link to the GREL docs -- I'd suggest putting it under the DatePart function, or perhaps just putting a section of reference links at the top of the Functions section of that help text

thanks!

### PR DESCRIPTION
**Pull request by Binita-tech**
Fixes #1122 

Changes proposed in this pull request:
- Addition of a link to the GREL docs in the Help section of the Expression dialog

### CODE REVIEW

**Comment by Binita-tech** [comment]
@wetneb , I have only made changes in DatePart.java, but other files are also appearing in my pull request. I have no idea how it is happening. Please guide

**Comment by Binita-tech** [comment]
Please review @wetneb , @antoine2711

**Comment by Binita-tech** [comment]
Is everything fine with this PR @wetneb?

**Comment by antoine2711** [comment]
> Is everything fine with this PR @wetneb?

Yes, it's good. It will be merged. Thank you.

Regards,
   Antoine

**Comment by antoine2711** [comment]
@Binita-tech : in an afterthough, I think this information could also be added to the Version 3.5 of our documentation, not just the current one (v3.6). What do you think? @thadguidry?

Regards, Antoine

**Review by antoine2711 — APPROVED** [review]

**Pull request merged**
