### PR TITLE
Warn user if Google extension oauth credentials have not been provided

### PR DESCRIPTION
**Pull request by AghaSaad04**
Signed-off-by: Agha Saad Fraz <agha.saad04@gmail.com>

I have added the link to the google extension page which will help the developers to configure the keys for signing into their Google account.
P.S: added the feature for different languages.

### Issue:
There was no help provided about how to set up the keys for signing in to the google account for the development version of the OpenRefine.

### Solution:
I have linked the google extension page with the OpenRefine, before signing in, the developer will visit the google extension page, will set up the required keys and will authorize the google account.

### CODE REVIEW

**Comment by thadguidry** [comment]
@wetneb It's beyond love :)  It's a disease.

**Comment by AghaSaad04** [comment]
@wetneb How would we know if credentials are already set up? Do you have any idea which file needs to be changed?

**Comment by wetneb** [comment]
> How would we know if credentials are already set up?

It's not easy as things stand! I guess you could introduce a new command which would just return a boolean indicating whether the credentials have been set or not. Or try to pass this information to the frontend at compile time somehow. It's definitely quite some work, and perhaps #2383 should be sorted out first.

**Comment by wetneb** [comment]
@AghaSaad04 do you intend to make progress on this PR or should we close it?

**Comment by AghaSaad04** [comment]
@wetneb Yeah I tried to register the command in controller.js file and also created a file that calls the boolean function(I added this function in **GoogleAPIExtension.java file** which returns true if both client_id and secret_key are set else false) but it is not working. 
Can you guide me a bit more about this?

**Comment by wetneb** [comment]
It is hard to help you without looking at your code, so perhaps you could open a draft pull request with what you have so far?

**Comment by kushthedude** [comment]
> @wetneb Yeah I tried to register the command in controller.js file and also created a file that calls the boolean function(I added this function in **GoogleAPIExtension.java file** which returns true if both client_id and secret_key are set else false) but it is not working.
> Can you guide me a bit more about this?

Would you mind pushing your code before asking for guide ?

**Comment by wetneb** [comment]
I propose to close this as stale unless @AghaSaad04 has the intention to work on this soon.

**Comment by tfmorris** [comment]
@AghaSaad04 Thank you for working on this. I'm going to close this for now, but if you find time to work on it again, feel free to either reopen this or create a new Pull Request.

**Pull request closed without merging**
