### PR TITLE
Update LICENSE.txt

### PR DESCRIPTION
**Pull request by magdmartin**
changes to the License.txt following [discussion on the mailing list. ](https://groups.google.com/d/msg/openrefine-dev/wMG0Dz8JMN4/bDR7o-O0AAAJ)

PR under progress

### CODE REVIEW

**Comment by magdmartin** [comment]
External licenses are already available in the licenses folder.  Do you
think we need a file listing them ?

On Feb 24, 2018 3:50 PM, "Thad Guidry" <notifications@github.com> wrote:

*@thadguidry* approved this pull request.

Ready to merge Martin ? will you be adding the external_license.txt file
also to this PR ? or separate ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenRefine/OpenRefine/pull/1519#pullrequestreview-99123050>,
or mute the thread

**Comment by thadguidry** [comment]
@magdmartin We just need to also update our README.md file to include the URL to the Github folder path, then I think we are good.  Notice this sentence in our README.md "See that file also for information on open source libraries that OpenRefine depends on."  which should be replaced with something like "See <url>(text) for license information on other open source libraries that OpenRefine depends on."

**Comment by magdmartin** [comment]
Ok I will do the edits.

**Comment by tfmorris** [comment]
LGTM. The diff is massive (basically the entire file), but I reviewed the license text and it is unchanged -- just reformatted.

**Comment by wetneb** [comment]
oh @tfmorris, good to see you! please do stick around if you have time!

**Pull request merged**
