### PR TITLE
Docs > index page

### PR DESCRIPTION
**Pull request by allanaaa**
A baseline of introductory text. Not too sure what needs to be included here but so far it's just a walkthrough of the docs structure.

### CODE REVIEW

**Review by wetneb — APPROVED** [review]
I love it!

**Comment by allanaaa** [comment]
There is also some commented-out text about versioning, which can be un-commented when we do a 3.5 fork.

**Comment by allanaaa** [comment]
We might also mirror some text from this page:
https://openrefine.org/

> OpenRefine (previously Google Refine) is a powerful tool for working with messy data: cleaning it; transforming it from one format into another; and extending it with web services and external data.
> OpenRefine always keeps your data private on your own computer until YOU want to share or collaborate. Your private data never leaves your computer unless you want it to. (It works by running a small server on your computer and you use your web browser to interact with it)
> OpenRefine is available in more than 15 languages.
> OpenRefine is part of Code for Science & Society.

**Review by ostephens — APPROVED** [review]
Looks good to me

**Comment by wetneb** [comment]
Let's merge this for now - we can improve it as we see fit later!

**Pull request merged**
