### PR TITLE
simplify dialog top position

### PR DESCRIPTION
**Pull request by Abbe98**
Have the default top positioning being set by CSS and only use JavaScript as a fallback for very large modals.

### CODE REVIEW

**Review by elebitzero — COMMENTED** [review]
When the dialog height is greater than 90% of the view height the new logic is different.  Before, it would inch the dialog top higher from 10vh to a minimum 5 pixel offset. The new logic jumps the dialog immediately to a 5 pixel offset as soon as the dialog height exceeds 90% of view height.

I like the idea of having the browser do the work, but this puts part of the logic in CSS, and another part in Javascript.  So, I'm not sure if this is an improvement.

**Comment by Abbe98** [comment]
@elebitzero the goal here is to only have logic for the edge case in JavaScript and leave the default positioning to CSS. I don't think the edge case motivates to have the default positioning in CSS.

The new code does indeed do less than the old code for that edge case but it allows one to remove the `visible`/`hidden` trick(that affects all rendering).

**Comment by Abbe98** [comment]
It's worth noting that the old code comment only address a part of what was going on when the edge case triggered. That said I'm not aware of a dialog that triggers the edge case to begin with, maybe in an extension somewhere?

**Comment by elebitzero** [comment]
For the visible/hidden trick, I just checked and I don't think that is necessary; we can remove that even with the existing code.

> That said I'm not aware of a dialog that triggers the edge case to begin with, maybe in an extension somewhere?

'Cluster and edit' and 'Templating export' are big dialogs. On some laptops, they may be > 100% of the browser window height.

**Pull request closed without merging**
