### PR TITLE
Deb package

### PR DESCRIPTION
**Pull request by pachamaltese**
@magdmartin here's the PR for now
it should be tested so let's work on a PPA later

### CODE REVIEW

**Comment by wetneb** [comment]
Hi @pachamaltese - thanks for this PR! However, there is a problem: you deleted most files from our repository. For OpenRefine to work, we need these files to stay.
Can you try making a new pull request without deleting any files? Thanks.

**Comment by magdmartin** [comment]
it was first PR for #1445 (linking the two tickets)

**Comment by magdmartin** [comment]
@pachamaltese  any update on the new PR?

**Comment by pachamaltese** [comment]
@magdmartin are you ok with a PPA or just a package that works for any Debian based distro?

**Comment by magdmartin** [comment]
@thadguidry @wetneb @jackyq2015  any preferences?

**Comment by thadguidry** [comment]
prefer the widest distro packaging...if that is .deb or whatever nowadays,  ppa seems limiting?

**Comment by wetneb** [comment]
Ideally a PPA would help I think - it is more useful than just a .deb file. I am not familiar with Debian's policies but in an ideal world we could try getting in the official repository. But that is probably a lengthy process.

**Pull request closed without merging**
