### PR TITLE
List facet changes

### PR DESCRIPTION
**Pull request by ostephens**
As per discussion #1662 this PR changes the behaviour of List facets.

With this PR, List facets will no longer convert non-string values of Dates, Numbers or Booleans to a string for display in the facet, but will instead group together these non-string types in the facet:

screen shot 2018-06-28 at 07 24 54

There is no 'edit' function next to these groupings.

Note, the 'mass edit' behaviour has not changed - which means that editing string values such as 'true' will also update cells containing the Boolean value of `true` - this is the same behaviour as 2.8 and earlier.

### CODE REVIEW

**Comment by thadguidry** [comment]
@ostephens Nice.  The functionality of it is fine for me.  Like I said before in issue, this can be enhanced further later on once we get a new UI, but for now its functions as expected.  Where later you might want to catch when they are about to mass edit a 'true' or 'false' and throw up a pop-up warning "This Edit will also update rows of boolean values True or False", since it is a bit unexpected when they see 2 groupings and select 1 to mass edit and lo-and-behold the other grouping also changes even when they didn't select it, but that's exactly what we have been doing since 2.0 days.

So up to you on warning dialogs, now or later.

**Comment by wetneb** [comment]
@ostephens I tried to fix the merge conflicts earlier but the tests did not pass after that. Could you have a look? It would be great to have this PR merged before 3.0.

**Comment by ostephens** [comment]
Just noticed that this PR breaks "Facet by blank" functionality. I think it's an easy fix, but I need to do this before this PR is merged.

**Comment by thadguidry** [comment]
One small question:  Are we OK with having "undefined" showing for null cells when using a Custom Facet with grel:value.type()  ?  Or should those cells show up in the facet as "null" ? hmmm...

capture

**Comment by wetneb** [comment]
The backwards incompatibility with previous workflows spotted by @ostephens worries me a bit. (Very good catch by the way!) Maybe we should only merge this after the next release, and make sure the changelog explains how to migrate existing workflows by adding the extra `.toString()` to the facet expressions.

**Comment by thadguidry** [comment]
No need to worry.  Folks that want to continue to have surprises in their data and hiding away those surprises can continue to use 2.8 and previous.  If they want less surprises and better Facets that show data inconsistencies then they can move forward with OpenRefine 3.0+  Those that move forward will have minimal changes to adapt their workflows.

This is one of those features where it will actually help our users, rather than surprise them.  Since we will no longer hide their data inconsistency, but expose that inconsistency fully with these Facet changes...so that they can deal with them and clean it up.

Merge it.

**Comment by ostephens** [comment]
@wetneb yes. As noted it potentially breaks reapplying transforms from previous versions of refine but @thadguiry has argued quite strongly to go ahead and I'm convinced

**Pull request merged**
