### PR TITLE
Update translation-es.json

### PR DESCRIPTION
**Pull request by nestorjal**
157: "Huella" according to my colleagues is the way they used that term in Big Data.
158: "Huella del n-grma" same as 157. 
456 to 465: for an easy reading I made some adjustments in the “menu” and in the “best-cand” options.
516: “Tiempo entre consultas” sounds better, because throttle-delay tells OpenRefine to wait the specified number of milliseconds between URL requests.

### CODE REVIEW

**Comment by thadguidry** [comment]
I agree except for 516.  Its more of a "Retraso de tiempo" or time delay.  Change and we can merge.

**Comment by nestorjal** [comment]
Thanks for the recomendation but "Retraso de tiempo" sounds weird, I think "Tiempo de retraso" is the appropriate term, since it's the amount of time to wait or "retraso" between requests.

**Comment by thadguidry** [comment]
+1 to "Tiempo de retraso"

**Comment by magdmartin** [comment]
Thank you for the correction. 
Please send new correction in a separate pull request.

**Pull request merged**
