### PR TITLE
Introducing OpenRefine Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [OpenRefine Guru](https://gurubase.io/g/openrefine) to Gurubase. OpenRefine Guru uses the data from this repo and data from the [docs](https://openrefine.org/docs) to answer questions by leveraging the LLM.

In this PR, I showcased the "OpenRefine Guru", which highlights that OpenRefine now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable OpenRefine Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by magdmartin** [comment]
It's interesting. However, when I asked how to [remove duplicates in OpenRefine](https://gurubase.io/g/openrefine/remove-duplicates-in-openrefine) (a basic operation we do not support well, leading to a lot of user questions), it forgot to mention the step "reorder rows permanently," which make the suggested process at risk of corrupting user data.

**Comment by Abbe98** [comment]
While I applaud the effort I don't think this is something we should link to this more prominently than our own docs.

**Comment by wetneb** [comment]
Agreed - thanks for reaching out though!

**Comment by kursataktas** [comment]
Thank you for taking the time to review it. We are continuously improving the system behind it. Would you be open to giving it a second chance once I believe it’s robust enough for another review?

I also want to mention that you can manage the data sources for OpenRefine Guru on Gurubase. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

If you’re uncomfortable, I can disable OpenRefine Guru on Gurubase as well.

**Pull request closed without merging**
