### PR TITLE
100% translation for translation-tl.json file

### PR DESCRIPTION
**Pull request by vinzruzell**
Hi. This is my Second Contribution and  Completed the Tagalog Translation for translation-tl.json file. 
Before:
I translated 299 strings (44.2 %) out of 676 strings.
I translated 1122 words out of 2508 words.
After: 
I completed the remaining Strings from 44.2% to 100%.
And from 1122 words to 2508 words.

### CODE REVIEW

**Comment by wetneb** [comment]
@vinzruzell thanks! but there is no need for this PR as you have already submitted your translations via Weblate (#1510).

**Comment by vinzruzell** [comment]
Is it automatically merge sir?

**Comment by wetneb** [comment]
yes, just click on the link I provided (#1510), read there and see that it has been merged.

**Comment by vinzruzell** [comment]
Thank you sir.

**Pull request closed without merging**
