### PR TITLE
Adding mostly-empty docs

### PR DESCRIPTION
**Pull request by allanaaa**
This update mirrors the structure from the proposal doc (https://docs.google.com/document/d/1cctIY0GPrvC2k3-BfDU0j7bVrzitua84ATSJWV7247w/edit?usp=sharing) (minus Recipes, still undecided) so we can see it live.

### CODE REVIEW

**Comment by allanaaa** [comment]
I'm not clear on what the Travis-CI error is indicating - I am assuming that if the Netlify preview looks good then I've done my job. Can someone let me know if there's anything I need to fix on my end?

**Comment by wetneb** [comment]
Fantastic! Do not worry about travis, it is indeed irrelevant for updates to the docs. The failure is spurious.

**Comment by allanaaa** [comment]
Thanks! 

You can merge this as-is and we can go from there - or if you'd prefer I work at a more granular level I can wipe the pages that already have some draft content. 
Offhand this includes the History section, Installing extensions, and all of Starting a project: 
https://deploy-preview-2892--openrefine-docs.netlify.app/manual/starting

**Comment by ostephens** [comment]
Looks good to me

**Comment by ostephens** [comment]
@thadguidry does this look good to you?

**Comment by thadguidry** [comment]
👍

**Pull request merged**
