### PR TITLE
Issue 3352 travis setup

### LINKED ISSUE #3352: Add UI tests to the CI/CD
The CI/CD must run cypress tests
With:
* Integration to the Cypress dashboard
* Multiple browser tests
* Proper matrix configuration, maybe there's no need to trigger tests on multiple browsers for each branch

### Proposed solution
Update the travis configuration.
Run tests on 
* Linux / firefox
* Linux / chrome 
* Osx / chrome
* Osx / firefox
* Linux / Edge

### Alternatives considered
CircleCI, does OpenRefine usr Circle CI ?

### PR DESCRIPTION
**Pull request by fgiroud**
This PR adds the UX tests to ./refine ui_test command, closes #3352

* Added Travis Matrix
* Fixed flaky tests
* Refactored/Fixed  some tests
* Tried integration with Cypress dashboard

### CODE REVIEW

**Comment by fgiroud** [comment]
See also #3367 about why there's no job for firefox testing

**Comment by fgiroud** [comment]
That would be nice if we have two things specifically reviewed
* the test must pass locally, that would ensure that the doc contains enough information for developers to run the tests
* the travis matrix, is that correct ? I can see only chrome tests have been runned, then, when does the full matrix is executed ? at merge time ?

**Comment by tfmorris** [comment]
Thanks! I changed "implemented" to "closes" in your original description so that Github recognizes it as an actionable keyword to link the original issue one.

> the travis matrix, is that correct ? I can see only chrome tests have been runned, then, when does the full matrix is executed ? at merge time ?

Yes, at merge time. You can change the build matrix so that both sets of browser tests get run on pull requests if you want. The reason the full Java matrix isn't run is because: a) it's rare that a test doesn't fail on all versions of Java, 2) some of the Java installs are flaky, and c) given a & b running them all is a waste of both resources and developers' time & attention.

The tradeoffs may be different for browser tests. Perhaps we should start with them all running all the time and then make a decision based on performance, failure rates, etc.

Items I noticed in testing:
* There doesn't appear to be any documentation of what I need to do to get started (unless I overlooked it). I eventually navigated to the test directory and did both `npm install` and `yarn install` but I don't know if both were necessary. The Readme there also seems to be out of date, so it points to an empty directory (`e2e`)
* All of the tests show red for duration for me. Can we change the threshold so that only the ones that take unexpectedly long show red?
* I got a warning - (node:30291) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

* The Test Runner crashed with a SIGABRT on my Mac after the Undo/Redo tests. This appears to be repeatable (at least twice).

```
/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/MacOS/Cypress[29848]: ../../third_party/electron_node/src/api/callback.cc:247:MaybeLocal<v8::Value> node::MakeCallback(v8::Isolate *, Local<v8::Object>, Local<v8::Function>, int, Local<v8::Value> *, node::async_context): Assertion `(env) != nullptr' failed.
 1: 0x10a6e0b15 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x10a6e092b node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x10a65b8e9 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x107a9d11c ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x1079a4894 ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x1079a2df7 ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x1079a2cb0 ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x10bc941f4 v8::internal::compiler::ZoneStats::GetCurrentAllocatedBytes() const [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x10b91c5a9 v8::internal::compiler::ZoneStats::GetCurrentAllocatedBytes() const [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x10872c3cd v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x107a266cb ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x107a2670e ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x107a28b2d ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x107a28963 ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x10873e589 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
16: 0x10873fc44 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
17: 0x10873b655 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
18: 0x108705ec1 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
19: 0x108705be6 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
20: 0x107f491ee ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
21: 0x107f496f2 ElectronInitializeICUandStartNode [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
22: 0x107962f48 ElectronMain [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
23: 0x101dbc5bd  [/Users/tfmorris/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/MacOS/Cypress]
24: 0x7fff738b8cc9 start [/usr/lib/system/libdyld.dylib]
25: 0x10 
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin (19.6.0)
Cypress Version: 6.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Killing OpenRefine
Cleaning up
Error: The UI test suite failed.

```

**Comment by wetneb** [comment]
@tfmorris docs are here: https://deploy-preview-3366--openrefine-docs.netlify.app/technical-reference/functional-tests

**Comment by tfmorris** [comment]
Thanks for the pointer. We need to have at least minimal directions in the README. That's where developers are going to look. It's only three lines of commands. It can include a link to the web page for more complete explanations if necessary. And, clearly, the incorrect README needs to be removed.

**Comment by fgiroud** [comment]
Hi @tfmorris, can you gives me the full log of your failed run ? I will also need to know which browser you used
Thank you

**Comment by wetneb** [comment]
Concerning the README, we could put a link to the online documentation (and perhaps path of the markdown file in the repository that generates it), to avoid duplication.

**Comment by floriangiroudrefinepro** [comment]
This needs to be re-done, following merge of PR #3378 
@wetneb I will rework this PR

**Comment by wetneb** [comment]
Yes, very sorry about this!

**Comment by tfmorris** [comment]
I haven't had a chance to retest, but will attempt to do so this weekend and will capture the log. 

Browser was Chrome Version 86.0.4240.193 (Official Build) (x86_64) on Mac OS X.

**Comment by floriangiroudrefinepro** [comment]
@wetneb I think we need to reject this PR
I've tried to rebase master into my branch to benefit from the latest updates, especially regarding github, but now it shows many commits
If you don't mind let's reject this and I will copy-paste my work on a fresh PR

**Comment by fgiroud** [comment]
@wetneb I think we need to reject this PR
I've tried to rebase master into my branch to benefit from the latest updates, especially regarding github, but now it shows many commits
If you don't mind let's reject this and I will copy-paste my work on a fresh PR

**Comment by tfmorris** [comment]
A couple of alternate strategies that you could use for this:
* `git diff --patch` the HEAD of your existing branch against the starting point that you used
* `git rebase -i HEAD~13` and squash all of your commits into one or a few logical commits that you could then `git cherry-pick` onto your new branch

You could also update and force push this branch if you want to keep the pull request history, but the priority should be whatever is easiest for you.

**Comment by wetneb** [comment]
@fgiroud it's entirely up to you, feel free to close this and open a new one. Sorry again for the trouble (I am *not* looking forward to doing the same migration on other repositories I am involved in…)

**Pull request closed without merging**
