### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/openrefine/translations/) for OpenRefine/Translations.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by wetneb — APPROVED** [review]

**Comment by kushthedude** [comment]
Hi @wetneb , here occurred the error which is falling tests in your pr #3634 . Looks like @weblate doesnt update the prs with the updated master hence the error occurred on this branch yet was fixed on master.

**Comment by wetneb** [comment]
Wow, I really don't get it! How could a weblate PR be the cause of a linting failure in #3634? It did not touch the offending files at all, right?

**Comment by kushthedude** [comment]
Yes it didn't touch the offending files, what happened here is when the PR https://github.com/OpenRefine/OpenRefine/pull/3601 was made, we did the change in ci scripts to use `yarn lint` which was already committed on master, but it was not committed in the fork's branch. So the old code was run into the modified ci script which also didn't let the ci fail as it was mistake over a mistake. I know how confusing this can be but to sum it up, unlisted files were committed in PR https://github.com/OpenRefine/OpenRefine/pull/3601 which were not detected by our ci due to the pull_request_target trigger which takes the ci workflow of the Openrefine/master but use the code of {Fork_User}/branch from where the PR was made.

**Comment by kushthedude** [comment]
Let me fix it asap!

**Pull request merged**
