### PR TITLE
Re-fetch Service Manifest when selecting a service

### LINKED ISSUE #3645: Double check the reconciliation manifest each time reconciliation is fired.
This is not a high priority issue, but while developing a reconciliation service, I stopped and start the service several times while making modifications.  It looks like the service manifest is only checked when the service is added.  So that if it changes between restarts changes to the manifest are not picked up unless the service is deleted and restarted.

### Proposed solution

Perhaps we could take a hash of the service manifest and recheck that the hash hasn't changed since the service was added.  Admittedly this likely covers a narrow set of cases, but it doesn't sound hard to implement either.  If the hash doesn't match, then maybe we could automatically delete the service and then readd it, perhaps with a dialog asking the user to opt in (though I don't know when someone would want to opt out...)

### Additional context

Again, this is a pretty small issue because the actual reconciliation queries seem to go through just fine with the restarted service.  Though, thinking about it more, there may be a need to keep the manifest in sync to support features.  (I haven't implemented any in my service.)

### PR DESCRIPTION
**Pull request by v1scal**
Fixes #3645

Changes proposed in this pull request:
- Re-fetch Service Manifest when selecting a service
- Update the Manifest in the Preferences

### CODE REVIEW

**Review by wetneb — COMMENTED** [review]
Thanks! I haven't tried it yet, but I noticed two things:
* the identation seems a bit off
* this is likely to fail for services which only support fetching the manifest via JSONP. It would be good to preserve support for that. For this reason, it might make sense to encapsulate the existing logic of fetching the manifest (from the dialog to add a new service) into a function that you could reuse here.

**Comment by v1scal** [comment]
Ok, I'll work on that. Thanks!

**Comment by v1scal** [comment]
@wetneb I've already added the JSONP but didn't fully understand what you meant by reusing the function. Should I put the refetch in a separate method and call it or try to use the one in recon-manager.js?

**Comment by wetneb** [comment]
I mean that the logic to fetch a manifest first via CORS and then via JSONP should intuitively be the same in two places:
* when adding a new service
* when checking its manifest again before using it

so it would probably make sense not to duplicate code and use a common javascript function / method to implement this fetching.

Also, there are still a lot of indentation changes so it is hard to figure out where you made actual changes. Could you revert those indentation changes?

**Comment by wetneb** [comment]
Hi @v1scal, are you still working on this?

**Comment by wetneb** [comment]
Closing per inactivity, but happy to reopen if activity resumes.

**Pull request closed without merging**
