### PR TITLE
Issue 6316 replace logo

### LINKED ISSUE #6316: Use SVG logo and icons instead of png
Hello,
I was very surprised to see OpenRefine still use a png image for its logos displayed in the application
image

image

SVG (vector image format) are great : fast, light, can resize easily, etc.. and work perfectly in a web browser. Moreover, it's not a lot of work since the logo is already available in svg
https://fr.wikipedia.org/wiki/OpenRefine#/media/Fichier:OpenRefine_favicon_(2018-present).svg

### Proposed solution
To use svg version of these pictures

### Alternatives considered
N/A
### Additional context
N/A

### PR DESCRIPTION
**Pull request by Sophia3287**
Fixes #6316 

Changes proposed in this pull request:
- use logo-gem-126.svg replace logo-gem-126.png
- 
-

### CODE REVIEW

**Comment by wetneb** [comment]
@Sophia3287 thanks for this! It looks like you have used the same branch to submit two different pull requests (this one and #6618), meaning that both PRs contain unrelated changes. You can see that with the list of commits on this page, as well as in the "Files changed" tab of each PR. Could you try again and submit PRs that only contain the changes they describe?

**Comment by xinluz6** [comment]
Hi, thank you for pointing this out, we are really sorry about that. Right now I tried to revert the unrelated commits under these two pull requests, is that okay or we better create the new pull requests again? Thanks for your help.

**Comment by wetneb** [comment]
I think it's probably better to create new pull requests. In general, the workflow I would recommend would be to:
* don't push any of your own commits to the master branch of your fork
* create one branch for each PR, branching off from the master branch of your fork
* from time to time, you can use the "Sync" button in GitHub to update your master branch to the master branch of the upstream repository

**Comment by xinluz6** [comment]
Ok I got this, thank you for your help

**Comment by wetneb** [comment]
Superseded by #6620.

**Pull request closed without merging**
