### PR TITLE
(I#1286)

### PR DESCRIPTION
**Pull request by shriyasankhyan**
(I#1286)

Changes proposed in this pull request:
- Control characters are shown in the parsing panel by default.

### CODE REVIEW

**Comment by wetneb** [comment]
Could you integrate that in your other pull request instead?

**Comment by shriyasankhyan** [comment]
> Could you integrate that in your other pull request instead? (#4758)

I had integrated it in that only but afterward, one test is failing in this, so I made another pull request for this.

**Comment by wetneb** [comment]
Thank you! Closing this one then.

**Comment by shriyasankhyan** [comment]
> Thank you! Closing this one then.

Ok :-)

**Pull request closed without merging**
