### PR TITLE
Adds a default separator preference for split/join multi valued cells

### PR DESCRIPTION
**Pull request by lisa761**
Closes part 1 of #2197

### CODE REVIEW

**Comment by thadguidry** [comment]
@wetneb Hmm, I don't know.  This might actually end up being a bit useful as a permanent preference depending on your daily life in your domain.  I'm thinking of subfields in archival formats in GLAM.  Examples of separator pattern they might want to store: `##$a` or `##$z`

**Comment by lisa761** [comment]
Can we ask for some more opinions then?

**Comment by wetneb** [comment]
To merge this, I think it would be worth using the new JS interface to access the preferences introduced by @antoine2711. I am not opposed to storing it in the preferences (for the sake of getting out of this stalemate).

**Comment by antoine2711** [comment]
> To merge this, I think it would be worth using the new JS interface to access the preferences introduced by @antoine2711. I am not opposed to storing it in the preferences (for the sake of getting out of this stalemate).

@lisa761 & @wetneb: I can confirm that #2624 implements these two JS functions and is now merged in the master branch (v3.5):
```
Refine.getPreference(key, defaultValue) => return a string
Refine.setPreference(key, newValue)
```

Regards,
   Antoine

**Comment by wetneb** [comment]
@tfmorris any thoughts about the preference key to use for this? (should we prefix it like the others?)

**Comment by tfmorris** [comment]
Yes, a prefix would be good. It provides a simple namespacing mechanism. Our naming scheme is kind of a mess, but let's try to not make it worse.

How about something along the lines of `ui.edit.defaultSeparator`? Do we need to qualify separator any more in this context (ie will we have multiple types of editing default separators)?

Here's a sampling of what we have now (along with suggested cleaner names, but it might be too late to rename things):

```
cell-ui.previewMatchedCells => ui.cell.previewMatchedCells
exporters.templating.template
reconciliation.standardServices
ui.gridPaginationSize => ui.browsing.pageSize
ui.browsing.listFacet.limit
userMetadata

```

**Comment by lisa761** [comment]
@tfmorris There's also a split/join operation for columns. But we don't have a preference setting for it's default value yet.

**Comment by ostephens** [comment]
I think `ui.cell` better than `ui.edit.cell`

Anticipating that we might have a preference for split/join columns at some point I'd suggest we are specific with this naming, so suggest something like:

`ui.cell.rowSplitDefaultSeparator`

This allows us to have `ui.cell.columnSplitDefaultSeparator` in future if we want. I think having these separate is a good idea because when you are doing data manipulations that uses both operations together you need different separators for each way you are splitting

**Pull request merged**
