### PR TITLE
feat: add tests for project parsing options

### LINKED ISSUE #3429: Add UX tests for the create project preview
Screen Shot 2020-12-16 at 14 36 13

#### Start over behavior

Add a test to start over a project creation.
Just ensure the user is redirected to the previous page.

#### Rename the project add tags

Rename the project and add tags.   
Ensure those modifications are persisted (when visiting the project list page ? or is there a better way to do it ?)

#### Navigation

Ensure that once a project reaches the preview step, a user can navigate back&forth to other screens of OpenRefine (language for example)

#### Parsing Options

Does it make sense to test each and every parsing option? It looks like a backend matter.
Looking at the requests, they are similar, whatever the option is (importing-controller, get-models, get-rows)

To start, we could have an MVP test that would

* load a CSV
* change a few parsing options, and ensure the grid reflect those changes

This simple test could be duplicated with JSON data to have better coverage.

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: kushthedude <kushthedude@gmail.com>

Fixes #3429

Changes proposed in this pull request:
- adds a test for project-parsing options
- renames a wrong named test suite to follow correct conventions.

### CODE REVIEW

**Comment by kushthedude** [comment]
@fgiroud I have removed all wait condition and added a handy command for waiting in import-update. Please review

**Comment by fgiroud** [comment]
@kushthedude I can see a selector for `cy.contains('1.')`, is it possible to find a better selector for that ?
It makes the test difficult to understand, and it's probably prone to failures in case there's a new element containing `1.`

**Comment by kushthedude** [comment]
@fgiroud changed the selector, please review and merge

**Comment by fgiroud** [comment]
@kushthedude apologies for the very long delay
`navigateToProjectPreview`is very specific to the preview_project.spec.js test suite, shall we move it within the test ?
I would like to keep commands to generic, reusable Openrefine commands and actions

**Review by fgiroud — APPROVED** [review]

**Review by fgiroud — APPROVED** [review]

**Comment by kushthedude** [comment]
@fgiroud there is a issue in code for frequent failures of the tests like in this one. Let me make a PR for that!

**Comment by kushthedude** [comment]
@fgiroud this is good to be merged now as the frequent ci failures are gone.

**Comment by fgiroud** [comment]
@kushthedude are you sure that's okay to re-open a PR?
I would need confirmation, maybe from @wetneb to be sure this is not something that goes against the rules of the community

**Comment by kushthedude** [comment]
I dont even know why this PR was closed, as the timeout pr was just an extension to this not something which adds test.

**Comment by wetneb** [comment]
Not sure why the other PR closed this one… No problem with reopening PRs in general as far as I can see.

**Pull request merged**
